
// Generated by Cadence Genus(TM) Synthesis Solution 16.12-s027_1
// Generated on: Jun 12 2019 22:53:12 CEST (Jun 12 2019 20:53:12 UTC)

// Verification Directory fv/elevator 

module buttons_res(clock, an_reset, buttons_block, btn_in, btn_up_out,
     btn_down_out, inactivate_in_levels, inactivate_out_up_levels,
     inactivate_out_down_levels, active_in_levels,
     active_out_up_levels, active_out_down_levels);
  input clock, an_reset, buttons_block;
  input [7:0] btn_in, inactivate_in_levels;
  input [6:0] btn_up_out, inactivate_out_up_levels;
  input [7:1] btn_down_out, inactivate_out_down_levels;
  output [7:0] active_in_levels;
  output [6:0] active_out_up_levels;
  output [7:1] active_out_down_levels;
  wire clock, an_reset, buttons_block;
  wire [7:0] btn_in, inactivate_in_levels;
  wire [6:0] btn_up_out, inactivate_out_up_levels;
  wire [7:1] btn_down_out, inactivate_out_down_levels;
  wire [7:0] active_in_levels;
  wire [6:0] active_out_up_levels;
  wire [7:1] active_out_down_levels;
  wire [7:0] l_btn_in;
  wire [7:0] l_inactivate_in_levels;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_133;
  TLATX2M \active_out_up_levels_reg[0] (.G (n_72), .D (n_69), .Q
       (active_out_up_levels[0]), .QN (UNCONNECTED));
  TLATX2M \active_out_down_levels_reg[7] (.G (n_73), .D (n_71), .Q
       (active_out_down_levels[7]), .QN (UNCONNECTED0));
  OAI21XLM g3393(.A0 (buttons_block), .A1 (n_70), .B0 (an_reset), .Y
       (n_73));
  OAI21XLM g3394(.A0 (buttons_block), .A1 (n_68), .B0 (an_reset), .Y
       (n_72));
  NAND3BXLM g3395(.AN (buttons_block), .B (btn_in[0]), .C
       (l_btn_in[0]), .Y (n_133));
  DFFRQX2M \l_btn_in_reg[1] (.RN (an_reset), .CK (clock), .D
       (btn_in[1]), .Q (l_btn_in[1]));
  DFFRQX2M \l_inactivate_in_levels_reg[1] (.RN (an_reset), .CK (clock),
       .D (inactivate_in_levels[1]), .Q (l_inactivate_in_levels[1]));
  DFFRQX2M \l_inactivate_in_levels_reg[2] (.RN (an_reset), .CK (clock),
       .D (inactivate_in_levels[2]), .Q (l_inactivate_in_levels[2]));
  DFFRQX2M \l_btn_in_reg[2] (.RN (an_reset), .CK (clock), .D
       (btn_in[2]), .Q (l_btn_in[2]));
  DFFRQX2M \l_inactivate_in_levels_reg[3] (.RN (an_reset), .CK (clock),
       .D (inactivate_in_levels[3]), .Q (l_inactivate_in_levels[3]));
  DFFRQX2M \l_inactivate_in_levels_reg[4] (.RN (an_reset), .CK (clock),
       .D (inactivate_in_levels[4]), .Q (l_inactivate_in_levels[4]));
  DFFRQX2M \l_btn_in_reg[3] (.RN (an_reset), .CK (clock), .D
       (btn_in[3]), .Q (l_btn_in[3]));
  DFFRQX2M \l_inactivate_in_levels_reg[5] (.RN (an_reset), .CK (clock),
       .D (inactivate_in_levels[5]), .Q (l_inactivate_in_levels[5]));
  DFFRQX2M \l_inactivate_in_levels_reg[6] (.RN (an_reset), .CK (clock),
       .D (inactivate_in_levels[6]), .Q (l_inactivate_in_levels[6]));
  DFFRQX2M \l_btn_in_reg[4] (.RN (an_reset), .CK (clock), .D
       (btn_in[4]), .Q (l_btn_in[4]));
  DFFRQX2M \l_inactivate_in_levels_reg[7] (.RN (an_reset), .CK (clock),
       .D (inactivate_out_down_levels[7]), .Q
       (l_inactivate_in_levels[7]));
  DFFRQX2M \l_btn_in_reg[5] (.RN (an_reset), .CK (clock), .D
       (btn_in[5]), .Q (l_btn_in[5]));
  DFFRQX2M \l_btn_in_reg[6] (.RN (an_reset), .CK (clock), .D
       (btn_in[6]), .Q (l_btn_in[6]));
  DFFRQX2M \l_btn_in_reg[7] (.RN (an_reset), .CK (clock), .D
       (btn_in[7]), .Q (l_btn_in[7]));
  DFFRX1M \l_btn_in_reg[0] (.RN (an_reset), .CK (clock), .D
       (btn_in[0]), .Q (UNCONNECTED1), .QN (l_btn_in[0]));
  DFFRQX2M \l_inactivate_in_levels_reg[0] (.RN (an_reset), .CK (clock),
       .D (inactivate_out_up_levels[0]), .Q
       (l_inactivate_in_levels[0]));
  CLKAND2X2M g3412(.A (an_reset), .B (btn_down_out[7]), .Y (n_71));
  NOR2XLM g3413(.A (inactivate_out_down_levels[7]), .B
       (btn_down_out[7]), .Y (n_70));
  CLKAND2X2M g3414(.A (an_reset), .B (btn_up_out[0]), .Y (n_69));
  NOR2XLM g3415(.A (inactivate_out_up_levels[0]), .B (btn_up_out[0]),
       .Y (n_68));
  DFFRQX2M \active_in_levels_reg[0] (.RN (an_reset), .CK (clock), .D
       (n_60), .Q (active_in_levels[0]));
  DFFRQX2M \active_in_levels_reg[1] (.RN (an_reset), .CK (clock), .D
       (n_64), .Q (active_in_levels[1]));
  DFFRQX2M \active_in_levels_reg[2] (.RN (an_reset), .CK (clock), .D
       (n_62), .Q (active_in_levels[2]));
  DFFRQX2M \active_in_levels_reg[3] (.RN (an_reset), .CK (clock), .D
       (n_63), .Q (active_in_levels[3]));
  DFFRQX2M \active_in_levels_reg[4] (.RN (an_reset), .CK (clock), .D
       (n_61), .Q (active_in_levels[4]));
  DFFRQX2M \active_in_levels_reg[5] (.RN (an_reset), .CK (clock), .D
       (n_66), .Q (active_in_levels[5]));
  DFFRQX2M \active_in_levels_reg[6] (.RN (an_reset), .CK (clock), .D
       (n_67), .Q (active_in_levels[6]));
  DFFRQX2M \active_in_levels_reg[7] (.RN (an_reset), .CK (clock), .D
       (n_65), .Q (active_in_levels[7]));
  TLATX2M \active_out_down_levels_reg[1] (.G (n_51), .D (n_14), .Q
       (active_out_down_levels[1]), .QN (UNCONNECTED2));
  TLATX2M \active_out_down_levels_reg[2] (.G (n_50), .D (n_24), .Q
       (active_out_down_levels[2]), .QN (UNCONNECTED3));
  TLATX2M \active_out_down_levels_reg[3] (.G (n_49), .D (n_17), .Q
       (active_out_down_levels[3]), .QN (UNCONNECTED4));
  TLATX2M \active_out_down_levels_reg[4] (.G (n_48), .D (n_16), .Q
       (active_out_down_levels[4]), .QN (UNCONNECTED5));
  TLATX2M \active_out_down_levels_reg[5] (.G (n_47), .D (n_10), .Q
       (active_out_down_levels[5]), .QN (UNCONNECTED6));
  TLATX2M \active_out_down_levels_reg[6] (.G (n_46), .D (n_13), .Q
       (active_out_down_levels[6]), .QN (UNCONNECTED7));
  TLATX2M \active_out_up_levels_reg[1] (.G (n_45), .D (n_11), .Q
       (active_out_up_levels[1]), .QN (UNCONNECTED8));
  TLATX2M \active_out_up_levels_reg[2] (.G (n_44), .D (n_21), .Q
       (active_out_up_levels[2]), .QN (UNCONNECTED9));
  TLATX2M \active_out_up_levels_reg[3] (.G (n_43), .D (n_2), .Q
       (active_out_up_levels[3]), .QN (UNCONNECTED10));
  TLATX2M \active_out_up_levels_reg[4] (.G (n_42), .D (n_12), .Q
       (active_out_up_levels[4]), .QN (UNCONNECTED11));
  TLATX2M \active_out_up_levels_reg[5] (.G (n_41), .D (n_18), .Q
       (active_out_up_levels[5]), .QN (UNCONNECTED12));
  TLATX2M \active_out_up_levels_reg[6] (.G (n_52), .D (n_1), .Q
       (active_out_up_levels[6]), .QN (UNCONNECTED13));
  OAI21XLM g4037(.A0 (inactivate_in_levels[6]), .A1 (n_57), .B0 (n_28),
       .Y (n_67));
  OAI21XLM g4038(.A0 (inactivate_in_levels[5]), .A1 (n_58), .B0 (n_33),
       .Y (n_66));
  OAI21XLM g4039(.A0 (inactivate_out_down_levels[7]), .A1 (n_56), .B0
       (n_31), .Y (n_65));
  OAI21XLM g4040(.A0 (inactivate_in_levels[1]), .A1 (n_55), .B0 (n_29),
       .Y (n_64));
  OAI21XLM g4041(.A0 (inactivate_in_levels[3]), .A1 (n_53), .B0 (n_32),
       .Y (n_63));
  OAI21XLM g4042(.A0 (inactivate_in_levels[2]), .A1 (n_54), .B0 (n_27),
       .Y (n_62));
  OAI21XLM g4043(.A0 (inactivate_in_levels[4]), .A1 (n_59), .B0 (n_26),
       .Y (n_61));
  OAI21XLM g4057(.A0 (inactivate_out_up_levels[0]), .A1 (n_25), .B0
       (n_30), .Y (n_60));
  AOI2BB2XLM g4058(.A0N (n_37), .A1N (active_in_levels[4]), .B0 (n_37),
       .B1 (active_in_levels[4]), .Y (n_59));
  AOI2BB2XLM g4059(.A0N (n_40), .A1N (active_in_levels[5]), .B0 (n_40),
       .B1 (active_in_levels[5]), .Y (n_58));
  AOI2BB2XLM g4060(.A0N (n_39), .A1N (active_in_levels[6]), .B0 (n_39),
       .B1 (active_in_levels[6]), .Y (n_57));
  AOI2BB2XLM g4061(.A0N (n_38), .A1N (active_in_levels[7]), .B0 (n_38),
       .B1 (active_in_levels[7]), .Y (n_56));
  AOI2BB2XLM g4062(.A0N (n_34), .A1N (active_in_levels[1]), .B0 (n_34),
       .B1 (active_in_levels[1]), .Y (n_55));
  AOI2BB2XLM g4063(.A0N (n_36), .A1N (active_in_levels[2]), .B0 (n_36),
       .B1 (active_in_levels[2]), .Y (n_54));
  AOI2BB2XLM g4064(.A0N (n_35), .A1N (active_in_levels[3]), .B0 (n_35),
       .B1 (active_in_levels[3]), .Y (n_53));
  OAI21XLM g4065(.A0 (buttons_block), .A1 (n_3), .B0 (an_reset), .Y
       (n_52));
  OAI21XLM g4066(.A0 (buttons_block), .A1 (n_19), .B0 (an_reset), .Y
       (n_51));
  OAI21XLM g4067(.A0 (buttons_block), .A1 (n_8), .B0 (an_reset), .Y
       (n_50));
  OAI21XLM g4068(.A0 (buttons_block), .A1 (n_22), .B0 (an_reset), .Y
       (n_49));
  OAI21XLM g4069(.A0 (buttons_block), .A1 (n_5), .B0 (an_reset), .Y
       (n_48));
  OAI21XLM g4070(.A0 (buttons_block), .A1 (n_20), .B0 (an_reset), .Y
       (n_47));
  OAI21XLM g4071(.A0 (buttons_block), .A1 (n_9), .B0 (an_reset), .Y
       (n_46));
  OAI21XLM g4072(.A0 (buttons_block), .A1 (n_6), .B0 (an_reset), .Y
       (n_45));
  OAI21XLM g4073(.A0 (buttons_block), .A1 (n_15), .B0 (an_reset), .Y
       (n_44));
  OAI21XLM g4074(.A0 (buttons_block), .A1 (n_7), .B0 (an_reset), .Y
       (n_43));
  OAI21XLM g4075(.A0 (buttons_block), .A1 (n_4), .B0 (an_reset), .Y
       (n_42));
  OAI21XLM g4076(.A0 (buttons_block), .A1 (n_23), .B0 (an_reset), .Y
       (n_41));
  NAND3XLM g4077(.A (inactivate_in_levels[5]), .B
       (active_in_levels[5]), .C (l_inactivate_in_levels[5]), .Y
       (n_33));
  NAND3BXLM g4078(.AN (l_btn_in[5]), .B (btn_in[5]), .C (n_0), .Y
       (n_40));
  NAND3BXLM g4079(.AN (l_btn_in[6]), .B (btn_in[6]), .C (n_0), .Y
       (n_39));
  NAND3BXLM g4080(.AN (l_btn_in[7]), .B (btn_in[7]), .C (n_0), .Y
       (n_38));
  NAND3BXLM g4081(.AN (l_btn_in[4]), .B (btn_in[4]), .C (n_0), .Y
       (n_37));
  NAND3BXLM g4082(.AN (l_btn_in[2]), .B (btn_in[2]), .C (n_0), .Y
       (n_36));
  NAND3BXLM g4083(.AN (l_btn_in[3]), .B (btn_in[3]), .C (n_0), .Y
       (n_35));
  NAND3BXLM g4084(.AN (l_btn_in[1]), .B (btn_in[1]), .C (n_0), .Y
       (n_34));
  NAND3XLM g4085(.A (inactivate_in_levels[3]), .B
       (active_in_levels[3]), .C (l_inactivate_in_levels[3]), .Y
       (n_32));
  NAND3XLM g4086(.A (inactivate_out_down_levels[7]), .B
       (active_in_levels[7]), .C (l_inactivate_in_levels[7]), .Y
       (n_31));
  NAND3XLM g4087(.A (inactivate_out_up_levels[0]), .B
       (active_in_levels[0]), .C (l_inactivate_in_levels[0]), .Y
       (n_30));
  NAND3XLM g4088(.A (inactivate_in_levels[1]), .B
       (active_in_levels[1]), .C (l_inactivate_in_levels[1]), .Y
       (n_29));
  NAND3XLM g4089(.A (inactivate_in_levels[6]), .B
       (active_in_levels[6]), .C (l_inactivate_in_levels[6]), .Y
       (n_28));
  NAND3XLM g4090(.A (inactivate_in_levels[2]), .B
       (active_in_levels[2]), .C (l_inactivate_in_levels[2]), .Y
       (n_27));
  NAND3XLM g4091(.A (inactivate_in_levels[4]), .B
       (active_in_levels[4]), .C (l_inactivate_in_levels[4]), .Y
       (n_26));
  AOI2BB2XLM g4092(.A0N (n_133), .A1N (active_in_levels[0]), .B0
       (n_133), .B1 (active_in_levels[0]), .Y (n_25));
  CLKAND2X2M g4093(.A (an_reset), .B (btn_down_out[2]), .Y (n_24));
  NOR2XLM g4094(.A (inactivate_out_up_levels[5]), .B (btn_up_out[5]),
       .Y (n_23));
  NOR2XLM g4095(.A (inactivate_out_down_levels[3]), .B
       (btn_down_out[3]), .Y (n_22));
  CLKAND2X2M g4096(.A (an_reset), .B (btn_up_out[2]), .Y (n_21));
  NOR2XLM g4097(.A (inactivate_out_down_levels[5]), .B
       (btn_down_out[5]), .Y (n_20));
  NOR2XLM g4098(.A (inactivate_out_down_levels[1]), .B
       (btn_down_out[1]), .Y (n_19));
  CLKAND2X2M g4099(.A (an_reset), .B (btn_up_out[5]), .Y (n_18));
  CLKAND2X2M g4100(.A (an_reset), .B (btn_down_out[3]), .Y (n_17));
  CLKAND2X2M g4101(.A (an_reset), .B (btn_down_out[4]), .Y (n_16));
  NOR2XLM g4102(.A (inactivate_out_up_levels[2]), .B (btn_up_out[2]),
       .Y (n_15));
  CLKAND2X2M g4103(.A (an_reset), .B (btn_down_out[1]), .Y (n_14));
  CLKAND2X2M g4104(.A (an_reset), .B (btn_down_out[6]), .Y (n_13));
  CLKAND2X2M g4105(.A (an_reset), .B (btn_up_out[4]), .Y (n_12));
  CLKAND2X2M g4106(.A (an_reset), .B (btn_up_out[1]), .Y (n_11));
  CLKAND2X2M g4107(.A (an_reset), .B (btn_down_out[5]), .Y (n_10));
  NOR2XLM g4108(.A (inactivate_out_down_levels[6]), .B
       (btn_down_out[6]), .Y (n_9));
  NOR2XLM g4109(.A (inactivate_out_down_levels[2]), .B
       (btn_down_out[2]), .Y (n_8));
  NOR2XLM g4110(.A (inactivate_out_up_levels[3]), .B (btn_up_out[3]),
       .Y (n_7));
  NOR2XLM g4111(.A (inactivate_out_up_levels[1]), .B (btn_up_out[1]),
       .Y (n_6));
  NOR2XLM g4112(.A (inactivate_out_down_levels[4]), .B
       (btn_down_out[4]), .Y (n_5));
  NOR2XLM g4113(.A (inactivate_out_up_levels[4]), .B (btn_up_out[4]),
       .Y (n_4));
  NOR2XLM g4114(.A (inactivate_out_up_levels[6]), .B (btn_up_out[6]),
       .Y (n_3));
  CLKAND2X2M g4115(.A (an_reset), .B (btn_up_out[3]), .Y (n_2));
  CLKAND2X2M g4116(.A (an_reset), .B (btn_up_out[6]), .Y (n_1));
  INVX2M g4117(.A (buttons_block), .Y (n_0));
endmodule

module elevator(clock, an_reset, buttons_block, open_btn, close_btn,
     overload, bell, sensor_up, sensor_down, sensor_inside,
     sensor_door, btn_in, btn_up_out, btn_down_out, engine, door,
     direction, bell_out, level_display);
  input clock, an_reset, buttons_block, open_btn, close_btn, overload,
       bell, sensor_up, sensor_down, sensor_inside;
  input [1:0] sensor_door;
  input [7:0] btn_in;
  input [6:0] btn_up_out;
  input [7:1] btn_down_out;
  output [1:0] engine, door;
  output direction, bell_out;
  output [3:0] level_display;
  wire clock, an_reset, buttons_block, open_btn, close_btn, overload,
       bell, sensor_up, sensor_down, sensor_inside;
  wire [1:0] sensor_door;
  wire [7:0] btn_in;
  wire [6:0] btn_up_out;
  wire [7:1] btn_down_out;
  wire [1:0] engine, door;
  wire direction, bell_out;
  wire [3:0] level_display;
  wire [7:0] inactivate_in_levels;
  wire [6:0] inactivate_out_up_levels;
  wire [7:1] inactivate_out_down_levels;
  wire [7:0] active_in_levels;
  wire [6:0] active_out_up_levels;
  wire [7:1] active_out_down_levels;
  wire [4:0] state;
  wire [15:0] counter;
  wire [1:0] i_engine;
  wire [4:0] saved_state;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, closing, i_direction,
       letout, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_143, n_144, n_145, n_146, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_210, n_211, n_212, n_213, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_253, n_254, n_255, n_256, n_257, n_258;
  wire n_259, n_260, n_261, n_262, n_263, n_264, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_300, n_301, n_302, n_303, n_304, n_305, n_306, n_307;
  wire n_308, n_309, n_310, n_311, n_312, n_313, n_314, n_315;
  wire n_316, n_317, n_318, n_319, n_320, n_321, n_322, n_323;
  wire n_324, n_325, n_326, n_327, n_328, n_329, n_330, n_331;
  wire n_332, n_333, n_334, n_335, n_336, n_337, n_338, n_339;
  wire n_340, n_341, n_342, n_343, n_344, n_345, n_346, n_347;
  wire n_348, n_349, n_350, n_351, n_352, n_353, n_354, n_355;
  wire n_356, n_357, n_358, n_359, n_360, n_361, n_362, n_363;
  wire n_364, n_365, n_366, n_367, n_368, n_369, n_370, n_371;
  wire n_372, n_373, n_374, n_375, n_376, n_377, n_378, n_379;
  wire n_380, n_381, n_382, n_383, n_384, n_385, n_386, n_387;
  wire n_388, n_389, n_390, n_391, n_392, n_393, n_394, n_395;
  wire n_396, n_397, n_399, n_400, n_401, n_402, n_403, n_404;
  wire n_405, n_406, n_407, n_408, n_409, n_410, n_411, n_412;
  wire n_413, n_414, n_415, n_416, n_418, n_419, n_420, n_421;
  wire n_422, n_423, n_424, n_425, n_426, n_427, n_428, n_429;
  wire n_430, n_431, n_432, n_433, n_434, n_435, n_437, n_438;
  wire n_439, n_440, n_441, n_442, n_443, n_444, n_445, n_446;
  wire n_447, n_448, n_449, n_450, n_451, n_452, n_453, n_454;
  wire n_455, n_456, n_457, n_458, n_459, n_460, n_461, n_462;
  wire n_463, n_464, n_465, n_466, n_467, n_468, n_469, n_470;
  wire n_471, n_472, n_473, n_474, n_475, n_476, n_477, n_478;
  wire n_479, n_480, n_481, n_482, n_483, n_484, n_485, n_486;
  wire n_487, n_488, n_489, n_490, n_491, n_492, n_493, n_494;
  wire n_495, n_496, n_497, n_498, n_499, n_500, n_501, n_502;
  wire n_503, n_504, n_505, n_506, n_507, n_508, n_509, n_510;
  wire n_511, n_512, n_513, n_514, n_515, n_516, n_517, n_518;
  wire n_519, n_520, n_521, n_522, n_523, n_524, n_525, n_526;
  wire n_527, n_528, n_529, n_530, n_531, n_532, n_533, n_534;
  wire n_535, n_536, n_537, n_538, n_539, n_540, n_541, n_542;
  wire n_543, n_544, n_545, n_546, n_547, n_548, n_549, n_550;
  wire n_551, n_552, n_553, n_554, n_555, n_556, n_557, n_558;
  wire n_559, n_561, n_563, n_564, n_565, n_566, n_567, n_568;
  wire n_569, n_570, n_571, n_572, n_573, n_574, n_575, n_576;
  wire n_577, n_589, n_590, n_620, n_622, n_623, n_624, n_625;
  wire n_627, n_630, n_631, n_632, n_633, n_634, opening, reached;
  wire waiting;
  buttons_res buttons_inst(.clock (clock), .an_reset (an_reset),
       .buttons_block (buttons_block), .btn_in (btn_in), .btn_up_out
       (btn_up_out), .btn_down_out (btn_down_out),
       .inactivate_in_levels ({UNCONNECTED_HIER_Z0,
       inactivate_in_levels[6:1], UNCONNECTED_HIER_Z}),
       .inactivate_out_up_levels ({inactivate_out_up_levels[6:1],
       inactivate_in_levels[0]}), .inactivate_out_down_levels
       ({inactivate_in_levels[7], inactivate_out_down_levels[6:1]}),
       .active_in_levels (active_in_levels), .active_out_up_levels
       (active_out_up_levels), .active_out_down_levels
       (active_out_down_levels));
  AO21XLM g21283(.A0 (n_624), .A1 (n_627), .B0 (buttons_block), .Y
       (n_565));
  NOR2BXLM g21284(.AN (n_569), .B (letout), .Y (n_564));
  NOR2BXLM g21285(.AN (n_570), .B (letout), .Y (n_563));
  AO21XLM g21286(.A0 (n_623), .A1 (n_620), .B0 (buttons_block), .Y
       (n_566));
  NOR2BXLM g21287(.AN (n_622), .B (letout), .Y (n_589));
  NOR2BXLM g21288(.AN (n_625), .B (letout), .Y (n_590));
  NOR2BX1MTH g21289(.AN (n_625), .B (buttons_block), .Y (n_570));
  NOR3BX2M g21290(.AN (n_571), .B (state[2]), .C (state[1]), .Y
       (n_624));
  AND4XLM g21291(.A (n_572), .B (n_573), .C (state[0]), .D (n_13), .Y
       (n_569));
  CLKAND2X2M g21292(.A (n_571), .B (n_572), .Y (n_623));
  NOR2XLM g21293(.A (n_574), .B (n_575), .Y (n_622));
  NOR2XLM g21294(.A (n_576), .B (n_577), .Y (n_625));
  NOR2BX2M g21295(.AN (reached), .B (direction), .Y (n_627));
  CLKAND2X2M g21296(.A (n_561), .B (state[3]), .Y (n_571));
  NAND2BXLM g21297(.AN (state[2]), .B (n_561), .Y (n_576));
  CLKAND2X2M g21298(.A (direction), .B (reached), .Y (n_620));
  NAND3BXLM g21299(.AN (state[4]), .B (state[0]), .C (state[2]), .Y
       (n_574));
  DFFRQX2M bell_out_reg(.RN (an_reset), .CK (clock), .D (bell), .Q
       (bell_out));
  NOR2XLM g21301(.A (state[4]), .B (state[3]), .Y (n_573));
  CLKAND2X2M g21302(.A (sensor_up), .B (sensor_down), .Y (reached));
  NAND2BXLM g21303(.AN (state[3]), .B (state[1]), .Y (n_575));
  OR2X1M g21304(.A (state[3]), .B (state[1]), .Y (n_577));
  NOR2XLM g21305(.A (state[4]), .B (state[0]), .Y (n_561));
  CLKAND2X2M g21306(.A (state[1]), .B (state[2]), .Y (n_572));
  DFFRQX2M closing_reg(.RN (an_reset), .CK (clock), .D (n_243), .Q
       (closing));
  SDFFRQX2M \counter_reg[0] (.RN (an_reset), .CK (clock), .D (n_480),
       .SI (n_460), .SE (counter[0]), .Q (counter[0]));
  DFFRQX2M \counter_reg[1] (.RN (an_reset), .CK (clock), .D (n_501), .Q
       (counter[1]));
  DFFRQX2M \counter_reg[2] (.RN (an_reset), .CK (clock), .D (n_498), .Q
       (counter[2]));
  DFFRQX2M \counter_reg[3] (.RN (an_reset), .CK (clock), .D (n_500), .Q
       (counter[3]));
  DFFRQX2M \counter_reg[4] (.RN (an_reset), .CK (clock), .D (n_499), .Q
       (counter[4]));
  DFFRQX2M \counter_reg[5] (.RN (an_reset), .CK (clock), .D (n_502), .Q
       (counter[5]));
  DFFRQX2M \counter_reg[6] (.RN (an_reset), .CK (clock), .D (n_497), .Q
       (counter[6]));
  DFFRQX2M \counter_reg[7] (.RN (an_reset), .CK (clock), .D (n_496), .Q
       (counter[7]));
  DFFRQX2M \counter_reg[8] (.RN (an_reset), .CK (clock), .D (n_520), .Q
       (counter[8]));
  DFFRQX2M \counter_reg[9] (.RN (an_reset), .CK (clock), .D (n_535), .Q
       (counter[9]));
  DFFRQX2M \counter_reg[10] (.RN (an_reset), .CK (clock), .D (n_536),
       .Q (counter[10]));
  DFFRQX2M \counter_reg[11] (.RN (an_reset), .CK (clock), .D (n_544),
       .Q (counter[11]));
  DFFRQX2M \counter_reg[12] (.RN (an_reset), .CK (clock), .D (n_551),
       .Q (counter[12]));
  DFFRQX2M \counter_reg[13] (.RN (an_reset), .CK (clock), .D (n_555),
       .Q (counter[13]));
  DFFRQX2M \counter_reg[14] (.RN (an_reset), .CK (clock), .D (n_558),
       .Q (counter[14]));
  DFFRQX2M \counter_reg[15] (.RN (an_reset), .CK (clock), .D (n_559),
       .Q (counter[15]));
  DFFRQX2M \door_reg[0] (.RN (an_reset), .CK (clock), .D (n_315), .Q
       (door[0]));
  DFFRQX2M \door_reg[1] (.RN (an_reset), .CK (clock), .D (n_302), .Q
       (door[1]));
  SDFFRQX2M i_direction_reg(.RN (an_reset), .CK (clock), .D
       (i_direction), .SI (direction), .SE (n_333), .Q (i_direction));
  DFFQX2M \i_engine_reg[0] (.CK (clock), .D (n_545), .Q (i_engine[0]));
  DFFQX2M \i_engine_reg[1] (.CK (clock), .D (n_552), .Q (i_engine[1]));
  DFFRQX2M \inactivate_in_levels_reg[0] (.RN (an_reset), .CK (clock),
       .D (n_55), .Q (inactivate_in_levels[0]));
  DFFRQX2M \inactivate_in_levels_reg[1] (.RN (an_reset), .CK (clock),
       .D (n_478), .Q (inactivate_in_levels[1]));
  DFFRQX2M \inactivate_in_levels_reg[2] (.RN (an_reset), .CK (clock),
       .D (n_438), .Q (inactivate_in_levels[2]));
  DFFRQX2M \inactivate_in_levels_reg[3] (.RN (an_reset), .CK (clock),
       .D (n_344), .Q (inactivate_in_levels[3]));
  DFFRQX2M \inactivate_in_levels_reg[4] (.RN (an_reset), .CK (clock),
       .D (n_422), .Q (inactivate_in_levels[4]));
  DFFRQX2M \inactivate_in_levels_reg[5] (.RN (an_reset), .CK (clock),
       .D (n_388), .Q (inactivate_in_levels[5]));
  DFFRQX2M \inactivate_in_levels_reg[6] (.RN (an_reset), .CK (clock),
       .D (n_434), .Q (inactivate_in_levels[6]));
  DFFRQX2M \inactivate_in_levels_reg[7] (.RN (an_reset), .CK (clock),
       .D (n_54), .Q (inactivate_in_levels[7]));
  DFFRQX2M \inactivate_out_down_levels_reg[1] (.RN (an_reset), .CK
       (clock), .D (n_468), .Q (inactivate_out_down_levels[1]));
  DFFRQX2M \inactivate_out_down_levels_reg[2] (.RN (an_reset), .CK
       (clock), .D (n_399), .Q (inactivate_out_down_levels[2]));
  DFFRQX2M \inactivate_out_down_levels_reg[3] (.RN (an_reset), .CK
       (clock), .D (n_340), .Q (inactivate_out_down_levels[3]));
  DFFRQX2M \inactivate_out_down_levels_reg[4] (.RN (an_reset), .CK
       (clock), .D (n_368), .Q (inactivate_out_down_levels[4]));
  DFFRQX2M \inactivate_out_down_levels_reg[5] (.RN (an_reset), .CK
       (clock), .D (n_244), .Q (inactivate_out_down_levels[5]));
  DFFRQX2M \inactivate_out_down_levels_reg[6] (.RN (an_reset), .CK
       (clock), .D (n_248), .Q (inactivate_out_down_levels[6]));
  DFFRQX2M \inactivate_out_up_levels_reg[1] (.RN (an_reset), .CK
       (clock), .D (n_284), .Q (inactivate_out_up_levels[1]));
  DFFRQX2M \inactivate_out_up_levels_reg[2] (.RN (an_reset), .CK
       (clock), .D (n_261), .Q (inactivate_out_up_levels[2]));
  DFFRQX2M \inactivate_out_up_levels_reg[3] (.RN (an_reset), .CK
       (clock), .D (n_259), .Q (inactivate_out_up_levels[3]));
  DFFRQX2M \inactivate_out_up_levels_reg[4] (.RN (an_reset), .CK
       (clock), .D (n_405), .Q (inactivate_out_up_levels[4]));
  DFFRQX2M \inactivate_out_up_levels_reg[5] (.RN (an_reset), .CK
       (clock), .D (n_365), .Q (inactivate_out_up_levels[5]));
  DFFRQX2M \inactivate_out_up_levels_reg[6] (.RN (an_reset), .CK
       (clock), .D (n_437), .Q (inactivate_out_up_levels[6]));
  DFFQX2M \level_display_reg[0] (.CK (clock), .D (n_383), .Q
       (level_display[0]));
  DFFQX2M \level_display_reg[1] (.CK (clock), .D (n_378), .Q
       (level_display[1]));
  DFFQX2M \level_display_reg[2] (.CK (clock), .D (n_387), .Q
       (level_display[2]));
  DFFQX2M \level_display_reg[3] (.CK (clock), .D (n_355), .Q
       (level_display[3]));
  DFFQX2M \saved_state_reg[0] (.CK (clock), .D (n_541), .Q
       (saved_state[0]));
  DFFQX2M \saved_state_reg[1] (.CK (clock), .D (n_542), .Q
       (saved_state[1]));
  DFFQX2M \saved_state_reg[2] (.CK (clock), .D (n_529), .Q
       (saved_state[2]));
  DFFQX2M \saved_state_reg[3] (.CK (clock), .D (n_508), .Q
       (saved_state[3]));
  DFFSRHQX2M \state_reg[0] (.RN (n_37), .SN (n_21), .CK (clock), .D
       (n_537), .Q (state[0]));
  DFFSRHQX2M \state_reg[1] (.RN (n_40), .SN (n_38), .CK (clock), .D
       (n_543), .Q (state[1]));
  DFFSRHQX2M \state_reg[2] (.RN (n_22), .SN (n_39), .CK (clock), .D
       (n_528), .Q (state[2]));
  DFFSRHQX2M \state_reg[3] (.RN (n_23), .SN (n_24), .CK (clock), .D
       (n_514), .Q (state[3]));
  DFFRQX2M \state_reg[4] (.RN (an_reset), .CK (clock), .D (n_506), .Q
       (state[4]));
  XOR2XLM g40816(.A (n_557), .B (counter[15]), .Y (n_559));
  ADDHX1M g40819(.A (counter[14]), .B (n_554), .S (n_558), .CO (n_557));
  OAI22XLM g40821(.A0 (buttons_block), .A1 (n_553), .B0 (n_402), .B1
       (n_409), .Y (n_556));
  ADDHX1M g40822(.A (counter[13]), .B (n_549), .S (n_555), .CO (n_554));
  NOR4BXLM g40824(.AN (n_374), .B (n_546), .C (n_360), .D (n_359), .Y
       (n_553));
  NAND2X1M g40826(.A (n_550), .B (n_488), .Y (n_552));
  AO22XLM g40827(.A0 (n_480), .A1 (n_548), .B0 (n_460), .B1
       (counter[12]), .Y (n_551));
  AOI32XLM g40829(.A0 (n_476), .A1 (n_99), .A2 (n_4), .B0
       (i_engine[1]), .B1 (n_477), .Y (n_550));
  NOR2BXLM g40830(.AN (n_547), .B (n_460), .Y (n_549));
  ADDHX1M g40831(.A (counter[12]), .B (n_539), .S (n_548), .CO (n_547));
  NAND4XLM g40833(.A (n_538), .B (n_289), .C (n_225), .D (n_185), .Y
       (n_546));
  OAI2B11XLM g40834(.A0 (n_476), .A1N (i_engine[0]), .B0 (n_487), .C0
       (n_4), .Y (n_545));
  AO22XLM g40837(.A0 (n_480), .A1 (n_540), .B0 (n_460), .B1
       (counter[11]), .Y (n_544));
  NAND4BXLMTH g40839(.AN (n_195), .B (n_532), .C (n_165), .D (n_456),
       .Y (n_543));
  NAND4BXLMTH g40842(.AN (n_522), .B (n_531), .C (n_488), .D (n_518),
       .Y (n_542));
  NAND4BXLMTH g40843(.AN (n_505), .B (n_530), .C (n_487), .D (n_494),
       .Y (n_541));
  ADDHX1M g40845(.A (counter[11]), .B (n_523), .S (n_540), .CO (n_539));
  NOR4XLM g40846(.A (n_525), .B (n_362), .C (n_308), .D (n_184), .Y
       (n_538));
  OAI2BB1XLM g40848(.A0N (buttons_block), .A1N (state[0]), .B0 (n_534),
       .Y (n_537));
  AO22XLM g40849(.A0 (n_521), .A1 (counter[10]), .B0 (n_480), .B1
       (n_526), .Y (n_536));
  OAI2BB1XLM g40852(.A0N (counter[9]), .A1N (n_521), .B0 (n_524), .Y
       (n_535));
  AOI2B1XLM g40853(.A0 (saved_state[0]), .A1N (n_472), .B0 (n_527), .Y
       (n_534));
  OAI222XLMTH g40854(.A0 (n_352), .A1 (n_493), .B0 (n_513), .B1
       (direction), .C0 (n_477), .C1 (n_178), .Y (n_533));
  NOR3XLM g40855(.A (n_515), .B (n_386), .C (n_237), .Y (n_532));
  AOI221XLM g40856(.A0 (n_27), .A1 (n_510), .B0 (saved_state[1]), .B1
       (n_482), .C0 (n_484), .Y (n_531));
  AOI211XLM g40857(.A0 (n_482), .A1 (saved_state[0]), .B0 (n_516), .C0
       (n_3), .Y (n_530));
  OAI211XLM g40859(.A0 (n_477), .A1 (n_207), .B0 (n_483), .C0 (n_519),
       .Y (n_529));
  NAND4BXLMTH g40860(.AN (n_299), .B (n_507), .C (n_193), .D (n_456),
       .Y (n_528));
  NOR4BXLM g40861(.AN (n_193), .B (n_504), .C (n_195), .D
       (buttons_block), .Y (n_527));
  MXI2XLMTH g40862(.S0 (counter[10]), .B (counter[9]), .A (n_517), .Y
       (n_526));
  NAND4XLM g40863(.A (n_492), .B (n_311), .C (n_247), .D (n_226), .Y
       (n_525));
  NAND3BXLM g40864(.AN (counter[9]), .B (n_512), .C (n_480), .Y
       (n_524));
  NOR2BXLM g40865(.AN (counter[10]), .B (n_517), .Y (n_523));
  AO22XLM g40867(.A0 (n_480), .A1 (n_509), .B0 (n_460), .B1
       (counter[8]), .Y (n_520));
  AOI22XLM g40868(.A0 (n_510), .A1 (n_232), .B0 (saved_state[2]), .B1
       (n_482), .Y (n_519));
  AOI32XLM g40869(.A0 (n_309), .A1 (n_44), .A2 (n_476), .B0
       (direction), .B1 (n_503), .Y (n_518));
  OAI32XLM g40870(.A0 (n_138), .A1 (direction), .A2 (n_477), .B0
       (n_511), .B1 (n_191), .Y (n_522));
  OAI21BXLM g40871(.A0 (n_479), .A1 (n_512), .B0N (n_460), .Y (n_521));
  AOI2B1XLM g40881(.A0 (n_191), .A1N (n_27), .B0 (n_511), .Y (n_516));
  NAND4XLM g40882(.A (n_474), .B (n_453), .C (n_372), .D (n_208), .Y
       (n_515));
  NAND3XLM g40883(.A (n_382), .B (n_485), .C (n_456), .Y (n_514));
  NOR2XLM g40884(.A (n_503), .B (n_489), .Y (n_513));
  NAND2X1M g40885(.A (n_512), .B (counter[9]), .Y (n_517));
  CLKINVX2M g40889(.A (n_511), .Y (n_510));
  ADDHX1M g40890(.A (counter[8]), .B (n_470), .S (n_509), .CO (n_512));
  OAI2BB1XLM g40891(.A0N (saved_state[3]), .A1N (n_482), .B0 (n_477),
       .Y (n_508));
  AOI21XLM g40892(.A0 (buttons_block), .A1 (state[2]), .B0 (n_486), .Y
       (n_507));
  NAND3BXLM g40893(.AN (n_139), .B (n_114), .C (n_475), .Y (n_506));
  OAI22XLM g40894(.A0 (n_260), .A1 (n_482), .B0 (n_97), .B1 (n_477), .Y
       (n_505));
  NAND4BXLMTH g40895(.AN (n_386), .B (n_449), .C (n_231), .D (n_463),
       .Y (n_504));
  NAND3BXLM g40898(.AN (n_482), .B (letout), .C (n_101), .Y (n_511));
  AO22XLM g40899(.A0 (n_480), .A1 (n_407), .B0 (n_460), .B1
       (counter[5]), .Y (n_502));
  AO22XLM g40900(.A0 (n_480), .A1 (n_119), .B0 (n_460), .B1
       (counter[1]), .Y (n_501));
  AO22XLM g40901(.A0 (n_480), .A1 (n_273), .B0 (n_460), .B1
       (counter[3]), .Y (n_500));
  AO22XLM g40902(.A0 (n_480), .A1 (n_347), .B0 (n_460), .B1
       (counter[4]), .Y (n_499));
  AO22XLM g40903(.A0 (n_480), .A1 (n_211), .B0 (n_460), .B1
       (counter[2]), .Y (n_498));
  AO22XLM g40904(.A0 (n_480), .A1 (n_441), .B0 (n_460), .B1
       (counter[6]), .Y (n_497));
  AO22XLM g40905(.A0 (n_480), .A1 (n_471), .B0 (n_460), .B1
       (counter[7]), .Y (n_496));
  OAI32XLM g40906(.A0 (n_133), .A1 (buttons_block), .A2 (n_461), .B0
       (n_473), .B1 (n_6), .Y (n_495));
  OAI22XLM g40907(.A0 (n_143), .A1 (n_482), .B0 (n_78), .B1 (n_477), .Y
       (n_503));
  NOR4XLM g40909(.A (n_458), .B (n_423), .C (n_288), .D (n_220), .Y
       (n_492));
  OAI31XLM g40910(.A0 (n_455), .A1 (buttons_block), .A2 (n_9), .B0
       (n_464), .Y (n_491));
  OAI31XLM g40911(.A0 (n_455), .A1 (buttons_block), .A2 (n_8), .B0
       (n_465), .Y (n_490));
  OAI21XLM g40912(.A0 (n_623), .A1 (n_345), .B0 (n_476), .Y (n_494));
  NAND2X1M g40914(.A (n_476), .B (n_81), .Y (n_493));
  OAI2B2XLMTH g40916(.A0 (n_472), .A1N (saved_state[2]), .B0
       (buttons_block), .B1 (n_129), .Y (n_486));
  AOI2B1XLM g40917(.A0 (saved_state[3]), .A1N (n_472), .B0 (n_467), .Y
       (n_485));
  AOI31XLM g40918(.A0 (n_124), .A1 (n_16), .A2 (n_634), .B0 (n_482), .Y
       (n_484));
  OAI31XLM g40919(.A0 (n_159), .A1 (n_26), .A2 (n_164), .B0 (n_481), .Y
       (n_483));
  NOR3XLM g40920(.A (n_477), .B (n_179), .C (n_81), .Y (n_489));
  NAND3BXLM g40921(.AN (n_99), .B (n_153), .C (n_476), .Y (n_488));
  OR3X1MTH g40922(.A (n_477), .B (n_153), .C (n_99), .Y (n_487));
  CLKINVX2M g40923(.A (n_482), .Y (n_481));
  CLKINVX2M g40924(.A (n_480), .Y (n_479));
  OAI211XLM g40925(.A0 (n_448), .A1 (n_158), .B0 (n_13), .C0 (n_459),
       .Y (n_478));
  AOI21X1M g40927(.A0 (n_452), .A1 (n_30), .B0 (n_466), .Y (n_482));
  AOI211X4MTH g40928(.A0 (n_369), .A1 (n_133), .B0 (n_460), .C0
       (n_457), .Y (n_480));
  INVX2M g40929(.A (n_477), .Y (n_476));
  NOR4XLM g40930(.A (n_469), .B (n_426), .C (n_354), .D (n_283), .Y
       (n_475));
  AOI221XLM g40931(.A0 (n_107), .A1 (n_276), .B0 (n_13), .B1 (n_197),
       .C0 (n_462), .Y (n_474));
  AOI2B1XLM g40932(.A0 (n_461), .A1N (n_369), .B0 (n_144), .Y (n_473));
  AOI21X2MTH g40933(.A0 (n_450), .A1 (n_30), .B0 (n_466), .Y (n_477));
  ADDHX1M g40934(.A (counter[7]), .B (n_440), .S (n_471), .CO (n_470));
  OAI2B11XLM g40935(.A0 (n_13), .A1N (state[4]), .B0 (n_453), .C0
       (n_444), .Y (n_469));
  OAI211XLM g40936(.A0 (n_443), .A1 (n_158), .B0 (n_13), .C0 (n_451),
       .Y (n_468));
  NAND4BXLMTH g40937(.AN (n_384), .B (n_435), .C (n_286), .D (n_328),
       .Y (n_467));
  NOR2XLM g40938(.A (n_457), .B (n_424), .Y (n_472));
  NAND3XLM g40939(.A (i_engine[1]), .B (n_455), .C (n_48), .Y (n_465));
  NAND3XLM g40940(.A (i_engine[0]), .B (n_455), .C (n_48), .Y (n_464));
  AOI211XLM g40941(.A0 (n_246), .A1 (n_627), .B0 (n_446), .C0 (n_258),
       .Y (n_463));
  OAI2B2XLMTH g40942(.A0 (n_449), .A1N (saved_state[1]), .B0 (n_173),
       .B1 (n_192), .Y (n_462));
  OAI2B1XLM g40943(.A0 (n_376), .A1N (n_30), .B0 (n_454), .Y (n_466));
  NAND2X1M g40944(.A (n_448), .B (inactivate_in_levels[1]), .Y (n_459));
  OAI211XLM g40945(.A0 (n_370), .A1 (n_102), .B0 (n_408), .C0 (n_439),
       .Y (n_458));
  NOR2XLM g40946(.A (n_450), .B (n_429), .Y (n_461));
  CLKAND2X2M g40947(.A (n_445), .B (n_409), .Y (n_460));
  OAI31XLM g40948(.A0 (n_432), .A1 (n_305), .A2 (n_429), .B0 (n_30), .Y
       (n_454));
  OAI21XLM g40949(.A0 (n_402), .A1 (n_442), .B0 (n_393), .Y (n_457));
  AOI221XLM g40950(.A0 (n_569), .A1 (n_278), .B0 (n_570), .B1 (n_390),
       .C0 (n_447), .Y (n_456));
  NAND4XLM g40951(.A (n_433), .B (n_404), .C (n_385), .D (n_310), .Y
       (n_455));
  NAND4BXLMTH g40952(.AN (n_366), .B (n_430), .C (n_287), .D (n_395),
       .Y (n_452));
  NAND2X1M g40953(.A (n_443), .B (inactivate_out_down_levels[1]), .Y
       (n_451));
  NAND2BXLM g40955(.AN (n_442), .B (n_402), .Y (n_453));
  OAI2BB2XLMTH g40958(.A0N (n_149), .A1N (n_371), .B0 (n_428), .B1
       (n_126), .Y (n_447));
  NAND4XLM g40959(.A (n_421), .B (n_379), .C (n_165), .D (n_200), .Y
       (n_446));
  AOI221XLM g40960(.A0 (n_171), .A1 (n_419), .B0 (n_13), .B1 (n_75),
       .C0 (n_189), .Y (n_445));
  AOI211XLM g40961(.A0 (n_277), .A1 (n_569), .B0 (n_431), .C0 (n_304),
       .Y (n_444));
  NAND3BXLM g40962(.AN (n_359), .B (n_408), .C (n_430), .Y (n_450));
  AND3XLM g40963(.A (n_442), .B (n_425), .C (n_393), .Y (n_449));
  AOI221XLM g40964(.A0 (reached), .A1 (n_418), .B0 (n_41), .B1 (n_172),
       .C0 (n_166), .Y (n_448));
  ADDHX1M g40965(.A (counter[6]), .B (n_406), .S (n_441), .CO (n_440));
  NOR3XLM g40966(.A (n_423), .B (n_166), .C (n_137), .Y (n_443));
  OAI31XLM g40968(.A0 (n_401), .A1 (n_303), .A2 (n_351), .B0 (n_104),
       .Y (n_442));
  NAND3BXLM g40970(.AN (n_402), .B (n_104), .C (n_419), .Y (n_439));
  OAI211XLM g40971(.A0 (n_404), .A1 (n_10), .B0 (n_94), .C0 (n_13), .Y
       (n_438));
  OAI211XLM g40972(.A0 (n_411), .A1 (n_129), .B0 (n_13), .C0 (n_420),
       .Y (n_437));
  AOI222XLM g40974(.A0 (n_415), .A1 (n_13), .B0 (n_285), .B1 (n_107),
       .C0 (n_77), .C1 (n_331), .Y (n_435));
  OAI211XLM g40975(.A0 (n_385), .A1 (n_10), .B0 (n_187), .C0 (n_13), .Y
       (n_434));
  NOR4XLM g40976(.A (n_418), .B (n_380), .C (n_339), .D (n_0), .Y
       (n_433));
  OR3X1MTH g40977(.A (n_403), .B (n_396), .C (n_327), .Y (n_432));
  OAI221XLM g40978(.A0 (n_392), .A1 (n_109), .B0 (n_186), .B1 (letout),
       .C0 (n_414), .Y (n_431));
  AOI211XLM g40980(.A0 (n_257), .A1 (n_132), .B0 (n_397), .C0 (n_330),
       .Y (n_428));
  OAI2B2XLMTH g40981(.A0 (n_633), .A1N (n_158), .B0 (n_5), .B1 (n_333),
       .Y (n_427));
  OAI22XLM g40982(.A0 (n_181), .A1 (n_410), .B0 (letout), .B1 (n_183),
       .Y (n_426));
  AOI31XLM g40983(.A0 (n_104), .A1 (n_98), .A2 (n_306), .B0 (n_416), .Y
       (n_430));
  OR2X1M g40984(.A (n_413), .B (n_360), .Y (n_429));
  CLKINVX2M g40985(.A (n_424), .Y (n_425));
  OAI211XLM g40986(.A0 (n_361), .A1 (n_138), .B0 (n_13), .C0 (n_389),
       .Y (n_422));
  NOR2XLM g40987(.A (n_400), .B (n_197), .Y (n_421));
  NAND2X1M g40988(.A (n_411), .B (inactivate_out_up_levels[6]), .Y
       (n_420));
  NOR2BXLM g40990(.AN (n_410), .B (n_181), .Y (n_424));
  NOR2XLM g40991(.A (n_2), .B (n_10), .Y (n_423));
  AOI211XLM g40994(.A0 (n_370), .A1 (n_105), .B0 (n_392), .C0 (n_102),
       .Y (n_416));
  AO21XLM g40995(.A0 (n_167), .A1 (n_627), .B0 (n_403), .Y (n_415));
  AOI221XLM g40996(.A0 (n_132), .A1 (n_292), .B0 (n_570), .B1 (n_391),
       .C0 (n_1), .Y (n_414));
  OAI2B1XLM g40997(.A0 (n_381), .A1N (n_104), .B0 (n_311), .Y (n_413));
  OAI22XLM g40998(.A0 (n_622), .A1 (n_377), .B0 (n_80), .B1 (n_363), .Y
       (n_412));
  OAI222XLMTH g40999(.A0 (n_102), .A1 (n_357), .B0 (n_265), .B1 (n_25),
       .C0 (n_245), .C1 (n_100), .Y (n_419));
  OAI21XLM g41000(.A0 (n_14), .A1 (n_134), .B0 (n_2), .Y (n_418));
  ADDHX1M g41001(.A (counter[5]), .B (n_346), .S (n_407), .CO (n_406));
  OAI211XLM g41002(.A0 (n_349), .A1 (n_138), .B0 (n_13), .C0 (n_367),
       .Y (n_405));
  AOI211XLM g41003(.A0 (n_117), .A1 (n_620), .B0 (n_362), .C0 (n_160),
       .Y (n_411));
  NAND2BXLM g41007(.AN (n_33), .B (n_394), .Y (n_410));
  NAND2X1M g41008(.A (n_375), .B (n_171), .Y (n_409));
  NAND2BXLM g41009(.AN (n_395), .B (letout), .Y (n_408));
  OAI22XLM g41012(.A0 (n_109), .A1 (n_357), .B0 (n_141), .B1 (n_307),
       .Y (n_401));
  AOI2B1XLM g41013(.A0 (n_372), .A1N (n_299), .B0 (n_620), .Y (n_400));
  NAND3XLM g41014(.A (n_176), .B (n_374), .C (n_13), .Y (n_399));
  OAI222XLMTH g41016(.A0 (n_141), .A1 (n_296), .B0 (n_350), .B1
       (n_109), .C0 (n_256), .C1 (n_106), .Y (n_397));
  OAI33XLM g41017(.A0 (n_334), .A1 (n_121), .A2 (n_45), .B0 (n_194),
       .B1 (n_42), .B2 (n_76), .Y (n_396));
  AOI33XLM g41018(.A0 (direction), .A1 (n_334), .A2 (n_120), .B0
       (n_77), .B1 (n_14), .B2 (n_194), .Y (n_404));
  AND4XLM g41020(.A (n_337), .B (n_624), .C (n_63), .D (n_620), .Y
       (n_403));
  NAND3BXLM g41021(.AN (counter[10]), .B (counter[7]), .C (n_364), .Y
       (n_402));
  CLKINVX2M g41022(.A (n_390), .Y (n_391));
  NAND2X1M g41023(.A (n_361), .B (inactivate_in_levels[4]), .Y (n_389));
  NAND2X1M g41024(.A (n_356), .B (n_13), .Y (n_388));
  OAI211XLM g41025(.A0 (n_317), .A1 (n_206), .B0 (n_342), .C0 (n_373),
       .Y (n_387));
  NAND2X1M g41026(.A (n_358), .B (n_625), .Y (n_395));
  NAND2X1M g41028(.A (n_369), .B (n_6), .Y (n_394));
  NAND2BXLM g41029(.AN (n_371), .B (n_149), .Y (n_393));
  NOR2BXLM g41030(.AN (n_370), .B (n_357), .Y (n_392));
  NOR2XLM g41031(.A (n_358), .B (n_5), .Y (n_390));
  AOI21XLM g41034(.A0 (reached), .A1 (n_336), .B0 (n_34), .Y (n_384));
  OAI2B11XLM g41035(.A0 (n_316), .A1N (level_display[0]), .B0 (n_32),
       .C0 (n_326), .Y (n_383));
  AOI2B1XLM g41036(.A0 (n_195), .A1N (n_334), .B0 (n_188), .Y (n_382));
  AOI221XLM g41037(.A0 (n_101), .A1 (n_245), .B0 (n_26), .B1 (n_265),
       .C0 (n_353), .Y (n_381));
  OAI2BB2XLMTH g41038(.A0N (n_45), .A1N (n_624), .B0 (n_338), .B1
       (n_14), .Y (n_380));
  NOR4XLM g41039(.A (n_341), .B (n_222), .C (n_563), .D (n_564), .Y
       (n_379));
  OAI2B11XLM g41040(.A0 (n_316), .A1N (level_display[1]), .B0 (n_325),
       .C0 (n_373), .Y (n_378));
  OAI22XLM g41041(.A0 (n_80), .A1 (n_332), .B0 (n_14), .B1 (n_223), .Y
       (n_377));
  AOI22XLM g41042(.A0 (n_329), .A1 (n_79), .B0 (n_623), .B1 (n_335), .Y
       (n_376));
  OAI222XLMTH g41043(.A0 (n_43), .A1 (n_307), .B0 (n_306), .B1 (n_99),
       .C0 (n_266), .C1 (n_124), .Y (n_375));
  NOR3XLM g41044(.A (n_369), .B (n_181), .C (n_33), .Y (n_386));
  AOI32XLM g41045(.A0 (n_113), .A1 (direction), .A2 (n_79), .B0 (n_14),
       .B1 (n_343), .Y (n_385));
  OAI211XLM g41046(.A0 (n_291), .A1 (n_138), .B0 (n_13), .C0 (n_314),
       .Y (n_368));
  NAND2X1M g41047(.A (n_349), .B (inactivate_out_up_levels[4]), .Y
       (n_367));
  NAND2X1M g41048(.A (n_348), .B (n_632), .Y (n_366));
  NAND3BXLM g41049(.AN (n_308), .B (n_13), .C (n_205), .Y (n_365));
  NOR4BXLM g41050(.AN (counter[2]), .B (n_294), .C (counter[12]), .D
       (counter[9]), .Y (n_364));
  NAND4BXLMTH g41051(.AN (n_45), .B (n_290), .C
       (active_out_down_levels[2]), .D (n_120), .Y (n_374));
  NOR2BXLM g41052(.AN (n_32), .B (n_324), .Y (n_373));
  NAND2BXLM g41053(.AN (n_34), .B (n_336), .Y (n_372));
  NAND3BXLM g41054(.AN (counter[10]), .B (counter[7]), .C (n_313), .Y
       (n_371));
  NAND2BXLM g41057(.AN (n_126), .B (n_350), .Y (n_370));
  NOR4BX1M g41058(.AN (counter[10]), .B (n_294), .C (n_90), .D
       (counter[7]), .Y (n_369));
  AOI222XLM g41060(.A0 (n_298), .A1 (n_41), .B0 (n_85), .B1
       (inactivate_in_levels[5]), .C0 (n_180), .C1 (n_163), .Y (n_356));
  OAI2BB1XLM g41061(.A0N (level_display[3]), .A1N (n_317), .B0 (n_32),
       .Y (n_355));
  AOI2BB1XLM g41062(.A0N (n_322), .A1N (n_306), .B0 (n_131), .Y
       (n_354));
  AO22XLM g41063(.A0 (n_266), .A1 (n_125), .B0 (n_307), .B1 (n_44), .Y
       (n_353));
  AOI222XLM g41064(.A0 (n_319), .A1 (n_103), .B0 (n_233), .B1 (n_125),
       .C0 (n_26), .C1 (n_127), .Y (n_352));
  OAI22XLM g41065(.A0 (n_106), .A1 (n_265), .B0 (n_131), .B1 (n_306),
       .Y (n_351));
  AOI222XLM g41066(.A0 (n_234), .A1 (n_125), .B0 (n_128), .B1 (n_26),
       .C0 (n_103), .C1 (n_318), .Y (n_363));
  NOR3BXLM g41067(.AN (n_87), .B (n_320), .C (n_42), .Y (n_362));
  AOI2BB1XLM g41068(.A0N (n_310), .A1N (n_10), .B0 (n_159), .Y (n_361));
  OAI22XLM g41069(.A0 (n_124), .A1 (n_281), .B0 (n_43), .B1 (n_323), .Y
       (n_360));
  OAI21XLM g41070(.A0 (n_5), .A1 (n_632), .B0 (n_348), .Y (n_359));
  NAND3BXLM g41071(.AN (active_out_up_levels[0]), .B (n_74), .C
       (n_319), .Y (n_358));
  AOI22XLM g41072(.A0 (n_319), .A1 (direction), .B0 (n_14), .B1 (n_47),
       .Y (n_357));
  ADDHX1M g41073(.A (counter[4]), .B (n_272), .S (n_347), .CO (n_346));
  NOR2XLM g41074(.A (n_309), .B (n_43), .Y (n_345));
  NAND2X1M g41075(.A (n_312), .B (n_13), .Y (n_344));
  NAND2X1M g41076(.A (n_320), .B (n_135), .Y (n_343));
  NAND2X1M g41077(.A (n_317), .B (level_display[2]), .Y (n_342));
  NOR2XLM g41078(.A (n_321), .B (n_111), .Y (n_341));
  NAND3XLM g41079(.A (n_202), .B (n_289), .C (n_13), .Y (n_340));
  AOI2B1XLM g41080(.A0 (n_242), .A1N (n_298), .B0 (direction), .Y
       (n_339));
  AOI221XLM g41081(.A0 (n_77), .A1 (n_264), .B0 (n_96), .B1 (n_180),
       .C0 (n_623), .Y (n_338));
  NAND2X1M g41084(.A (n_319), .B (n_47), .Y (n_350));
  AOI211XLM g41085(.A0 (n_156), .A1 (n_620), .B0 (n_288), .C0 (n_159),
       .Y (n_349));
  NAND2X1M g41086(.A (n_322), .B (n_98), .Y (n_348));
  CLKINVX2M g41088(.A (n_336), .Y (n_335));
  CLKAND2X2M g41089(.A (n_300), .B (n_179), .Y (n_332));
  OAI211XLM g41090(.A0 (n_264), .A1 (n_15), .B0 (reached), .C0 (n_219),
       .Y (n_331));
  OAI22XLM g41091(.A0 (n_130), .A1 (n_238), .B0 (n_131), .B1 (n_295),
       .Y (n_330));
  OAI21XLM g41092(.A0 (n_45), .A1 (n_113), .B0 (n_321), .Y (n_329));
  AOI2BB2XLM g41093(.A0N (n_297), .A1N (n_111), .B0 (n_239), .B1
       (n_145), .Y (n_328));
  AO21XLM g41094(.A0 (n_246), .A1 (n_41), .B0 (n_301), .Y (n_327));
  OAI31XLM g41095(.A0 (n_221), .A1 (n_79), .A2 (n_120), .B0 (n_316), .Y
       (n_326));
  OAI31XLM g41096(.A0 (n_146), .A1 (n_44), .A2 (n_125), .B0 (n_316), .Y
       (n_325));
  AOI2BB1XLM g41097(.A0N (n_164), .A1N (n_623), .B0 (n_317), .Y
       (n_324));
  NAND3BXLM g41098(.AN (active_out_up_levels[1]), .B
       (active_out_down_levels[1]), .C (n_319), .Y (n_337));
  NAND3XLM g41099(.A (n_627), .B (n_293), .C (n_87), .Y (n_336));
  OAI31XLM g41100(.A0 (n_274), .A1 (n_20), .A2
       (active_out_up_levels[2]), .B0 (n_69), .Y (n_334));
  AOI21XLM g41101(.A0 (n_228), .A1 (n_287), .B0 (buttons_block), .Y
       (n_333));
  INVX2M g41103(.A (n_318), .Y (n_319));
  INVX2M g41104(.A (n_317), .Y (n_316));
  AOI21XLM g41105(.A0 (n_200), .A1 (n_271), .B0 (buttons_block), .Y
       (n_315));
  NAND2X1M g41106(.A (n_291), .B (inactivate_out_down_levels[4]), .Y
       (n_314));
  NOR4XLM g41107(.A (n_241), .B (counter[4]), .C (counter[6]), .D
       (counter[5]), .Y (n_313));
  AOI222XLM g41108(.A0 (n_148), .A1 (n_213), .B0 (n_162), .B1
       (inactivate_in_levels[3]), .C0 (n_112), .C1 (n_264), .Y (n_312));
  NAND2BXLM g41110(.AN (n_126), .B (n_296), .Y (n_323));
  NOR2BXLM g41111(.AN (n_295), .B (n_126), .Y (n_322));
  NAND2BXLM g41112(.AN (n_297), .B (reached), .Y (n_321));
  NAND2BXLM g41113(.AN (n_293), .B (n_623), .Y (n_320));
  NAND2X1M g41114(.A (n_290), .B (n_20), .Y (n_318));
  NAND2X1M g41115(.A (n_282), .B (an_reset), .Y (n_317));
  OAI2B2XLMTH g41116(.A0 (n_264), .A1N (n_112), .B0 (n_152), .B1
       (n_235), .Y (n_305));
  AOI2B1XLM g41117(.A0 (n_268), .A1N (n_265), .B0 (n_106), .Y (n_304));
  OAI2B2XLMTH g41118(.A0 (n_266), .A1N (n_132), .B0 (n_130), .B1
       (n_245), .Y (n_303));
  OAI32XLM g41119(.A0 (n_192), .A1 (n_35), .A2 (n_249), .B0 (n_270),
       .B1 (buttons_block), .Y (n_302));
  AO2B2X1M g41120(.A0 (n_163), .A1N (n_180), .B0 (n_276), .B1 (n_96),
       .Y (n_301));
  AOI222XLM g41121(.A0 (n_190), .A1 (n_101), .B0 (n_98), .B1 (n_28),
       .C0 (n_44), .C1 (n_275), .Y (n_300));
  AOI22XLM g41122(.A0 (n_253), .A1 (n_101), .B0 (n_26), .B1 (n_269), .Y
       (n_311));
  AOI33XLM g41123(.A0 (n_14), .A1 (n_250), .A2 (n_96), .B0 (n_122), .B1
       (direction), .B2 (n_235), .Y (n_310));
  AOI2BB1XLM g41124(.A0N (n_274), .A1N (n_80), .B0 (n_27), .Y (n_309));
  NOR4BXLM g41125(.AN (n_65), .B (n_255), .C (n_78), .D (n_42), .Y
       (n_308));
  MX2X1M g41126(.S0 (direction), .B (n_274), .A (n_110), .Y (n_307));
  AOI2BB2XLM g41127(.A0N (n_267), .A1N (direction), .B0 (n_28), .B1
       (direction), .Y (n_306));
  NAND2BXLM g41128(.AN (n_266), .B (n_281), .Y (n_292));
  NOR2BXLM g41130(.AN (n_107), .B (n_276), .Y (n_299));
  CLKAND2X2M g41131(.A (n_279), .B (n_79), .Y (n_298));
  NAND2BXLM g41132(.AN (n_279), .B (n_14), .Y (n_297));
  NAND2BXLM g41134(.AN (n_110), .B (n_275), .Y (n_296));
  NAND2BXLM g41135(.AN (n_267), .B (n_28), .Y (n_295));
  NAND4XLM g41136(.A (n_230), .B (counter[6]), .C (counter[5]), .D
       (counter[4]), .Y (n_294));
  NAND2BXLM g41137(.AN (n_267), .B (active_out_up_levels[6]), .Y
       (n_293));
  AOI221XLM g41138(.A0 (n_10), .A1 (n_155), .B0 (buttons_block), .B1
       (state[3]), .C0 (n_262), .Y (n_286));
  OAI21BXLM g41139(.A0 (n_180), .A1 (n_15), .B0N (n_276), .Y (n_285));
  OAI211XLM g41140(.A0 (n_218), .A1 (n_158), .B0 (n_13), .C0 (n_240),
       .Y (n_284));
  AOI2BB1XLM g41141(.A0N (n_253), .A1N (n_245), .B0 (n_130), .Y
       (n_283));
  NAND4BXLMTH g41142(.AN (n_164), .B (n_228), .C (n_182), .D (n_179),
       .Y (n_282));
  NOR2XLM g41143(.A (n_263), .B (n_159), .Y (n_291));
  NOR3XLM g41144(.A (n_274), .B (active_out_up_levels[2]), .C
       (active_in_levels[2]), .Y (n_290));
  NAND3BXLM g41145(.AN (n_254), .B (active_out_down_levels[3]), .C
       (n_112), .Y (n_289));
  NOR4BXLM g41146(.AN (n_66), .B (n_236), .C (n_97), .D (n_42), .Y
       (n_288));
  NOR4BXLM g41147(.AN (n_634), .B (n_227), .C (n_159), .D (n_590), .Y
       (n_287));
  CLKINVX2M g41148(.A (n_277), .Y (n_278));
  INVX2M g41149(.A (n_275), .Y (n_274));
  ADDHX1M g41150(.A (counter[3]), .B (n_210), .S (n_273), .CO (n_272));
  NAND2X1M g41151(.A (n_249), .B (door[0]), .Y (n_271));
  NAND2X1M g41152(.A (n_249), .B (door[1]), .Y (n_270));
  OR2X1M g41154(.A (n_257), .B (n_126), .Y (n_281));
  NAND2X1M g41157(.A (n_255), .B (n_65), .Y (n_279));
  NAND2X1M g41158(.A (n_251), .B (letout), .Y (n_277));
  NOR2XLM g41160(.A (n_250), .B (n_42), .Y (n_276));
  NOR2XLM g41161(.A (n_254), .B (active_out_down_levels[3]), .Y
       (n_275));
  CLKINVX2M g41162(.A (n_268), .Y (n_269));
  OAI31XLM g41163(.A0 (n_97), .A1 (n_11), .A2 (n_66), .B0 (n_247), .Y
       (n_263));
  OAI22XLM g41164(.A0 (n_193), .A1 (n_235), .B0 (n_113), .B1 (n_165),
       .Y (n_262));
  NAND3XLM g41165(.A (n_225), .B (n_13), .C (n_201), .Y (n_261));
  NOR3XLM g41166(.A (n_227), .B (n_77), .C (n_624), .Y (n_260));
  NAND3XLM g41167(.A (n_204), .B (n_13), .C (n_226), .Y (n_259));
  AOI2BB1XLM g41168(.A0N (n_237), .A1N (n_624), .B0 (n_620), .Y
       (n_258));
  NAND2BXLM g41169(.AN (n_126), .B (n_256), .Y (n_268));
  NAND3BXLM g41170(.AN (active_out_down_levels[5]), .B (n_52), .C
       (n_224), .Y (n_267));
  AOI22XLM g41171(.A0 (n_233), .A1 (direction), .B0 (n_14), .B1
       (n_140), .Y (n_266));
  AOI22XLM g41172(.A0 (n_224), .A1 (n_14), .B0 (direction), .B1
       (n_127), .Y (n_265));
  OAI31X1M g41173(.A0 (n_234), .A1 (n_18), .A2
       (active_out_up_levels[3]), .B0 (n_72), .Y (n_264));
  NAND3XLM g41175(.A (n_185), .B (n_203), .C (n_13), .Y (n_248));
  CLKAND2X2M g41176(.A (n_233), .B (n_140), .Y (n_257));
  NAND2X1M g41177(.A (n_224), .B (n_127), .Y (n_256));
  NAND2X1M g41178(.A (n_224), .B (active_out_up_levels[5]), .Y (n_255));
  NAND2X1M g41179(.A (n_233), .B (n_51), .Y (n_254));
  NOR2BXLM g41180(.AN (n_238), .B (n_126), .Y (n_253));
  NOR2XLM g41181(.A (n_234), .B (n_212), .Y (n_251));
  NAND2X1M g41182(.A (n_236), .B (n_66), .Y (n_250));
  AOI211XLM g41183(.A0 (n_139), .A1 (n_175), .B0 (n_150), .C0 (n_151),
       .Y (n_249));
  NAND3BXLM g41184(.AN (n_220), .B (n_177), .C (n_13), .Y (n_244));
  OAI2B1XLM g41185(.A0 (n_192), .A1N (n_173), .B0 (n_229), .Y (n_243));
  AOI21XLM g41186(.A0 (n_122), .A1 (n_213), .B0 (n_172), .Y (n_242));
  NAND3BXLM g41187(.AN (n_90), .B (counter[3]), .C (n_217), .Y (n_241));
  AOI2BB2XLM g41188(.A0N (n_134), .A1N (n_15), .B0 (n_218), .B1
       (inactivate_out_up_levels[1]), .Y (n_240));
  OAI21XLM g41189(.A0 (n_11), .A1 (n_213), .B0 (reached), .Y (n_239));
  NAND3BXLM g41190(.AN (n_152), .B (active_out_down_levels[4]), .C
       (n_216), .Y (n_247));
  OAI21BXLM g41191(.A0 (n_213), .A1 (n_123), .B0N (n_167), .Y (n_246));
  AOI2BB2XLM g41192(.A0N (n_212), .A1N (direction), .B0 (n_190), .B1
       (direction), .Y (n_245));
  INVX2M g41193(.A (n_234), .Y (n_233));
  OAI21XLM g41194(.A0 (n_80), .A1 (n_190), .B0 (n_36), .Y (n_232));
  AOI22XLM g41195(.A0 (n_139), .A1 (n_157), .B0 (state[4]), .B1
       (n_174), .Y (n_231));
  NOR2BXLM g41196(.AN (n_217), .B (counter[3]), .Y (n_230));
  OAI21XLM g41197(.A0 (waiting), .A1 (n_192), .B0 (closing), .Y
       (n_229));
  NAND2BXLM g41198(.AN (n_212), .B (n_190), .Y (n_238));
  CLKAND2X2M g41199(.A (n_219), .B (n_77), .Y (n_237));
  NAND2BXLM g41200(.AN (n_212), .B (active_out_up_levels[4]), .Y
       (n_236));
  OAI31XLM g41201(.A0 (n_191), .A1 (active_out_up_levels[4]), .A2
       (n_17), .B0 (n_68), .Y (n_235));
  NAND2BXLM g41202(.AN (active_out_down_levels[4]), .B (n_216), .Y
       (n_234));
  AOI2BB2XLM g41203(.A0N (n_81), .A1N (n_625), .B0 (n_182), .B1 (n_99),
       .Y (n_223));
  AOI21XLM g41204(.A0 (n_183), .A1 (n_186), .B0 (letout), .Y (n_222));
  NAND3XLM g41206(.A (n_16), .B (n_179), .C (n_123), .Y (n_221));
  NOR3BXLM g41207(.AN (n_158), .B (n_198), .C (n_77), .Y (n_228));
  OAI21BXLM g41208(.A0 (n_179), .A1 (letout), .B0N (n_589), .Y (n_227));
  NAND3BXLM g41209(.AN (n_196), .B (n_59), .C (n_148), .Y (n_226));
  NAND4XLM g41210(.A (n_169), .B (n_77), .C (n_61), .D (n_41), .Y
       (n_225));
  NOR4X1MTH g41211(.A (n_212), .B (active_out_up_levels[4]), .C
       (active_out_down_levels[4]), .D (active_in_levels[4]), .Y
       (n_224));
  ADDHX1M g41212(.A (counter[2]), .B (n_118), .S (n_211), .CO (n_210));
  AND3XLM g41213(.A (n_163), .B (n_170), .C
       (active_out_down_levels[5]), .Y (n_220));
  NAND2BXLM g41214(.AN (n_194), .B (n_627), .Y (n_219));
  NOR2XLM g41215(.A (n_166), .B (n_184), .Y (n_218));
  NOR4BXLM g41216(.AN (counter[8]), .B (n_95), .C (counter[11]), .D
       (counter[1]), .Y (n_217));
  NOR3XLM g41217(.A (n_191), .B (active_out_up_levels[4]), .C
       (active_in_levels[4]), .Y (n_216));
  NAND2X1M g41220(.A (n_196), .B (n_59), .Y (n_213));
  NAND3XLM g41221(.A (n_18), .B (n_140), .C (n_51), .Y (n_212));
  AOI22XLM g41222(.A0 (n_145), .A1 (n_15), .B0 (buttons_block), .B1
       (state[1]), .Y (n_208));
  OA21X1M g41223(.A0 (n_138), .A1 (n_14), .B0 (n_129), .Y (n_207));
  NOR4XLM g41224(.A (n_101), .B (n_96), .C (n_79), .D (n_26), .Y
       (n_206));
  AOI32XLM g41225(.A0 (n_71), .A1 (n_620), .A2 (n_96), .B0
       (inactivate_out_up_levels[5]), .B1 (n_85), .Y (n_205));
  AOI32XLM g41226(.A0 (n_73), .A1 (n_620), .A2 (n_77), .B0
       (inactivate_out_up_levels[3]), .B1 (n_162), .Y (n_204));
  AOI2BB2XLM g41227(.A0N (n_135), .A1N (n_11), .B0 (n_161), .B1
       (inactivate_out_down_levels[6]), .Y (n_203));
  AOI22XLM g41228(.A0 (n_148), .A1 (n_58), .B0
       (inactivate_out_down_levels[3]), .B1 (n_162), .Y (n_202));
  AOI2BB2XLM g41229(.A0N (n_168), .A1N (n_69), .B0 (n_83), .B1
       (inactivate_out_up_levels[2]), .Y (n_201));
  INVX2M g41232(.A (n_191), .Y (n_190));
  NOR2XLM g41233(.A (n_144), .B (n_33), .Y (n_189));
  NOR2BXLM g41234(.AN (n_48), .B (n_158), .Y (n_188));
  NAND2X1M g41235(.A (n_161), .B (inactivate_in_levels[6]), .Y (n_187));
  NAND2X1M g41236(.A (n_151), .B (n_53), .Y (n_200));
  NAND2X1M g41238(.A (n_138), .B (n_129), .Y (n_198));
  NOR2BXLM g41239(.AN (n_150), .B (closing), .Y (n_197));
  NAND2X1M g41240(.A (n_140), .B (active_out_up_levels[3]), .Y (n_196));
  NOR2XLM g41241(.A (n_168), .B (buttons_block), .Y (n_195));
  NAND2BXLM g41242(.AN (n_169), .B (n_61), .Y (n_194));
  NAND2X1M g41243(.A (n_145), .B (n_620), .Y (n_193));
  NAND2X1M g41244(.A (n_139), .B (n_13), .Y (n_192));
  NAND2BXLM g41245(.AN (active_out_down_levels[5]), .B (n_170), .Y
       (n_191));
  AOI21XLM g41246(.A0 (n_27), .A1 (n_101), .B0 (n_622), .Y (n_178));
  AOI32XLM g41247(.A0 (n_64), .A1 (n_627), .A2 (n_79), .B0
       (inactivate_out_down_levels[5]), .B1 (n_85), .Y (n_177));
  AOI32XLM g41248(.A0 (n_60), .A1 (n_627), .A2 (n_77), .B0
       (inactivate_out_down_levels[2]), .B1 (n_83), .Y (n_176));
  AO21XLM g41249(.A0 (n_6), .A1 (n_115), .B0 (n_116), .Y (n_175));
  OR4X1MTH g41250(.A (n_92), .B (n_46), .C (n_572), .D (state[3]), .Y
       (n_174));
  NOR3BXLM g41251(.AN (n_141), .B (n_132), .C (n_108), .Y (n_186));
  NAND4BXLMTH g41252(.AN (n_45), .B (n_79), .C
       (active_out_down_levels[6]), .D (n_93), .Y (n_185));
  NOR4BXLM g41253(.AN (n_62), .B (n_121), .C (n_91), .D (n_42), .Y
       (n_184));
  AND3XLM g41254(.A (n_130), .B (n_131), .C (n_106), .Y (n_183));
  NOR3XLM g41255(.A (n_101), .B (n_44), .C (n_625), .Y (n_182));
  NAND4BXLMTH g41256(.AN (state[3]), .B (n_88), .C (n_13), .D
       (state[1]), .Y (n_181));
  OAI31X1M g41257(.A0 (n_128), .A1 (n_19), .A2
       (active_out_up_levels[5]), .B0 (n_70), .Y (n_180));
  NOR3X1MTH g41258(.A (n_125), .B (n_103), .C (n_26), .Y (n_179));
  INVX2M g41259(.A (n_161), .Y (n_160));
  NAND2BXLM g41260(.AN (n_35), .B (n_116), .Y (n_157));
  NOR2XLM g41261(.A (n_123), .B (n_68), .Y (n_156));
  NOR2XLM g41262(.A (waiting), .B (n_115), .Y (n_173));
  CLKAND2X2M g41263(.A (n_120), .B (n_136), .Y (n_172));
  NOR2XLM g41264(.A (n_105), .B (buttons_block), .Y (n_171));
  CLKAND2X2M g41265(.A (n_127), .B (n_52), .Y (n_170));
  NOR2BXLM g41266(.AN (active_out_up_levels[2]), .B (n_110), .Y
       (n_169));
  NAND2X1M g41267(.A (n_120), .B (n_620), .Y (n_168));
  NOR2XLM g41268(.A (n_121), .B (n_136), .Y (n_167));
  NOR2XLM g41269(.A (n_102), .B (letout), .Y (n_166));
  NAND2BXLM g41270(.AN (n_111), .B (n_620), .Y (n_165));
  NAND2X1M g41271(.A (n_99), .B (n_16), .Y (n_164));
  NOR2XLM g41272(.A (n_97), .B (n_45), .Y (n_163));
  NAND2X1M g41273(.A (n_125), .B (n_5), .Y (n_162));
  NAND2X1M g41274(.A (n_98), .B (n_5), .Y (n_161));
  NOR2XLM g41275(.A (n_100), .B (letout), .Y (n_159));
  NOR2XLM g41276(.A (n_120), .B (n_624), .Y (n_158));
  CLKINVX2M g41277(.A (n_154), .Y (n_155));
  NOR3XLM g41279(.A (n_121), .B (n_62), .C (n_11), .Y (n_137));
  NOR2BXLM g41280(.AN (n_111), .B (n_107), .Y (n_154));
  AOI21XLM g41281(.A0 (n_28), .A1 (n_81), .B0 (n_27), .Y (n_153));
  NAND2BXLM g41282(.AN (n_45), .B (n_122), .Y (n_152));
  AOI21XLM g41283(.A0 (close_btn), .A1 (n_7), .B0 (n_114), .Y (n_151));
  NOR2XLM g41284(.A (n_114), .B (n_53), .Y (n_150));
  NOR3XLM g41285(.A (n_56), .B (state[4]), .C (buttons_block), .Y
       (n_149));
  NOR2XLM g41286(.A (n_123), .B (n_42), .Y (n_148));
  NAND2X1M g41287(.A (n_123), .B (n_76), .Y (n_146));
  NOR2XLM g41288(.A (n_123), .B (buttons_block), .Y (n_145));
  NAND2X1M g41289(.A (n_133), .B (n_13), .Y (n_144));
  NOR2XLM g41290(.A (n_120), .B (n_77), .Y (n_143));
  NAND3BXLM g41292(.AN (state[2]), .B (state[1]), .C (n_89), .Y
       (n_141));
  NOR4X1MTH g41293(.A (n_110), .B (active_out_up_levels[2]), .C
       (active_out_down_levels[2]), .D (active_in_levels[2]), .Y
       (n_140));
  NOR4BX1MTH g41294(.AN (state[4]), .B (n_29), .C (state[1]), .D
       (state[3]), .Y (n_139));
  NOR2XLM g41295(.A (n_122), .B (n_96), .Y (n_138));
  INVX2M g41296(.A (n_128), .Y (n_127));
  INVX2M g41297(.A (n_125), .Y (n_124));
  INVX2M g41298(.A (n_123), .Y (n_122));
  INVX2M g41299(.A (n_121), .Y (n_120));
  ADDHX1M g41300(.A (counter[1]), .B (counter[0]), .S (n_119), .CO
       (n_118));
  NOR2XLM g41301(.A (n_78), .B (n_67), .Y (n_117));
  NAND2X1M g41303(.A (n_62), .B (n_91), .Y (n_136));
  NAND2BXLM g41304(.AN (n_87), .B (n_623), .Y (n_135));
  NAND2BXLM g41305(.AN (n_63), .B (n_624), .Y (n_134));
  NOR2BXLM g41307(.AN (n_88), .B (n_575), .Y (n_133));
  NOR2BXLM g41308(.AN (n_92), .B (n_31), .Y (n_132));
  NAND2X1M g41309(.A (n_89), .B (n_572), .Y (n_131));
  NAND2X1M g41310(.A (n_89), .B (n_46), .Y (n_130));
  NOR2XLM g41311(.A (n_79), .B (n_623), .Y (n_129));
  NAND2BXLM g41312(.AN (active_out_down_levels[6]), .B (n_93), .Y
       (n_128));
  NAND2X1M g41313(.A (n_81), .B (letout), .Y (n_126));
  NOR2BX1M g41314(.AN (n_84), .B (n_575), .Y (n_125));
  NAND2BXLM g41315(.AN (n_49), .B (n_84), .Y (n_123));
  NAND2X1M g41316(.A (n_84), .B (n_50), .Y (n_121));
  CLKINVX2M g41317(.A (n_109), .Y (n_108));
  INVX2M g41318(.A (n_105), .Y (n_104));
  INVX2M g41319(.A (n_103), .Y (n_102));
  CLKINVX2M g41320(.A (n_101), .Y (n_100));
  INVX2M g41321(.A (n_99), .Y (n_98));
  INVX2M g41322(.A (n_97), .Y (n_96));
  OR4X1MTH g41323(.A (counter[0]), .B (counter[15]), .C (counter[13]),
       .D (counter[14]), .Y (n_95));
  NAND2X1M g41324(.A (n_83), .B (inactivate_in_levels[2]), .Y (n_94));
  NOR4XLM g41325(.A (waiting), .B (overload), .C (open_btn), .D
       (sensor_inside), .Y (n_116));
  NOR3BXLM g41326(.AN (n_35), .B (overload), .C (sensor_inside), .Y
       (n_115));
  NAND2BXLM g41327(.AN (n_577), .B (n_88), .Y (n_114));
  NAND2X1M g41328(.A (n_57), .B (n_67), .Y (n_113));
  NOR2XLM g41329(.A (n_76), .B (n_45), .Y (n_112));
  NAND2X1M g41330(.A (n_79), .B (n_13), .Y (n_111));
  NAND2X1M g41331(.A (n_74), .B (n_47), .Y (n_110));
  OR3X1MTH g41332(.A (n_29), .B (n_31), .C (state[1]), .Y (n_109));
  AND3XLM g41333(.A (n_46), .B (n_571), .C (n_13), .Y (n_107));
  NAND3BXLM g41334(.AN (n_31), .B (state[0]), .C (n_46), .Y (n_106));
  NAND2X1M g41335(.A (n_80), .B (letout), .Y (n_105));
  NOR2BXLM g41336(.AN (n_84), .B (n_577), .Y (n_103));
  NOR2BX1MTH g41337(.AN (n_86), .B (n_577), .Y (n_101));
  NAND2BXLM g41338(.AN (n_575), .B (n_86), .Y (n_99));
  NAND2X1M g41339(.A (n_86), .B (n_50), .Y (n_97));
  INVX2M g41341(.A (n_81), .Y (n_80));
  INVX2M g41342(.A (n_79), .Y (n_78));
  INVX2M g41343(.A (n_77), .Y (n_76));
  NOR2XLM g41344(.A (n_49), .B (n_574), .Y (n_75));
  NOR3BXLM g41345(.AN (n_28), .B (active_out_up_levels[6]), .C
       (active_in_levels[6]), .Y (n_93));
  NOR2BXLM g41346(.AN (state[1]), .B (n_29), .Y (n_92));
  NAND2X1M g41347(.A (n_47), .B (active_out_up_levels[1]), .Y (n_91));
  NAND3BXLM g41348(.AN (counter[2]), .B (counter[9]), .C (counter[12]),
       .Y (n_90));
  NOR2XLM g41349(.A (n_31), .B (state[0]), .Y (n_89));
  NOR3BXLM g41350(.AN (state[4]), .B (state[0]), .C (state[2]), .Y
       (n_88));
  AOI2B1XLM g41351(.A0 (active_out_down_levels[6]), .A1N (overload),
       .B0 (active_in_levels[6]), .Y (n_87));
  NOR3BXLM g41352(.AN (state[2]), .B (state[0]), .C (state[4]), .Y
       (n_86));
  NAND2X1M g41353(.A (n_26), .B (n_5), .Y (n_85));
  NOR2XLM g41354(.A (n_29), .B (state[4]), .Y (n_84));
  NAND2X1M g41355(.A (n_44), .B (n_5), .Y (n_83));
  NOR2BXLM g41356(.AN (n_36), .B (n_27), .Y (n_81));
  NOR2BX1M g41357(.AN (n_50), .B (n_574), .Y (n_79));
  NOR2X1M g41358(.A (n_49), .B (n_576), .Y (n_77));
  CLKINVX2M g41359(.A (n_72), .Y (n_73));
  CLKINVX2M g41360(.A (n_70), .Y (n_71));
  CLKINVX2M g41361(.A (n_65), .Y (n_64));
  CLKINVX2M g41362(.A (n_61), .Y (n_60));
  CLKINVX2M g41363(.A (n_59), .Y (n_58));
  NAND3BXLM g41364(.AN (active_out_up_levels[6]), .B
       (active_out_down_levels[6]), .C (n_28), .Y (n_57));
  NAND3XLM g41365(.A (state[0]), .B (n_572), .C (state[3]), .Y (n_56));
  AO21XLM g41366(.A0 (n_567), .A1 (inactivate_in_levels[0]), .B0
       (n_565), .Y (n_55));
  AO21XLM g41367(.A0 (n_568), .A1 (inactivate_in_levels[7]), .B0
       (n_566), .Y (n_54));
  NOR3XLM g41368(.A (active_out_up_levels[1]), .B
       (active_out_down_levels[1]), .C (active_in_levels[1]), .Y
       (n_74));
  AOI2B1XLM g41369(.A0 (active_out_up_levels[3]), .A1N (overload), .B0
       (active_in_levels[3]), .Y (n_72));
  AOI2B1XLM g41370(.A0 (active_out_up_levels[5]), .A1N (overload), .B0
       (active_in_levels[5]), .Y (n_70));
  AOI2B1XLM g41371(.A0 (active_out_up_levels[2]), .A1N (overload), .B0
       (active_in_levels[2]), .Y (n_69));
  AOI2B1XLM g41372(.A0 (active_out_up_levels[4]), .A1N (overload), .B0
       (active_in_levels[4]), .Y (n_68));
  AOI2B1XLM g41373(.A0 (active_out_up_levels[6]), .A1N (overload), .B0
       (active_in_levels[6]), .Y (n_67));
  AOI2BB1XLM g41374(.A0N (n_17), .A1N (overload), .B0
       (active_in_levels[4]), .Y (n_66));
  AOI2BB1XLM g41375(.A0N (n_19), .A1N (overload), .B0
       (active_in_levels[5]), .Y (n_65));
  AOI2B1XLM g41376(.A0 (active_out_up_levels[1]), .A1N (overload), .B0
       (active_in_levels[1]), .Y (n_63));
  AOI2B1XLM g41377(.A0 (active_out_down_levels[1]), .A1N (overload),
       .B0 (active_in_levels[1]), .Y (n_62));
  AOI2BB1XLM g41378(.A0N (n_20), .A1N (overload), .B0
       (active_in_levels[2]), .Y (n_61));
  AOI2BB1XLM g41379(.A0N (n_18), .A1N (overload), .B0
       (active_in_levels[3]), .Y (n_59));
  INVX2M g41380(.A (n_44), .Y (n_43));
  INVX2M g41381(.A (n_42), .Y (n_41));
  OR2X1M g41382(.A (saved_state[1]), .B (an_reset), .Y (n_40));
  NAND2XLM g41383(.A (saved_state[2]), .B (n_12), .Y (n_39));
  NAND2XLM g41384(.A (saved_state[1]), .B (n_12), .Y (n_38));
  OR2X1M g41385(.A (saved_state[0]), .B (an_reset), .Y (n_37));
  NAND2BXLM g41386(.AN (sensor_door[1]), .B (sensor_door[0]), .Y
       (n_53));
  NOR2XLM g41387(.A (active_out_up_levels[5]), .B
       (active_in_levels[5]), .Y (n_52));
  NOR2XLM g41388(.A (active_out_up_levels[3]), .B
       (active_in_levels[3]), .Y (n_51));
  NOR2BXLM g41389(.AN (state[3]), .B (state[1]), .Y (n_50));
  NAND2X1M g41390(.A (state[1]), .B (state[3]), .Y (n_49));
  NOR2XLM g41391(.A (reached), .B (buttons_block), .Y (n_48));
  NOR2XLM g41392(.A (active_out_up_levels[0]), .B
       (active_in_levels[0]), .Y (n_47));
  NOR2BXLM g41393(.AN (state[2]), .B (state[1]), .Y (n_46));
  NAND2X1M g41394(.A (direction), .B (reached), .Y (n_45));
  NOR2X1M g41395(.A (n_576), .B (n_575), .Y (n_44));
  NAND2X1M g41396(.A (n_14), .B (reached), .Y (n_42));
  CLKINVX2M g41397(.A (n_26), .Y (n_25));
  NAND2XLM g41398(.A (saved_state[3]), .B (n_12), .Y (n_24));
  NAND2BXLMTH g41399(.AN (saved_state[3]), .B (n_12), .Y (n_23));
  NAND2BXLMTH g41400(.AN (saved_state[2]), .B (n_12), .Y (n_22));
  NAND2XLM g41401(.A (saved_state[0]), .B (n_12), .Y (n_21));
  NAND2X1M g41402(.A (direction), .B (i_direction), .Y (n_36));
  NOR2BXLM g41403(.AN (sensor_door[1]), .B (sensor_door[0]), .Y (n_35));
  NAND2X1M g41404(.A (n_623), .B (n_13), .Y (n_34));
  NOR2XLM g41405(.A (waiting), .B (opening), .Y (n_33));
  NAND2X1M g41406(.A (an_reset), .B (buttons_block), .Y (n_32));
  NAND2X1M g41407(.A (n_573), .B (n_13), .Y (n_31));
  NOR2XLM g41408(.A (n_12), .B (buttons_block), .Y (n_30));
  NAND2BXLM g41409(.AN (state[2]), .B (state[0]), .Y (n_29));
  NOR2XLM g41410(.A (active_out_down_levels[7]), .B
       (active_in_levels[7]), .Y (n_28));
  NOR2XLM g41411(.A (direction), .B (i_direction), .Y (n_27));
  NOR2X1M g41412(.A (n_574), .B (n_577), .Y (n_26));
  INVX2M g41414(.A (active_out_down_levels[2]), .Y (n_20));
  INVX2M g41415(.A (active_out_down_levels[5]), .Y (n_19));
  INVX2M g41416(.A (active_out_down_levels[3]), .Y (n_18));
  CLKINVX2M g41417(.A (active_out_down_levels[4]), .Y (n_17));
  INVX2M g41418(.A (n_622), .Y (n_16));
  INVX2M g41419(.A (n_620), .Y (n_15));
  INVX2M g41420(.A (direction), .Y (n_14));
  INVX2M g41421(.A (buttons_block), .Y (n_13));
  INVX2M g41422(.A (an_reset), .Y (n_12));
  INVX2M g41426(.A (n_627), .Y (n_11));
  INVX2M g41427(.A (reached), .Y (n_10));
  DFFRX1M \engine_reg[0] (.RN (an_reset), .CK (clock), .D (n_491), .Q
       (engine[0]), .QN (n_9));
  DFFRX1M \engine_reg[1] (.RN (an_reset), .CK (clock), .D (n_490), .Q
       (engine[1]), .QN (n_8));
  DFFRX1M letout_reg(.RN (an_reset), .CK (clock), .D (n_427), .Q
       (letout), .QN (n_5));
  DFFRX1M opening_reg(.RN (an_reset), .CK (clock), .D (n_630), .Q
       (opening), .QN (n_7));
  DFFRX1M waiting_reg(.RN (an_reset), .CK (clock), .D (n_495), .Q
       (waiting), .QN (n_6));
  NOR3BX2M g2(.AN (n_494), .B (n_533), .C (n_522), .Y (n_4));
  OAI2B2X1M g41439(.A0 (n_14), .A1N (n_489), .B0 (n_363), .B1 (n_493),
       .Y (n_3));
  NAND4BX1M g41440(.AN (n_337), .B (n_624), .C (n_63), .D (direction),
       .Y (n_2));
  AOI2B1X1M g41441(.A0 (n_323), .A1N (n_307), .B0 (n_141), .Y (n_1));
  AOI2B1X1M g41442(.A0 (n_143), .A1N (n_198), .B0 (reached), .Y (n_0));
  INVXLM g41449(.A (n_589), .Y (n_568));
  INVXLM g41450(.A (n_590), .Y (n_567));
  OAI22X1M g41451(.A0 (buttons_block), .A1 (n_287), .B0 (n_631), .B1
       (n_7), .Y (n_630));
  NOR2X2M g41452(.A (n_394), .B (n_144), .Y (n_631));
  NAND2BX2M g41453(.AN (n_251), .B (n_622), .Y (n_632));
  NAND4BX1M g41454(.AN (n_146), .B (n_333), .C (n_154), .D (n_34), .Y
       (n_633));
  NOR2BX2M g41455(.AN (n_83), .B (n_160), .Y (n_634));
  SDFFRQX2M direction_reg(.RN (an_reset), .CK (clock), .D (direction),
       .SI (n_412), .SE (n_556), .Q (direction));
endmodule

