###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID lab513-pc1)
#  Generated on:      Sun Jun 30 23:51:20 2019
#  Design:            elevator
#  Command:           saveDesign elevator
###############################################################
current_design elevator
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clock}]  -name clk -period 100000.000000 -waveform {0.000000 50000.000000}
set_clock_transition  -rise -min 0.9 [get_clocks {clk}]
set_clock_transition  -rise -max 0.9 [get_clocks {clk}]
set_clock_transition  -fall -min 0.9 [get_clocks {clk}]
set_clock_transition  -fall -max 0.9 [get_clocks {clk}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[2]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[3]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {sensor_inside}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[1]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[6]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {open_btn}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[4]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {sensor_up}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {bell}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[2]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {sensor_door[1]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {sensor_down}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {overload}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[0]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[7]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[5]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[6]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[3]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[4]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[1]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[2]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[7]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[0]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[5]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {buttons_block}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[3]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_in[1]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {sensor_door[0]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {close_btn}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[6]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_down_out[4]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {btn_up_out[5]}]
set_input_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {an_reset}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {level_display[1]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {engine[1]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {door[0]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {level_display[2]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {level_display[0]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {direction}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {bell_out}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {engine[0]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {door[1]}]
set_output_delay -add_delay 200 -clock [get_clocks {clk}] [get_ports {level_display[3]}]
