/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID lab513-pc1)
#  Generated on:      Wed Jun 26 17:39:14 2019
#  Design:            elevator
#  Command:           saveNetlist elevator.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.12-s027_1
// Generated on: Jun 25 2019 23:06:02 CEST (Jun 25 2019 21:06:02 UTC)
// Verification Directory fv/elevator 
module buttons_res (
	clk, 
	an_reset, 
	buttons_block, 
	btn_in, 
	btn_up_out, 
	btn_down_out, 
	inactivate_in_levels, 
	inactivate_out_up_levels, 
	inactivate_out_down_levels, 
	active_in_levels, 
	active_out_up_levels, 
	active_out_down_levels, 
	p1, 
	p2, 
	FE_OFN0_an_reset);
   input clk;
   input an_reset;
   input buttons_block;
   input [7:0] btn_in;
   input [6:0] btn_up_out;
   input [7:1] btn_down_out;
   input [7:0] inactivate_in_levels;
   input [6:0] inactivate_out_up_levels;
   input [7:1] inactivate_out_down_levels;
   output [7:0] active_in_levels;
   output [6:0] active_out_up_levels;
   output [7:1] active_out_down_levels;
   input p1;
   input p2;
   input FE_OFN0_an_reset;

   // Internal wires
   wire [7:0] l_btn_in;
   wire [7:0] l_inactivate_in_levels;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_140;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;

   TLATX2M \active_out_up_levels_reg[0]  (.D(n_70),
	.G(n_72),
	.Q(active_out_up_levels[0]),
	.QN(UNCONNECTED));
   TLATX2M \active_out_down_levels_reg[7]  (.D(n_69),
	.G(n_73),
	.Q(active_out_down_levels[7]),
	.QN(UNCONNECTED0));
   OAI2B11XLM g2939 (.A0(btn_down_out[7]),
	.A1N(inactivate_out_down_levels[7]),
	.B0(FE_OFN0_an_reset),
	.C0(n_71),
	.Y(n_73));
   OAI2B11XLM g2940 (.A0(btn_up_out[0]),
	.A1N(inactivate_out_up_levels[0]),
	.B0(FE_OFN0_an_reset),
	.C0(n_68),
	.Y(n_72));
   NAND3BX2M g2941 (.AN(buttons_block),
	.B(btn_in[0]),
	.C(l_btn_in[0]),
	.Y(n_140));
   DFFRQX2M \l_btn_in_reg[1]  (.D(btn_in[1]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_btn_in[1]));
   DFFRQX2M \l_btn_in_reg[2]  (.D(btn_in[2]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_btn_in[2]));
   DFFRQX2M \l_btn_in_reg[3]  (.D(btn_in[3]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_btn_in[3]));
   DFFRQX2M \l_btn_in_reg[4]  (.D(btn_in[4]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_btn_in[4]));
   DFFRQX2M \l_btn_in_reg[5]  (.D(btn_in[5]),
	.CK(clk),
	.RN(an_reset),
	.Q(l_btn_in[5]));
   DFFRQX2M \l_btn_in_reg[6]  (.D(btn_in[6]),
	.CK(clk),
	.RN(an_reset),
	.Q(l_btn_in[6]));
   DFFRQX2M \l_btn_in_reg[7]  (.D(btn_in[7]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_btn_in[7]));
   DFFRQX2M \l_inactivate_in_levels_reg[0]  (.D(inactivate_out_up_levels[0]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_inactivate_in_levels[0]));
   DFFRQX2M \l_inactivate_in_levels_reg[1]  (.D(inactivate_in_levels[1]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_inactivate_in_levels[1]));
   DFFRQX2M \l_inactivate_in_levels_reg[5]  (.D(inactivate_in_levels[5]),
	.CK(clk),
	.RN(an_reset),
	.Q(l_inactivate_in_levels[5]));
   DFFRQX2M \l_inactivate_in_levels_reg[2]  (.D(inactivate_in_levels[2]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_inactivate_in_levels[2]));
   DFFRQX2M \l_inactivate_in_levels_reg[3]  (.D(inactivate_in_levels[3]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_inactivate_in_levels[3]));
   DFFRQX2M \l_inactivate_in_levels_reg[4]  (.D(inactivate_in_levels[4]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_inactivate_in_levels[4]));
   DFFRX1MTH \l_btn_in_reg[0]  (.D(btn_in[0]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(UNCONNECTED1),
	.QN(l_btn_in[0]));
   DFFRQX2M \l_inactivate_in_levels_reg[6]  (.D(inactivate_in_levels[6]),
	.CK(clk),
	.RN(an_reset),
	.Q(l_inactivate_in_levels[6]));
   DFFRQX2M \l_inactivate_in_levels_reg[7]  (.D(inactivate_out_down_levels[7]),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(l_inactivate_in_levels[7]));
   NAND2BXLM g2958 (.AN(buttons_block),
	.B(btn_down_out[7]),
	.Y(n_71));
   CLKAND2X2M g2959 (.A(FE_OFN0_an_reset),
	.B(btn_up_out[0]),
	.Y(n_70));
   CLKAND2X2M g2960 (.A(FE_OFN0_an_reset),
	.B(btn_down_out[7]),
	.Y(n_69));
   NAND2BXLM g2961 (.AN(buttons_block),
	.B(btn_up_out[0]),
	.Y(n_68));
   DFFRQX2M \active_in_levels_reg[0]  (.D(n_60),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(active_in_levels[0]));
   DFFRQX2M \active_in_levels_reg[1]  (.D(n_64),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(active_in_levels[1]));
   DFFRQX2M \active_in_levels_reg[2]  (.D(n_62),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(active_in_levels[2]));
   DFFRQX2M \active_in_levels_reg[3]  (.D(n_63),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(active_in_levels[3]));
   DFFRQX2M \active_in_levels_reg[4]  (.D(n_61),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(active_in_levels[4]));
   DFFRQX2M \active_in_levels_reg[5]  (.D(n_66),
	.CK(clk),
	.RN(an_reset),
	.Q(active_in_levels[5]));
   DFFRQX2M \active_in_levels_reg[6]  (.D(n_67),
	.CK(clk),
	.RN(an_reset),
	.Q(active_in_levels[6]));
   DFFRQX2M \active_in_levels_reg[7]  (.D(n_65),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(active_in_levels[7]));
   TLATX2M \active_out_down_levels_reg[1]  (.D(n_11),
	.G(n_52),
	.Q(active_out_down_levels[1]),
	.QN(UNCONNECTED2));
   TLATX2M \active_out_down_levels_reg[2]  (.D(n_9),
	.G(n_51),
	.Q(active_out_down_levels[2]),
	.QN(UNCONNECTED3));
   TLATX2M \active_out_down_levels_reg[3]  (.D(n_12),
	.G(n_50),
	.Q(active_out_down_levels[3]),
	.QN(UNCONNECTED4));
   TLATX2M \active_out_down_levels_reg[4]  (.D(n_2),
	.G(n_49),
	.Q(active_out_down_levels[4]),
	.QN(UNCONNECTED5));
   TLATX2M \active_out_down_levels_reg[5]  (.D(n_8),
	.G(n_48),
	.Q(active_out_down_levels[5]),
	.QN(UNCONNECTED6));
   TLATX2M \active_out_down_levels_reg[6]  (.D(n_7),
	.G(n_47),
	.Q(active_out_down_levels[6]),
	.QN(UNCONNECTED7));
   TLATX2M \active_out_up_levels_reg[1]  (.D(n_6),
	.G(n_46),
	.Q(active_out_up_levels[1]),
	.QN(UNCONNECTED8));
   TLATX2M \active_out_up_levels_reg[2]  (.D(n_5),
	.G(n_45),
	.Q(active_out_up_levels[2]),
	.QN(UNCONNECTED9));
   TLATX2M \active_out_up_levels_reg[3]  (.D(n_10),
	.G(n_44),
	.Q(active_out_up_levels[3]),
	.QN(UNCONNECTED10));
   TLATX2M \active_out_up_levels_reg[4]  (.D(n_3),
	.G(n_43),
	.Q(active_out_up_levels[4]),
	.QN(UNCONNECTED11));
   TLATX2M \active_out_up_levels_reg[5]  (.D(n_1),
	.G(n_42),
	.Q(active_out_up_levels[5]),
	.QN(UNCONNECTED12));
   TLATX2M \active_out_up_levels_reg[6]  (.D(n_4),
	.G(n_41),
	.Q(active_out_up_levels[6]),
	.QN(UNCONNECTED13));
   OAI21X2M g3797 (.A0(n_147),
	.A1(inactivate_in_levels[6]),
	.B0(n_30),
	.Y(n_67));
   OAI21X2M g3798 (.A0(n_145),
	.A1(inactivate_in_levels[5]),
	.B0(n_32),
	.Y(n_66));
   OAI21X2M g3799 (.A0(n_149),
	.A1(inactivate_out_down_levels[7]),
	.B0(n_28),
	.Y(n_65));
   OAI21X2M g3800 (.A0(n_151),
	.A1(inactivate_in_levels[1]),
	.B0(n_31),
	.Y(n_64));
   OAI21X2M g3801 (.A0(n_155),
	.A1(inactivate_in_levels[3]),
	.B0(n_34),
	.Y(n_63));
   OAI21X2M g3802 (.A0(n_153),
	.A1(inactivate_in_levels[2]),
	.B0(n_29),
	.Y(n_62));
   OAI21X2M g3803 (.A0(n_143),
	.A1(inactivate_in_levels[4]),
	.B0(n_33),
	.Y(n_61));
   OAI21X2M g3817 (.A0(n_24),
	.A1(inactivate_out_up_levels[0]),
	.B0(n_27),
	.Y(n_60));
   NAND2X1M g3825 (.A(n_21),
	.B(FE_OFN0_an_reset),
	.Y(n_52));
   NAND2X1M g3826 (.A(n_20),
	.B(FE_OFN0_an_reset),
	.Y(n_51));
   NAND2X1M g3827 (.A(n_19),
	.B(FE_OFN0_an_reset),
	.Y(n_50));
   NAND2X1M g3828 (.A(n_18),
	.B(FE_OFN0_an_reset),
	.Y(n_49));
   NAND2X1M g3829 (.A(n_17),
	.B(an_reset),
	.Y(n_48));
   NAND2X1M g3830 (.A(n_16),
	.B(FE_OFN0_an_reset),
	.Y(n_47));
   NAND2X1M g3831 (.A(n_15),
	.B(FE_OFN0_an_reset),
	.Y(n_46));
   NAND2X1M g3832 (.A(n_14),
	.B(FE_OFN0_an_reset),
	.Y(n_45));
   NAND2X1M g3833 (.A(n_13),
	.B(FE_OFN0_an_reset),
	.Y(n_44));
   NAND2X1M g3834 (.A(n_23),
	.B(FE_OFN0_an_reset),
	.Y(n_43));
   NAND2X1M g3835 (.A(n_25),
	.B(an_reset),
	.Y(n_42));
   NAND2X1M g3836 (.A(n_22),
	.B(an_reset),
	.Y(n_41));
   NAND3X2M g3837 (.A(active_in_levels[3]),
	.B(inactivate_in_levels[3]),
	.C(l_inactivate_in_levels[3]),
	.Y(n_34));
   NAND3X2M g3838 (.A(active_in_levels[4]),
	.B(inactivate_in_levels[4]),
	.C(l_inactivate_in_levels[4]),
	.Y(n_33));
   NAND3X2M g3839 (.A(active_in_levels[5]),
	.B(inactivate_in_levels[5]),
	.C(l_inactivate_in_levels[5]),
	.Y(n_32));
   NAND3X2M g3840 (.A(active_in_levels[1]),
	.B(inactivate_in_levels[1]),
	.C(l_inactivate_in_levels[1]),
	.Y(n_31));
   NAND3X2M g3841 (.A(active_in_levels[6]),
	.B(inactivate_in_levels[6]),
	.C(l_inactivate_in_levels[6]),
	.Y(n_30));
   NAND3X2M g3842 (.A(active_in_levels[2]),
	.B(inactivate_in_levels[2]),
	.C(l_inactivate_in_levels[2]),
	.Y(n_29));
   NAND3X2M g3843 (.A(active_in_levels[7]),
	.B(inactivate_out_down_levels[7]),
	.C(l_inactivate_in_levels[7]),
	.Y(n_28));
   NAND3X2M g3844 (.A(active_in_levels[0]),
	.B(inactivate_out_up_levels[0]),
	.C(l_inactivate_in_levels[0]),
	.Y(n_27));
   MXI2XLMTH g3851 (.S0(btn_up_out[5]),
	.B(p1),
	.A(inactivate_out_up_levels[5]),
	.Y(n_25));
   AOI2BB2XLM g3852 (.A0N(n_140),
	.A1N(active_in_levels[0]),
	.B0(n_140),
	.B1(active_in_levels[0]),
	.Y(n_24));
   MXI2XLMTH g3853 (.S0(btn_up_out[4]),
	.B(p1),
	.A(inactivate_out_up_levels[4]),
	.Y(n_23));
   MXI2XLMTH g3854 (.S0(btn_up_out[6]),
	.B(p1),
	.A(inactivate_out_up_levels[6]),
	.Y(n_22));
   MXI2XLMTH g3855 (.S0(btn_down_out[1]),
	.B(p1),
	.A(inactivate_out_down_levels[1]),
	.Y(n_21));
   MXI2XLMTH g3856 (.S0(btn_down_out[2]),
	.B(p1),
	.A(inactivate_out_down_levels[2]),
	.Y(n_20));
   MXI2XLMTH g3857 (.S0(btn_down_out[3]),
	.B(p1),
	.A(inactivate_out_down_levels[3]),
	.Y(n_19));
   MXI2XLMTH g3858 (.S0(btn_down_out[4]),
	.B(p1),
	.A(inactivate_out_down_levels[4]),
	.Y(n_18));
   MXI2XLMTH g3859 (.S0(btn_down_out[5]),
	.B(p1),
	.A(inactivate_out_down_levels[5]),
	.Y(n_17));
   MXI2XLMTH g3860 (.S0(btn_down_out[6]),
	.B(p1),
	.A(inactivate_out_down_levels[6]),
	.Y(n_16));
   MXI2XLMTH g3861 (.S0(btn_up_out[1]),
	.B(p1),
	.A(inactivate_out_up_levels[1]),
	.Y(n_15));
   MXI2XLMTH g3862 (.S0(btn_up_out[2]),
	.B(p1),
	.A(inactivate_out_up_levels[2]),
	.Y(n_14));
   MXI2XLMTH g3863 (.S0(btn_up_out[3]),
	.B(p1),
	.A(inactivate_out_up_levels[3]),
	.Y(n_13));
   NOR2BXLM g3865 (.AN(btn_down_out[3]),
	.B(p2),
	.Y(n_12));
   NOR2BXLM g3866 (.AN(btn_down_out[1]),
	.B(p2),
	.Y(n_11));
   NOR2BXLM g3867 (.AN(btn_up_out[3]),
	.B(p2),
	.Y(n_10));
   NOR2BXLM g3868 (.AN(btn_down_out[2]),
	.B(p2),
	.Y(n_9));
   NOR2BXLM g3869 (.AN(btn_down_out[5]),
	.B(p2),
	.Y(n_8));
   NOR2BXLM g3870 (.AN(btn_down_out[6]),
	.B(p2),
	.Y(n_7));
   NOR2BXLM g3871 (.AN(btn_up_out[1]),
	.B(p2),
	.Y(n_6));
   NOR2BXLM g3872 (.AN(btn_up_out[2]),
	.B(p2),
	.Y(n_5));
   NOR2BXLM g3873 (.AN(btn_up_out[6]),
	.B(p2),
	.Y(n_4));
   NOR2BXLM g3874 (.AN(btn_up_out[4]),
	.B(p2),
	.Y(n_3));
   NOR2BXLM g3875 (.AN(btn_down_out[4]),
	.B(p2),
	.Y(n_2));
   NOR2BXLM g3876 (.AN(btn_up_out[5]),
	.B(p2),
	.Y(n_1));
   XNOR2X2M g2 (.A(n_142),
	.B(active_in_levels[4]),
	.Y(n_143));
   NOR3BX2M g3 (.AN(btn_in[4]),
	.B(buttons_block),
	.C(l_btn_in[4]),
	.Y(n_142));
   XNOR2X2M g3878 (.A(n_144),
	.B(active_in_levels[5]),
	.Y(n_145));
   NOR3BX2M g3879 (.AN(btn_in[5]),
	.B(buttons_block),
	.C(l_btn_in[5]),
	.Y(n_144));
   XNOR2X2M g3880 (.A(n_146),
	.B(active_in_levels[6]),
	.Y(n_147));
   NOR3BX2M g3881 (.AN(btn_in[6]),
	.B(buttons_block),
	.C(l_btn_in[6]),
	.Y(n_146));
   XNOR2X2M g3882 (.A(n_148),
	.B(active_in_levels[7]),
	.Y(n_149));
   NOR3BX2M g3883 (.AN(btn_in[7]),
	.B(buttons_block),
	.C(l_btn_in[7]),
	.Y(n_148));
   XNOR2X2M g3884 (.A(n_150),
	.B(active_in_levels[1]),
	.Y(n_151));
   NOR3BX2M g3885 (.AN(btn_in[1]),
	.B(buttons_block),
	.C(l_btn_in[1]),
	.Y(n_150));
   XNOR2X2M g3886 (.A(n_152),
	.B(active_in_levels[2]),
	.Y(n_153));
   NOR3BX2M g3887 (.AN(btn_in[2]),
	.B(buttons_block),
	.C(l_btn_in[2]),
	.Y(n_152));
   XNOR2X2M g3888 (.A(n_154),
	.B(active_in_levels[3]),
	.Y(n_155));
   NOR3BX2M g3889 (.AN(btn_in[3]),
	.B(buttons_block),
	.C(l_btn_in[3]),
	.Y(n_154));
endmodule

module elevator (
	clk, 
	an_reset, 
	buttons_block, 
	open_btn, 
	close_btn, 
	overload, 
	bell, 
	sensor_up, 
	sensor_down, 
	sensor_inside, 
	sensor_door, 
	btn_in, 
	btn_up_out, 
	btn_down_out, 
	engine, 
	door, 
	direction, 
	bell_out, 
	level_display);
   input clk;
   input an_reset;
   input buttons_block;
   input open_btn;
   input close_btn;
   input overload;
   input bell;
   input sensor_up;
   input sensor_down;
   input sensor_inside;
   input [1:0] sensor_door;
   input [7:0] btn_in;
   input [6:0] btn_up_out;
   input [7:1] btn_down_out;
   output [1:0] engine;
   output [1:0] door;
   output direction;
   output bell_out;
   output [3:0] level_display;

   // Internal wires
   wire FE_OFN0_an_reset;
   wire FE_DBTN1_an_reset;
   wire FE_DBTN0_buttons_block;
   wire [7:0] inactivate_in_levels;
   wire [6:0] inactivate_out_up_levels;
   wire [7:1] inactivate_out_down_levels;
   wire [7:0] active_in_levels;
   wire [6:0] active_out_up_levels;
   wire [7:1] active_out_down_levels;
   wire [4:0] state;
   wire [15:0] counter;
   wire [1:0] i_engine;
   wire [4:0] saved_state;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;
   wire closing;
   wire i_direction;
   wire letout;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_212;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_275;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_281;
   wire n_282;
   wire n_283;
   wire n_284;
   wire n_285;
   wire n_286;
   wire n_287;
   wire n_288;
   wire n_289;
   wire n_290;
   wire n_291;
   wire n_292;
   wire n_293;
   wire n_294;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;
   wire n_299;
   wire n_300;
   wire n_301;
   wire n_302;
   wire n_303;
   wire n_304;
   wire n_305;
   wire n_306;
   wire n_307;
   wire n_308;
   wire n_309;
   wire n_310;
   wire n_311;
   wire n_312;
   wire n_313;
   wire n_314;
   wire n_315;
   wire n_316;
   wire n_317;
   wire n_318;
   wire n_319;
   wire n_320;
   wire n_321;
   wire n_322;
   wire n_323;
   wire n_324;
   wire n_325;
   wire n_326;
   wire n_327;
   wire n_328;
   wire n_329;
   wire n_330;
   wire n_331;
   wire n_332;
   wire n_333;
   wire n_334;
   wire n_335;
   wire n_336;
   wire n_337;
   wire n_338;
   wire n_339;
   wire n_340;
   wire n_341;
   wire n_342;
   wire n_343;
   wire n_344;
   wire n_345;
   wire n_346;
   wire n_347;
   wire n_348;
   wire n_349;
   wire n_350;
   wire n_351;
   wire n_352;
   wire n_353;
   wire n_354;
   wire n_355;
   wire n_356;
   wire n_357;
   wire n_358;
   wire n_359;
   wire n_360;
   wire n_361;
   wire n_362;
   wire n_363;
   wire n_364;
   wire n_365;
   wire n_366;
   wire n_367;
   wire n_368;
   wire n_369;
   wire n_370;
   wire n_371;
   wire n_372;
   wire n_373;
   wire n_374;
   wire n_375;
   wire n_376;
   wire n_377;
   wire n_378;
   wire n_379;
   wire n_380;
   wire n_381;
   wire n_382;
   wire n_383;
   wire n_384;
   wire n_385;
   wire n_386;
   wire n_387;
   wire n_388;
   wire n_389;
   wire n_390;
   wire n_391;
   wire n_392;
   wire n_393;
   wire n_394;
   wire n_395;
   wire n_396;
   wire n_397;
   wire n_398;
   wire n_399;
   wire n_400;
   wire n_401;
   wire n_402;
   wire n_403;
   wire n_404;
   wire n_405;
   wire n_406;
   wire n_407;
   wire n_408;
   wire n_409;
   wire n_410;
   wire n_411;
   wire n_412;
   wire n_413;
   wire n_414;
   wire n_415;
   wire n_416;
   wire n_417;
   wire n_418;
   wire n_419;
   wire n_420;
   wire n_421;
   wire n_422;
   wire n_423;
   wire n_424;
   wire n_425;
   wire n_426;
   wire n_427;
   wire n_428;
   wire n_429;
   wire n_430;
   wire n_431;
   wire n_432;
   wire n_433;
   wire n_434;
   wire n_435;
   wire n_436;
   wire n_437;
   wire n_438;
   wire n_439;
   wire n_440;
   wire n_441;
   wire n_442;
   wire n_443;
   wire n_444;
   wire n_445;
   wire n_446;
   wire n_447;
   wire n_448;
   wire n_449;
   wire n_450;
   wire n_451;
   wire n_452;
   wire n_453;
   wire n_454;
   wire n_455;
   wire n_456;
   wire n_457;
   wire n_458;
   wire n_459;
   wire n_460;
   wire n_461;
   wire n_462;
   wire n_463;
   wire n_464;
   wire n_465;
   wire n_466;
   wire n_467;
   wire n_468;
   wire n_469;
   wire n_470;
   wire n_471;
   wire n_472;
   wire n_473;
   wire n_474;
   wire n_475;
   wire n_476;
   wire n_477;
   wire n_478;
   wire n_479;
   wire n_480;
   wire n_481;
   wire n_482;
   wire n_483;
   wire n_484;
   wire n_485;
   wire n_486;
   wire n_487;
   wire n_488;
   wire n_489;
   wire n_490;
   wire n_491;
   wire n_492;
   wire n_493;
   wire n_494;
   wire n_495;
   wire n_496;
   wire n_497;
   wire n_498;
   wire n_499;
   wire n_500;
   wire n_501;
   wire n_502;
   wire n_503;
   wire n_504;
   wire n_505;
   wire n_506;
   wire n_507;
   wire n_508;
   wire n_509;
   wire n_510;
   wire n_511;
   wire n_512;
   wire n_513;
   wire n_514;
   wire n_515;
   wire n_516;
   wire n_517;
   wire n_518;
   wire n_519;
   wire n_520;
   wire n_521;
   wire n_522;
   wire n_523;
   wire n_524;
   wire n_525;
   wire n_526;
   wire n_527;
   wire n_528;
   wire n_529;
   wire n_530;
   wire n_531;
   wire n_532;
   wire n_533;
   wire n_534;
   wire n_535;
   wire n_536;
   wire n_537;
   wire n_538;
   wire n_539;
   wire n_540;
   wire n_541;
   wire n_542;
   wire n_543;
   wire n_544;
   wire n_545;
   wire n_546;
   wire n_547;
   wire n_548;
   wire n_549;
   wire n_550;
   wire n_551;
   wire n_552;
   wire n_553;
   wire n_554;
   wire n_555;
   wire n_556;
   wire n_557;
   wire n_558;
   wire n_559;
   wire n_560;
   wire n_561;
   wire n_562;
   wire n_563;
   wire n_564;
   wire n_565;
   wire n_567;
   wire n_568;
   wire n_569;
   wire n_570;
   wire n_571;
   wire n_572;
   wire n_573;
   wire n_574;
   wire n_575;
   wire n_576;
   wire n_577;
   wire n_578;
   wire n_579;
   wire n_580;
   wire n_581;
   wire n_582;
   wire n_583;
   wire n_584;
   wire n_596;
   wire n_597;
   wire n_628;
   wire n_629;
   wire n_630;
   wire n_631;
   wire n_633;
   wire n_636;
   wire opening;
   wire reached;
   wire waiting;

   CLKBUFX6M FE_OFC0_an_reset (.A(an_reset),
	.Y(FE_OFN0_an_reset));
   INVX2M FE_DBTC1_an_reset (.A(an_reset),
	.Y(FE_DBTN1_an_reset));
   CLKINVX3M FE_DBTC0_buttons_block (.A(buttons_block),
	.Y(FE_DBTN0_buttons_block));
   buttons_res buttons_inst (.clk(clk),
	.an_reset(an_reset),
	.buttons_block(buttons_block),
	.btn_in(btn_in),
	.btn_up_out(btn_up_out),
	.btn_down_out(btn_down_out),
	.inactivate_in_levels({ UNCONNECTED_HIER_Z0,
		inactivate_in_levels[6],
		inactivate_in_levels[5],
		inactivate_in_levels[4],
		inactivate_in_levels[3],
		inactivate_in_levels[2],
		inactivate_in_levels[1],
		UNCONNECTED_HIER_Z }),
	.inactivate_out_up_levels({ inactivate_out_up_levels[6],
		inactivate_out_up_levels[5],
		inactivate_out_up_levels[4],
		inactivate_out_up_levels[3],
		inactivate_out_up_levels[2],
		inactivate_out_up_levels[1],
		inactivate_in_levels[0] }),
	.inactivate_out_down_levels({ inactivate_in_levels[7],
		inactivate_out_down_levels[6],
		inactivate_out_down_levels[5],
		inactivate_out_down_levels[4],
		inactivate_out_down_levels[3],
		inactivate_out_down_levels[2],
		inactivate_out_down_levels[1] }),
	.active_in_levels(active_in_levels),
	.active_out_up_levels(active_out_up_levels),
	.active_out_down_levels(active_out_down_levels),
	.p1(FE_DBTN0_buttons_block),
	.p2(FE_DBTN1_an_reset),
	.FE_OFN0_an_reset(FE_OFN0_an_reset));
   AO21XLM g19157 (.A0(reached),
	.A1(n_577),
	.B0(buttons_block),
	.Y(n_569));
   NOR2BX2M g19158 (.AN(n_573),
	.B(letout),
	.Y(n_568));
   NOR2BX2M g19159 (.AN(n_574),
	.B(letout),
	.Y(n_567));
   AO21XLM g19160 (.A0(n_633),
	.A1(n_630),
	.B0(buttons_block),
	.Y(n_570));
   NOR2BX2M g19161 (.AN(n_628),
	.B(letout),
	.Y(n_596));
   NOR2BX2M g19162 (.AN(n_631),
	.B(letout),
	.Y(n_597));
   NOR2BX2M g19163 (.AN(n_628),
	.B(buttons_block),
	.Y(n_573));
   NOR2BX2M g19164 (.AN(n_631),
	.B(buttons_block),
	.Y(n_574));
   AND2X2M g19165 (.A(n_629),
	.B(direction),
	.Y(n_577));
   NOR2X2M g19166 (.A(n_583),
	.B(n_582),
	.Y(n_630));
   NOR2BX2M g19167 (.AN(n_575),
	.B(n_576),
	.Y(n_628));
   NOR2X2M g19168 (.A(n_579),
	.B(n_580),
	.Y(n_629));
   NOR2X2M g19169 (.A(n_583),
	.B(n_584),
	.Y(n_631));
   CLKNAND2X2M g19170 (.A(n_565),
	.B(state[0]),
	.Y(n_578));
   NAND2BX2M g19171 (.AN(state[0]),
	.B(n_565),
	.Y(n_579));
   NOR2BX2M g19172 (.AN(n_565),
	.B(state[3]),
	.Y(n_575));
   NOR2BX2M g19173 (.AN(reached),
	.B(direction),
	.Y(n_633));
   OR3X2M g19174 (.A(state[0]),
	.B(state[2]),
	.C(state[4]),
	.Y(n_583));
   NAND2BX2M g19175 (.AN(state[3]),
	.B(state[1]),
	.Y(n_581));
   DFFRQX2M bell_out_reg (.D(bell),
	.CK(clk),
	.RN(an_reset),
	.Q(bell_out));
   AND2X2M g19177 (.A(sensor_up),
	.B(sensor_down),
	.Y(reached));
   NOR2BX2M g19178 (.AN(state[2]),
	.B(state[4]),
	.Y(n_565));
   OR2X2M g19179 (.A(state[3]),
	.B(state[1]),
	.Y(n_584));
   CLKNAND2X2M g19180 (.A(state[1]),
	.B(state[3]),
	.Y(n_580));
   CLKNAND2X2M g19181 (.A(state[1]),
	.B(state[0]),
	.Y(n_576));
   NAND2BX2M g19182 (.AN(state[1]),
	.B(state[3]),
	.Y(n_582));
   DFFRQX2M closing_reg (.D(n_206),
	.CK(clk),
	.RN(an_reset),
	.Q(closing));
   SDFFRQX2M \counter_reg[0]  (.SI(n_455),
	.SE(counter[0]),
	.D(n_474),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[0]));
   DFFRQX2M \counter_reg[1]  (.D(n_490),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[1]));
   DFFRQX2M \counter_reg[2]  (.D(n_486),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[2]));
   DFFRQX2M \counter_reg[3]  (.D(n_484),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[3]));
   DFFRQX2M \counter_reg[4]  (.D(n_483),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[4]));
   DFFRQX2M \counter_reg[5]  (.D(n_487),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[5]));
   DFFRQX2M \counter_reg[6]  (.D(n_488),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[6]));
   DFFRQX2M \counter_reg[7]  (.D(n_489),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[7]));
   DFFRQX2M \counter_reg[8]  (.D(n_514),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[8]));
   DFFRQX2M \counter_reg[9]  (.D(n_537),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[9]));
   DFFRQX2M \counter_reg[10]  (.D(n_545),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[10]));
   DFFRQX2M \counter_reg[11]  (.D(n_547),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[11]));
   DFFRQX2M \counter_reg[12]  (.D(n_554),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[12]));
   DFFRQX2M \counter_reg[13]  (.D(n_561),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[13]));
   DFFRQX2M \counter_reg[15]  (.D(n_564),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(counter[15]));
   DFFRQX2M \door_reg[0]  (.D(n_309),
	.CK(clk),
	.RN(an_reset),
	.Q(door[0]));
   DFFRQX2M \door_reg[1]  (.D(n_279),
	.CK(clk),
	.RN(an_reset),
	.Q(door[1]));
   DFFRQX2M \engine_reg[0]  (.D(n_520),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(engine[0]));
   DFFRQX2M \engine_reg[1]  (.D(n_519),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(engine[1]));
   SDFFRQX2M i_direction_reg (.SI(i_direction),
	.SE(n_336),
	.D(direction),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(i_direction));
   DFFQX1M \i_engine_reg[0]  (.D(n_549),
	.CK(clk),
	.Q(i_engine[0]));
   DFFQX1M \i_engine_reg[1]  (.D(n_555),
	.CK(clk),
	.Q(i_engine[1]));
   DFFRQX2M \inactivate_in_levels_reg[0]  (.D(n_63),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_in_levels[0]));
   DFFRQX2M \inactivate_in_levels_reg[1]  (.D(n_424),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_in_levels[1]));
   DFFRQX2M \inactivate_in_levels_reg[2]  (.D(n_445),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_in_levels[2]));
   DFFRQX2M \inactivate_in_levels_reg[3]  (.D(n_358),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_in_levels[3]));
   DFFRQX2M \inactivate_in_levels_reg[4]  (.D(n_423),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_in_levels[4]));
   DFFRQX2M \inactivate_in_levels_reg[5]  (.D(n_362),
	.CK(clk),
	.RN(an_reset),
	.Q(inactivate_in_levels[5]));
   DFFRQX2M \inactivate_in_levels_reg[6]  (.D(n_459),
	.CK(clk),
	.RN(an_reset),
	.Q(inactivate_in_levels[6]));
   DFFRQX2M \inactivate_in_levels_reg[7]  (.D(n_61),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_in_levels[7]));
   DFFRQX2M \inactivate_out_down_levels_reg[1]  (.D(n_422),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_down_levels[1]));
   DFFRQX2M \inactivate_out_down_levels_reg[2]  (.D(n_403),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_down_levels[2]));
   DFFRQX2M \inactivate_out_down_levels_reg[3]  (.D(n_300),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_down_levels[3]));
   DFFRQX2M \inactivate_out_down_levels_reg[4]  (.D(n_369),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_down_levels[4]));
   DFFRQX2M \inactivate_out_down_levels_reg[5]  (.D(n_264),
	.CK(clk),
	.RN(an_reset),
	.Q(inactivate_out_down_levels[5]));
   DFFRQX2M \inactivate_out_down_levels_reg[6]  (.D(n_265),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_down_levels[6]));
   DFFRQX2M \inactivate_out_up_levels_reg[1]  (.D(n_256),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_up_levels[1]));
   DFFRQX2M \inactivate_out_up_levels_reg[2]  (.D(n_255),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_up_levels[2]));
   DFFRQX2M \inactivate_out_up_levels_reg[3]  (.D(n_290),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_up_levels[3]));
   DFFRQX2M \inactivate_out_up_levels_reg[4]  (.D(n_404),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_up_levels[4]));
   DFFRQX2M \inactivate_out_up_levels_reg[5]  (.D(n_332),
	.CK(clk),
	.RN(an_reset),
	.Q(inactivate_out_up_levels[5]));
   DFFRQX2M \inactivate_out_up_levels_reg[6]  (.D(n_452),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(inactivate_out_up_levels[6]));
   DFFQX1M \level_display_reg[0]  (.D(n_361),
	.CK(clk),
	.Q(level_display[0]));
   DFFQX1M \level_display_reg[1]  (.D(n_346),
	.CK(clk),
	.Q(level_display[1]));
   DFFQX1M \level_display_reg[2]  (.D(n_359),
	.CK(clk),
	.Q(level_display[2]));
   DFFQX1M \level_display_reg[3]  (.D(n_324),
	.CK(clk),
	.Q(level_display[3]));
   DFFRQX2M opening_reg (.D(n_436),
	.CK(clk),
	.RN(an_reset),
	.Q(opening));
   DFFQX1M \saved_state_reg[0]  (.D(n_1),
	.CK(clk),
	.Q(saved_state[0]));
   DFFQX1M \saved_state_reg[1]  (.D(n_546),
	.CK(clk),
	.Q(saved_state[1]));
   DFFQX1M \saved_state_reg[2]  (.D(n_530),
	.CK(clk),
	.Q(saved_state[2]));
   DFFQX1M \saved_state_reg[3]  (.D(n_506),
	.CK(clk),
	.Q(saved_state[3]));
   DFFSRHQX2M \state_reg[0]  (.D(n_548),
	.CK(clk),
	.SN(n_40),
	.RN(n_44),
	.Q(state[0]));
   DFFSRHQX2M \state_reg[1]  (.D(n_542),
	.CK(clk),
	.SN(n_14),
	.RN(n_42),
	.Q(state[1]));
   DFFSRHQX2M \state_reg[2]  (.D(n_531),
	.CK(clk),
	.SN(n_39),
	.RN(n_43),
	.Q(state[2]));
   DFFSRHQX2M \state_reg[3]  (.D(n_532),
	.CK(clk),
	.SN(n_13),
	.RN(n_41),
	.Q(state[3]));
   DFFRQX2M \state_reg[4]  (.D(n_498),
	.CK(clk),
	.RN(an_reset),
	.Q(state[4]));
   DFFRQX2M waiting_reg (.D(n_512),
	.CK(clk),
	.RN(an_reset),
	.Q(waiting));
   OAI2BB2X1M g39590 (.A0N(counter[15]),
	.A1N(n_560),
	.B0(n_562),
	.B1(n_473),
	.Y(n_564));
   OAI2BB2X1M g39592 (.A0N(counter[14]),
	.A1N(n_560),
	.B0(n_473),
	.B1(n_559),
	.Y(n_563));
   AOI22X1M g39594 (.A0(n_558),
	.A1(n_38),
	.B0(n_2),
	.B1(counter[15]),
	.Y(n_562));
   AO22XLM g39595 (.A0(n_474),
	.A1(n_557),
	.B0(n_455),
	.B1(counter[13]),
	.Y(n_561));
   NAND2BX2M g39596 (.AN(n_455),
	.B(n_558),
	.Y(n_560));
   NAND2X2M g39597 (.A(n_558),
	.B(n_2),
	.Y(n_559));
   ADDHX1M g39598 (.A(counter[13]),
	.B(n_550),
	.S(n_557),
	.CO(n_558));
   OAI22X1M g39601 (.A0(buttons_block),
	.A1(n_553),
	.B0(n_410),
	.B1(n_375),
	.Y(n_556));
   NAND2X2M g39602 (.A(n_552),
	.B(n_504),
	.Y(n_555));
   AO22XLM g39603 (.A0(n_474),
	.A1(n_551),
	.B0(n_455),
	.B1(counter[12]),
	.Y(n_554));
   NOR4BX1M g39606 (.AN(n_374),
	.B(n_541),
	.C(n_368),
	.D(n_343),
	.Y(n_553));
   AOI32X1M g39607 (.A0(n_543),
	.A1(n_477),
	.A2(n_47),
	.B0(n_478),
	.B1(i_engine[1]),
	.Y(n_552));
   ADDHX1M g39609 (.A(counter[12]),
	.B(n_536),
	.S(n_551),
	.CO(n_550));
   OAI2B11X2M g39612 (.A0(n_477),
	.A1N(i_engine[0]),
	.B0(n_543),
	.C0(n_505),
	.Y(n_549));
   OAI2BB1X2M g39613 (.A0N(state[0]),
	.A1N(buttons_block),
	.B0(n_544),
	.Y(n_548));
   OAI2BB2X1M g39614 (.A0N(counter[11]),
	.A1N(n_539),
	.B0(n_473),
	.B1(n_540),
	.Y(n_547));
   NAND4X2M g39617 (.A(n_533),
	.B(n_515),
	.C(n_518),
	.D(n_504),
	.Y(n_546));
   OAI2BB2X1M g39618 (.A0N(counter[10]),
	.A1N(n_539),
	.B0(n_473),
	.B1(n_535),
	.Y(n_545));
   AOI22X1M g39619 (.A0(FE_DBTN0_buttons_block),
	.A1(n_538),
	.B0(n_460),
	.B1(saved_state[0]),
	.Y(n_544));
   AOI211X2M g39621 (.A0(n_477),
	.A1(n_246),
	.B0(n_529),
	.C0(n_511),
	.Y(n_543));
   NAND4BX1M g39623 (.AN(n_179),
	.B(n_524),
	.C(n_381),
	.D(n_453),
	.Y(n_542));
   NAND4X2M g39624 (.A(n_525),
	.B(n_355),
	.C(n_289),
	.D(n_268),
	.Y(n_541));
   MXI2X1M g39625 (.S0(counter[10]),
	.B(n_534),
	.A(counter[11]),
	.Y(n_540));
   NOR4BX1M g39629 (.AN(n_523),
	.B(n_421),
	.C(n_180),
	.D(n_179),
	.Y(n_538));
   AO22XLM g39630 (.A0(n_474),
	.A1(n_527),
	.B0(n_455),
	.B1(counter[9]),
	.Y(n_537));
   OAI21BX1M g39631 (.A0(n_473),
	.A1(n_528),
	.B0N(n_455),
	.Y(n_539));
   AND3X2M g39632 (.A(n_528),
	.B(counter[11]),
	.C(counter[10]),
	.Y(n_536));
   NAND2BX2M g39633 (.AN(counter[10]),
	.B(n_528),
	.Y(n_535));
   NOR2BX2M g39634 (.AN(n_528),
	.B(counter[11]),
	.Y(n_534));
   AOI221XLM g39635 (.A0(n_7),
	.A1(n_510),
	.B0(saved_state[1]),
	.B1(n_482),
	.C0(n_497),
	.Y(n_533));
   NAND4BX1M g39636 (.AN(n_267),
	.B(n_507),
	.C(n_340),
	.D(n_453),
	.Y(n_532));
   OR3X2M g39637 (.A(n_124),
	.B(n_521),
	.C(n_122),
	.Y(n_531));
   OAI2B11X2M g39638 (.A0(n_7),
	.A1N(n_510),
	.B0(n_508),
	.C0(n_485),
	.Y(n_530));
   OAI22X1M g39639 (.A0(n_522),
	.A1(direction),
	.B0(n_503),
	.B1(n_345),
	.Y(n_529));
   ADDHX1M g39640 (.A(counter[9]),
	.B(n_501),
	.S(n_527),
	.CO(n_528));
   AND4X2M g39644 (.A(n_513),
	.B(n_499),
	.C(n_495),
	.D(n_500),
	.Y(n_526));
   NOR4X1M g39645 (.A(n_496),
	.B(n_420),
	.C(n_287),
	.D(n_167),
	.Y(n_525));
   NOR4X1M g39646 (.A(n_421),
	.B(n_203),
	.C(n_494),
	.D(n_242),
	.Y(n_524));
   NOR4X1M g39647 (.A(n_475),
	.B(n_458),
	.C(n_267),
	.D(n_205),
	.Y(n_523));
   NOR3X2M g39648 (.A(n_510),
	.B(n_493),
	.C(n_492),
	.Y(n_522));
   NAND4BX1M g39649 (.AN(n_180),
	.B(n_479),
	.C(n_381),
	.D(n_453),
	.Y(n_521));
   CLKINVX2M g39652 (.A(n_517),
	.Y(n_520));
   CLKINVX2M g39653 (.A(n_516),
	.Y(n_519));
   AOI32X1M g39654 (.A0(FE_DBTN0_buttons_block),
	.A1(n_471),
	.A2(engine[0]),
	.B0(n_491),
	.B1(i_engine[0]),
	.Y(n_517));
   AOI32X1M g39655 (.A0(FE_DBTN0_buttons_block),
	.A1(n_471),
	.A2(engine[1]),
	.B0(n_491),
	.B1(i_engine[1]),
	.Y(n_516));
   AOI32X1M g39656 (.A0(n_477),
	.A1(n_305),
	.A2(n_20),
	.B0(n_493),
	.B1(direction),
	.Y(n_515));
   AO22XLM g39657 (.A0(n_474),
	.A1(n_502),
	.B0(n_455),
	.B1(counter[8]),
	.Y(n_514));
   AOI2BB2XLM g39658 (.A0N(n_503),
	.A1N(n_376),
	.B0(n_492),
	.B1(direction),
	.Y(n_513));
   AOI32X1M g39659 (.A0(n_481),
	.A1(n_109),
	.A2(letout),
	.B0(n_477),
	.B1(n_220),
	.Y(n_518));
   CLKINVX2M g39667 (.A(n_509),
	.Y(n_512));
   AOI32X1M g39669 (.A0(FE_DBTN0_buttons_block),
	.A1(n_465),
	.A2(n_126),
	.B0(n_476),
	.B1(waiting),
	.Y(n_509));
   AOI22X1M g39670 (.A0(n_482),
	.A1(saved_state[2]),
	.B0(n_477),
	.B1(n_16),
	.Y(n_508));
   AOI221XLM g39671 (.A0(state[3]),
	.A1(buttons_block),
	.B0(saved_state[3]),
	.B1(n_460),
	.C0(n_480),
	.Y(n_507));
   OAI2BB1X1M g39672 (.A0N(saved_state[3]),
	.A1N(n_482),
	.B0(n_478),
	.Y(n_506));
   OAI32X1M g39673 (.A0(n_478),
	.A1(n_305),
	.A2(n_19),
	.B0(n_482),
	.B1(n_9),
	.Y(n_511));
   OAI22X1M g39674 (.A0(n_482),
	.A1(n_137),
	.B0(n_478),
	.B1(n_17),
	.Y(n_510));
   ADDHX1M g39677 (.A(counter[8]),
	.B(n_469),
	.S(n_502),
	.CO(n_501));
   NAND2X2M g39678 (.A(n_482),
	.B(saved_state[0]),
	.Y(n_500));
   OAI2BB1X2M g39679 (.A0N(n_51),
	.A1N(n_17),
	.B0(n_477),
	.Y(n_499));
   NAND4X2M g39680 (.A(n_461),
	.B(n_450),
	.C(n_393),
	.D(n_401),
	.Y(n_498));
   AOI31X2M g39681 (.A0(n_129),
	.A1(n_139),
	.A2(n_10),
	.B0(n_482),
	.Y(n_497));
   NAND4X2M g39682 (.A(n_464),
	.B(n_378),
	.C(n_269),
	.D(n_252),
	.Y(n_496));
   OAI21X2M g39683 (.A0(n_233),
	.A1(n_630),
	.B0(n_481),
	.Y(n_495));
   NAND4X2M g39684 (.A(n_463),
	.B(n_0),
	.C(n_383),
	.D(n_320),
	.Y(n_494));
   OR3X2M g39685 (.A(n_478),
	.B(n_47),
	.C(n_166),
	.Y(n_505));
   NAND3BX2M g39686 (.AN(n_47),
	.B(n_477),
	.C(n_166),
	.Y(n_504));
   CLKNAND2X2M g39687 (.A(n_477),
	.B(n_90),
	.Y(n_503));
   AO22XLM g39688 (.A0(n_474),
	.A1(n_135),
	.B0(n_455),
	.B1(counter[1]),
	.Y(n_490));
   AO22XLM g39689 (.A0(n_474),
	.A1(n_470),
	.B0(n_455),
	.B1(counter[7]),
	.Y(n_489));
   AO22XLM g39690 (.A0(n_474),
	.A1(n_447),
	.B0(n_455),
	.B1(counter[6]),
	.Y(n_488));
   AO22XLM g39691 (.A0(n_474),
	.A1(n_409),
	.B0(n_455),
	.B1(counter[5]),
	.Y(n_487));
   AO22XLM g39692 (.A0(n_474),
	.A1(n_217),
	.B0(n_455),
	.B1(counter[2]),
	.Y(n_486));
   OAI31X1M g39693 (.A0(n_92),
	.A1(n_50),
	.A2(n_261),
	.B0(n_481),
	.Y(n_485));
   AO22XLM g39694 (.A0(n_474),
	.A1(n_271),
	.B0(n_455),
	.B1(counter[3]),
	.Y(n_484));
   AO22XLM g39695 (.A0(n_474),
	.A1(n_334),
	.B0(n_455),
	.B1(counter[4]),
	.Y(n_483));
   AOI2B1X1M g39696 (.A0(n_175),
	.A1N(n_16),
	.B0(n_478),
	.Y(n_493));
   NOR3X2M g39697 (.A(n_478),
	.B(n_192),
	.C(n_90),
	.Y(n_492));
   NOR3X2M g39698 (.A(reached),
	.B(buttons_block),
	.C(n_471),
	.Y(n_491));
   INVX2M g39699 (.A(n_482),
	.Y(n_481));
   NAND4BX1M g39700 (.AN(n_462),
	.B(n_395),
	.C(n_314),
	.D(n_381),
	.Y(n_480));
   AOI221XLM g39701 (.A0(saved_state[2]),
	.A1(n_460),
	.B0(state[2]),
	.B1(buttons_block),
	.C0(n_297),
	.Y(n_479));
   AOI21X2M g39702 (.A0(n_29),
	.A1(n_419),
	.B0(n_472),
	.Y(n_482));
   INVX2M g39703 (.A(n_478),
	.Y(n_477));
   OAI21X2M g39704 (.A0(n_465),
	.A1(n_353),
	.B0(n_177),
	.Y(n_476));
   NAND4BX1M g39705 (.AN(n_466),
	.B(n_245),
	.C(n_114),
	.D(n_266),
	.Y(n_475));
   AOI21X2M g39706 (.A0(n_29),
	.A1(n_420),
	.B0(n_472),
	.Y(n_478));
   INVX2M g39707 (.A(n_474),
	.Y(n_473));
   NOR2BX2M g39708 (.AN(n_468),
	.B(n_455),
	.Y(n_474));
   AO21XLM g39709 (.A0(n_29),
	.A1(n_444),
	.B0(n_467),
	.Y(n_472));
   AND4X2M g39710 (.A(n_449),
	.B(n_415),
	.C(n_399),
	.D(n_306),
	.Y(n_471));
   ADDHX1M g39711 (.A(counter[7]),
	.B(n_446),
	.S(n_470),
	.CO(n_469));
   AOI211X2M g39712 (.A0(n_353),
	.A1(n_125),
	.B0(n_396),
	.C0(n_456),
	.Y(n_468));
   AOI21BX2M g39713 (.A0(n_390),
	.A1(n_454),
	.B0N(n_29),
	.Y(n_467));
   NAND4BBX1M g39714 (.AN(n_203),
	.BN(n_567),
	.C(n_434),
	.D(n_340),
	.Y(n_466));
   NOR4X1M g39716 (.A(n_441),
	.B(n_377),
	.C(n_194),
	.D(n_226),
	.Y(n_464));
   AOI22X1M g39717 (.A0(n_458),
	.A1(saved_state[1]),
	.B0(n_127),
	.B1(n_151),
	.Y(n_463));
   OAI221X1M g39718 (.A0(n_243),
	.A1(reached),
	.B0(n_184),
	.B1(n_150),
	.C0(n_451),
	.Y(n_462));
   AOI221XLM g39719 (.A0(state[4]),
	.A1(buttons_block),
	.B0(n_106),
	.B1(n_429),
	.C0(n_457),
	.Y(n_461));
   NAND3BX2M g39720 (.AN(n_420),
	.B(n_454),
	.C(n_400),
	.Y(n_465));
   OAI211X2M g39722 (.A0(n_431),
	.A1(n_95),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_440),
	.Y(n_459));
   OR2X2M g39723 (.A(n_448),
	.B(n_456),
	.Y(n_460));
   INVX2M g39724 (.A(n_0),
	.Y(n_457));
   NAND2BX2M g39725 (.AN(n_448),
	.B(n_439),
	.Y(n_458));
   NOR2X2M g39728 (.A(n_410),
	.B(n_439),
	.Y(n_456));
   AND2X2M g39730 (.A(n_437),
	.B(n_375),
	.Y(n_455));
   NAND2X2M g39731 (.A(FE_DBTN0_buttons_block),
	.B(n_438),
	.Y(n_452));
   NOR2X2M g39732 (.A(n_435),
	.B(n_205),
	.Y(n_451));
   AOI221XLM g39733 (.A0(n_304),
	.A1(n_159),
	.B0(n_366),
	.B1(n_574),
	.C0(n_433),
	.Y(n_450));
   AOI31X2M g39734 (.A0(n_18),
	.A1(direction),
	.A2(n_221),
	.B0(n_442),
	.Y(n_449));
   AOI31X2M g39735 (.A0(n_326),
	.A1(n_142),
	.A2(n_48),
	.B0(n_443),
	.Y(n_454));
   AOI221X1M g39736 (.A0(n_298),
	.A1(n_573),
	.B0(n_365),
	.B1(n_574),
	.C0(n_428),
	.Y(n_453));
   ADDHX1M g39737 (.A(counter[6]),
	.B(n_408),
	.S(n_447),
	.CO(n_446));
   OAI211X2M g39738 (.A0(n_4),
	.A1(n_398),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_133),
	.Y(n_445));
   NAND3X2M g39739 (.A(n_426),
	.B(n_407),
	.C(n_400),
	.Y(n_444));
   OR2X2M g39740 (.A(n_430),
	.B(n_343),
	.Y(n_443));
   NAND3BX2M g39741 (.AN(n_577),
	.B(n_418),
	.C(n_398),
	.Y(n_442));
   OAI31X1M g39742 (.A0(n_410),
	.A1(n_411),
	.A2(n_143),
	.B0(n_234),
	.Y(n_441));
   NAND2X2M g39743 (.A(n_431),
	.B(inactivate_in_levels[6]),
	.Y(n_440));
   OAI31X1M g39744 (.A0(n_94),
	.A1(n_413),
	.A2(n_26),
	.B0(n_397),
	.Y(n_448));
   AOI2BB2XLM g39746 (.A0N(n_427),
	.A1N(n_95),
	.B0(n_427),
	.B1(inactivate_out_up_levels[6]),
	.Y(n_438));
   AOI221XLM g39747 (.A0(n_412),
	.A1(n_181),
	.B0(n_55),
	.B1(n_177),
	.C0(n_62),
	.Y(n_437));
   OAI31X1M g39748 (.A0(buttons_block),
	.A1(n_284),
	.A2(n_125),
	.B0(n_432),
	.Y(n_436));
   OAI222X1M g39749 (.A0(n_405),
	.A1(n_152),
	.B0(n_149),
	.B1(reached),
	.C0(n_178),
	.C1(n_337),
	.Y(n_435));
   NOR4X1M g39750 (.A(n_157),
	.B(n_155),
	.C(n_568),
	.D(n_416),
	.Y(n_434));
   OAI221X1M g39751 (.A0(n_387),
	.A1(n_141),
	.B0(n_215),
	.B1(letout),
	.C0(n_392),
	.Y(n_433));
   AOI22X1M g39752 (.A0(n_425),
	.A1(n_142),
	.B0(n_181),
	.B1(n_382),
	.Y(n_439));
   CLKNAND2X2M g39753 (.A(n_417),
	.B(opening),
	.Y(n_432));
   OAI21X2M g39757 (.A0(n_389),
	.A1(n_143),
	.B0(n_378),
	.Y(n_430));
   OAI2B1X2M g39758 (.A0(state[0]),
	.A1N(n_413),
	.B0(state[1]),
	.Y(n_429));
   OAI32X1M g39759 (.A0(n_31),
	.A1(n_367),
	.A2(n_65),
	.B0(n_394),
	.B1(n_141),
	.Y(n_428));
   AOI2BB1X2M g39760 (.A0N(n_4),
	.A1N(n_399),
	.B0(n_97),
	.Y(n_431));
   AOI221XLM g39761 (.A0(n_238),
	.A1(n_163),
	.B0(n_202),
	.B1(n_110),
	.C0(n_391),
	.Y(n_426));
   OAI221X1M g39762 (.A0(n_146),
	.A1(n_285),
	.B0(n_119),
	.B1(n_249),
	.C0(n_388),
	.Y(n_425));
   OAI211X2M g39763 (.A0(n_99),
	.A1(n_363),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_212),
	.Y(n_424));
   OAI211X2M g39764 (.A0(n_357),
	.A1(n_173),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_380),
	.Y(n_423));
   NAND3BX2M g39765 (.AN(n_377),
	.B(FE_DBTN0_buttons_block),
	.C(n_210),
	.Y(n_422));
   NOR2X2M g39766 (.A(n_402),
	.B(n_97),
	.Y(n_427));
   NAND3X2M g39769 (.A(n_284),
	.B(n_379),
	.C(n_356),
	.Y(n_419));
   AOI31X2M g39770 (.A0(n_293),
	.A1(n_52),
	.A2(direction),
	.B0(n_386),
	.Y(n_418));
   OAI2BB1X2M g39771 (.A0N(n_284),
	.A1N(n_384),
	.B0(n_177),
	.Y(n_417));
   AOI2B1X1M g39772 (.A0(n_383),
	.A1N(n_297),
	.B0(n_45),
	.Y(n_416));
   AOI22X1M g39773 (.A0(n_385),
	.A1(n_630),
	.B0(n_4),
	.B1(n_204),
	.Y(n_415));
   OAI22X1M g39774 (.A0(n_229),
	.A1(n_373),
	.B0(n_376),
	.B1(n_89),
	.Y(n_414));
   AO21XLM g39775 (.A0(n_151),
	.A1(waiting),
	.B0(n_406),
	.Y(n_421));
   OAI21X2M g39776 (.A0(n_379),
	.A1(n_8),
	.B0(n_356),
	.Y(n_420));
   CLKINVX2M g39777 (.A(n_411),
	.Y(n_412));
   ADDHX1M g39778 (.A(counter[5]),
	.B(n_333),
	.S(n_409),
	.CO(n_408));
   AOI211X2M g39779 (.A0(n_288),
	.A1(n_18),
	.B0(n_370),
	.C0(n_308),
	.Y(n_407));
   NOR4BX1M g39780 (.AN(n_55),
	.B(n_94),
	.C(n_353),
	.D(n_26),
	.Y(n_406));
   AND2X2M g39781 (.A(reached),
	.B(n_385),
	.Y(n_405));
   NAND2X2M g39782 (.A(FE_DBTN0_buttons_block),
	.B(n_372),
	.Y(n_404));
   NAND3X2M g39783 (.A(FE_DBTN0_buttons_block),
	.B(n_355),
	.C(n_188),
	.Y(n_403));
   OAI21X2M g39784 (.A0(n_101),
	.A1(n_78),
	.B0(n_374),
	.Y(n_402));
   AOI221XLM g39785 (.A0(n_249),
	.A1(n_118),
	.B0(n_326),
	.B1(n_120),
	.C0(n_317),
	.Y(n_401));
   AND2X2M g39787 (.A(n_384),
	.B(n_55),
	.Y(n_413));
   NOR3X2M g39788 (.A(n_382),
	.B(n_349),
	.C(n_316),
	.Y(n_411));
   NAND3BX2M g39790 (.AN(counter[10]),
	.B(n_351),
	.C(counter[7]),
	.Y(n_410));
   CLKINVX2M g39792 (.A(n_396),
	.Y(n_397));
   AOI22X1M g39793 (.A0(n_331),
	.A1(n_128),
	.B0(n_364),
	.B1(n_122),
	.Y(n_395));
   AOI221XLM g39794 (.A0(n_338),
	.A1(n_174),
	.B0(n_294),
	.B1(n_159),
	.C0(n_299),
	.Y(n_394));
   AOI22X1M g39795 (.A0(n_352),
	.A1(n_140),
	.B0(n_195),
	.B1(n_8),
	.Y(n_393));
   AOI22X1M g39796 (.A0(n_174),
	.A1(n_354),
	.B0(n_145),
	.B1(n_285),
	.Y(n_392));
   OAI2B2X1M g39797 (.A0(n_99),
	.A1N(n_363),
	.B0(n_162),
	.B1(n_251),
	.Y(n_391));
   AOI21X2M g39798 (.A0(n_364),
	.A1(n_629),
	.B0(n_325),
	.Y(n_390));
   AOI222X1M g39799 (.A0(n_354),
	.A1(n_115),
	.B0(n_283),
	.B1(n_50),
	.C0(n_249),
	.C1(n_22),
	.Y(n_389));
   OA21X2M g39800 (.A0(n_144),
	.A1(n_283),
	.B0(n_371),
	.Y(n_388));
   AOI222X1M g39801 (.A0(n_145),
	.A1(n_273),
	.B0(n_174),
	.B1(n_339),
	.C0(n_295),
	.C1(n_159),
	.Y(n_387));
   OAI22X1M g39802 (.A0(n_347),
	.A1(direction),
	.B0(reached),
	.B1(n_175),
	.Y(n_386));
   AOI21X2M g39803 (.A0(n_350),
	.A1(n_142),
	.B0(n_368),
	.Y(n_400));
   AOI33X2M g39804 (.A0(n_344),
	.A1(n_629),
	.A2(n_7),
	.B0(n_16),
	.B1(direction),
	.B2(n_150),
	.Y(n_399));
   AOI33X2M g39805 (.A0(n_337),
	.A1(n_116),
	.A2(direction),
	.B0(n_52),
	.B1(n_7),
	.B2(n_201),
	.Y(n_398));
   NOR3BX2M g39806 (.AN(n_367),
	.B(n_31),
	.C(n_65),
	.Y(n_396));
   NAND2X2M g39807 (.A(n_357),
	.B(inactivate_in_levels[4]),
	.Y(n_380));
   CLKNAND2X2M g39813 (.A(n_45),
	.B(n_363),
	.Y(n_385));
   NAND2BX2M g39814 (.AN(waiting),
	.B(n_353),
	.Y(n_384));
   NAND2BX2M g39815 (.AN(n_364),
	.B(n_122),
	.Y(n_383));
   NOR2BX2M g39816 (.AN(n_115),
	.B(n_354),
	.Y(n_382));
   CLKNAND2X2M g39817 (.A(n_348),
	.B(n_140),
	.Y(n_381));
   OAI22X1M g39818 (.A0(n_329),
	.A1(n_89),
	.B0(n_187),
	.B1(n_7),
	.Y(n_373));
   AOI2BB2XLM g39819 (.A0N(n_342),
	.A1N(n_173),
	.B0(n_342),
	.B1(inactivate_out_up_levels[4]),
	.Y(n_372));
   AOI2B1X1M g39820 (.A0(n_159),
	.A1N(n_304),
	.B0(n_360),
	.Y(n_371));
   OAI22X1M g39821 (.A0(n_161),
	.A1(n_337),
	.B0(n_164),
	.B1(n_147),
	.Y(n_370));
   OAI211X2M g39822 (.A0(n_173),
	.A1(n_313),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_330),
	.Y(n_369));
   AOI22X1M g39823 (.A0(n_628),
	.A1(n_277),
	.B0(n_327),
	.B1(n_631),
	.Y(n_379));
   NAND3X2M g39824 (.A(n_339),
	.B(n_140),
	.C(n_115),
	.Y(n_378));
   NOR3BX2M g39825 (.AN(n_66),
	.B(n_99),
	.C(n_328),
	.Y(n_377));
   AOI222X1M g39826 (.A0(n_303),
	.A1(n_115),
	.B0(n_50),
	.B1(n_117),
	.C0(n_259),
	.C1(n_138),
	.Y(n_376));
   NAND3BX2M g39827 (.AN(n_326),
	.B(n_181),
	.C(n_48),
	.Y(n_375));
   NAND4X2M g39828 (.A(n_633),
	.B(n_312),
	.C(n_629),
	.D(n_77),
	.Y(n_374));
   INVX1M g39829 (.A(n_365),
	.Y(n_366));
   OAI211X2M g39830 (.A0(n_103),
	.A1(n_292),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_244),
	.Y(n_362));
   NAND2X2M g39831 (.A(n_322),
	.B(n_35),
	.Y(n_361));
   NOR2BX2M g39832 (.AN(n_120),
	.B(n_326),
	.Y(n_360));
   NAND2BX2M g39833 (.AN(n_341),
	.B(n_321),
	.Y(n_359));
   NAND2X2M g39834 (.A(FE_DBTN0_buttons_block),
	.B(n_318),
	.Y(n_358));
   NOR2X2M g39837 (.A(n_315),
	.B(n_141),
	.Y(n_368));
   NOR4BX1M g39838 (.AN(counter[7]),
	.B(n_291),
	.C(counter[10]),
	.D(counter[6]),
	.Y(n_367));
   NOR2X2M g39839 (.A(n_327),
	.B(n_8),
	.Y(n_365));
   NOR2BX2M g39840 (.AN(n_633),
	.B(n_344),
	.Y(n_364));
   AND2X2M g39841 (.A(n_328),
	.B(n_66),
	.Y(n_363));
   OAI222X1M g39842 (.A0(n_121),
	.A1(n_311),
	.B0(n_119),
	.B1(n_240),
	.C0(n_144),
	.C1(n_275),
	.Y(n_352));
   NOR4BX1M g39843 (.AN(counter[2]),
	.B(n_296),
	.C(counter[12]),
	.D(counter[9]),
	.Y(n_351));
   AO22XLM g39844 (.A0(n_285),
	.A1(n_138),
	.B0(n_304),
	.B1(n_20),
	.Y(n_350));
   OAI22X1M g39845 (.A0(n_285),
	.A1(n_139),
	.B0(n_304),
	.B1(n_19),
	.Y(n_349));
   OAI2BB2XLM g39846 (.A0N(n_311),
	.A1N(n_120),
	.B0(n_144),
	.B1(n_276),
	.Y(n_348));
   AOI21BX2M g39847 (.A0(n_147),
	.A1(n_116),
	.B0N(n_319),
	.Y(n_347));
   NAND2BX2M g39848 (.AN(n_341),
	.B(n_323),
	.Y(n_346));
   AOI2B1X1M g39849 (.A0(n_115),
	.A1N(n_303),
	.B0(n_281),
	.Y(n_345));
   AOI2BB1X2M g39850 (.A0N(n_4),
	.A1N(n_306),
	.B0(n_92),
	.Y(n_357));
   NAND3X2M g39851 (.A(n_310),
	.B(n_140),
	.C(n_48),
	.Y(n_356));
   OR3X2M g39852 (.A(n_161),
	.B(n_307),
	.C(active_in_levels[2]),
	.Y(n_355));
   OAI2BB2X1M g39853 (.A0N(direction),
	.A1N(n_303),
	.B0(direction),
	.B1(n_53),
	.Y(n_354));
   NOR4BX1M g39854 (.AN(counter[10]),
	.B(n_296),
	.C(n_83),
	.D(counter[7]),
	.Y(n_353));
   INVX1M g39855 (.A(n_339),
	.Y(n_338));
   CLKINVX2M g39856 (.A(n_335),
	.Y(n_336));
   ADDHX1M g39857 (.A(counter[4]),
	.B(n_270),
	.S(n_334),
	.CO(n_333));
   NAND3X2M g39858 (.A(FE_DBTN0_buttons_block),
	.B(n_289),
	.C(n_158),
	.Y(n_332));
   OAI21X2M g39859 (.A0(n_46),
	.A1(n_293),
	.B0(n_225),
	.Y(n_331));
   NAND2X2M g39860 (.A(n_313),
	.B(inactivate_out_down_levels[4]),
	.Y(n_330));
   AOI221XLM g39861 (.A0(n_20),
	.A1(n_272),
	.B0(n_25),
	.B1(n_48),
	.C0(n_220),
	.Y(n_329));
   NAND2BX2M g39862 (.AN(n_312),
	.B(n_77),
	.Y(n_344));
   NOR2X2M g39863 (.A(n_301),
	.B(n_141),
	.Y(n_343));
   NOR3X2M g39866 (.A(n_287),
	.B(n_92),
	.C(n_198),
	.Y(n_342));
   OAI21X2M g39867 (.A0(n_282),
	.A1(n_79),
	.B0(n_35),
	.Y(n_341));
   NAND3X2M g39868 (.A(n_633),
	.B(n_124),
	.C(n_292),
	.Y(n_340));
   NAND2BX2M g39869 (.AN(n_303),
	.B(n_53),
	.Y(n_339));
   CLKNAND2X2M g39870 (.A(n_307),
	.B(n_87),
	.Y(n_337));
   AOI21X2M g39871 (.A0(n_284),
	.A1(n_235),
	.B0(buttons_block),
	.Y(n_335));
   OAI2B2X1M g39872 (.A0(n_103),
	.A1N(n_292),
	.B0(n_101),
	.B1(n_150),
	.Y(n_325));
   OAI2BB1X2M g39873 (.A0N(level_display[3]),
	.A1N(n_282),
	.B0(n_35),
	.Y(n_324));
   MXI2X1M g39874 (.S0(n_282),
	.B(level_display[1]),
	.A(n_636),
	.Y(n_323));
   MXI2X1M g39875 (.S0(n_282),
	.B(level_display[0]),
	.A(n_263),
	.Y(n_322));
   AOI2BB2XLM g39876 (.A0N(n_282),
	.A1N(n_156),
	.B0(n_282),
	.B1(level_display[2]),
	.Y(n_321));
   AOI222X1M g39877 (.A0(n_160),
	.A1(n_274),
	.B0(n_46),
	.B1(n_123),
	.C0(state[1]),
	.C1(buttons_block),
	.Y(n_320));
   OA22X2M g39878 (.A0(n_292),
	.A1(n_15),
	.B0(n_137),
	.B1(n_238),
	.Y(n_319));
   AOI222X1M g39879 (.A0(n_98),
	.A1(n_293),
	.B0(n_163),
	.B1(n_239),
	.C0(inactivate_in_levels[3]),
	.C1(n_176),
	.Y(n_318));
   AO2B2BX2M g39880 (.A0(n_283),
	.A1N(n_144),
	.B0(n_573),
	.B1N(n_298),
	.Y(n_317));
   OAI22X1M g39881 (.A0(n_283),
	.A1(n_49),
	.B0(n_21),
	.B1(n_249),
	.Y(n_316));
   AOI22X1M g39882 (.A0(n_138),
	.A1(n_273),
	.B0(n_295),
	.B1(n_20),
	.Y(n_315));
   AOI22X1M g39883 (.A0(n_160),
	.A1(n_288),
	.B0(n_180),
	.B1(n_250),
	.Y(n_314));
   NAND3BX2M g39884 (.AN(active_out_up_levels[1]),
	.B(n_302),
	.C(active_out_down_levels[1]),
	.Y(n_328));
   OR3X2M g39885 (.A(n_303),
	.B(n_82),
	.C(active_out_up_levels[0]),
	.Y(n_327));
   OAI2BB2X1M g39886 (.A0N(n_7),
	.A1N(n_286),
	.B0(n_7),
	.B1(n_25),
	.Y(n_326));
   INVX2M g39887 (.A(n_310),
	.Y(n_311));
   OAI32X1M g39888 (.A0(n_254),
	.A1(n_54),
	.A2(n_32),
	.B0(n_253),
	.B1(buttons_block),
	.Y(n_309));
   NOR2BX2M g39889 (.AN(n_98),
	.B(n_293),
	.Y(n_308));
   NOR2X2M g39890 (.A(n_92),
	.B(n_280),
	.Y(n_313));
   NOR2BX2M g39892 (.AN(active_out_up_levels[6]),
	.B(n_286),
	.Y(n_312));
   NAND2BX2M g39894 (.AN(n_286),
	.B(n_25),
	.Y(n_310));
   CLKINVX2M g39895 (.A(n_303),
	.Y(n_302));
   AOI2BB2XLM g39896 (.A0N(n_21),
	.A1N(n_240),
	.B0(n_276),
	.B1(n_50),
	.Y(n_301));
   NAND3X2M g39897 (.A(FE_DBTN0_buttons_block),
	.B(n_268),
	.C(n_209),
	.Y(n_300));
   OAI2BB2XLM g39898 (.A0N(n_240),
	.A1N(n_118),
	.B0(n_146),
	.B1(n_273),
	.Y(n_299));
   NAND3BX2M g39899 (.AN(active_out_up_levels[2]),
	.B(n_272),
	.C(active_out_down_levels[2]),
	.Y(n_307));
   AOI33X2M g39900 (.A0(n_18),
	.A1(n_260),
	.A2(n_7),
	.B0(n_136),
	.B1(n_251),
	.B2(direction),
	.Y(n_306));
   AOI21X2M g39901 (.A0(n_272),
	.A1(n_90),
	.B0(n_30),
	.Y(n_305));
   OAI2BB2X1M g39902 (.A0N(n_148),
	.A1N(n_7),
	.B0(n_272),
	.B1(n_7),
	.Y(n_304));
   NAND3BX2M g39903 (.AN(active_out_up_levels[2]),
	.B(n_272),
	.C(n_37),
	.Y(n_303));
   INVX1M g39904 (.A(n_295),
	.Y(n_294));
   OR3X2M g39905 (.A(n_247),
	.B(counter[5]),
	.C(counter[4]),
	.Y(n_291));
   NAND3X2M g39906 (.A(FE_DBTN0_buttons_block),
	.B(n_252),
	.C(n_208),
	.Y(n_290));
   NOR2X2M g39907 (.A(n_277),
	.B(n_8),
	.Y(n_298));
   NOR2BX2M g39908 (.AN(n_160),
	.B(n_274),
	.Y(n_297));
   NAND4X2M g39911 (.A(n_237),
	.B(counter[4]),
	.C(counter[5]),
	.D(counter[6]),
	.Y(n_296));
   NAND2BX2M g39912 (.AN(n_148),
	.B(n_272),
	.Y(n_295));
   OAI31X1M g39913 (.A0(n_259),
	.A1(n_12),
	.A2(active_out_up_levels[3]),
	.B0(n_85),
	.Y(n_293));
   AND2X2M g39914 (.A(n_278),
	.B(n_70),
	.Y(n_292));
   OAI22X1M g39915 (.A0(n_139),
	.A1(n_259),
	.B0(n_49),
	.B1(n_117),
	.Y(n_281));
   OAI31X1M g39916 (.A0(n_3),
	.A1(n_17),
	.A2(n_73),
	.B0(n_269),
	.Y(n_280));
   OAI32X1M g39917 (.A0(n_231),
	.A1(n_88),
	.A2(n_32),
	.B0(n_257),
	.B1(buttons_block),
	.Y(n_279));
   NAND3BX2M g39918 (.AN(n_278),
	.B(n_102),
	.C(n_70),
	.Y(n_289));
   OAI21BX1M g39919 (.A0(n_46),
	.A1(n_221),
	.B0N(n_274),
	.Y(n_288));
   NOR4BX1M g39920 (.AN(n_73),
	.B(n_23),
	.C(n_17),
	.D(n_241),
	.Y(n_287));
   NAND3BX2M g39921 (.AN(active_out_up_levels[5]),
	.B(n_248),
	.C(n_60),
	.Y(n_286));
   OAI2BB2X1M g39922 (.A0N(direction),
	.A1N(n_259),
	.B0(direction),
	.B1(n_200),
	.Y(n_285));
   NOR4BX2M g39923 (.AN(n_129),
	.B(n_233),
	.C(n_92),
	.D(n_597),
	.Y(n_284));
   OAI2BB2X1M g39924 (.A0N(n_117),
	.A1N(direction),
	.B0(n_248),
	.B1(direction),
	.Y(n_283));
   NAND2X2M g39925 (.A(FE_OFN0_an_reset),
	.B(n_262),
	.Y(n_282));
   CLKINVX2M g39926 (.A(n_276),
	.Y(n_275));
   ADDHX1M g39927 (.A(counter[3]),
	.B(n_216),
	.S(n_271),
	.CO(n_270));
   NAND2X2M g39928 (.A(n_248),
	.B(active_out_up_levels[5]),
	.Y(n_278));
   OR2X2M g39931 (.A(n_259),
	.B(n_218),
	.Y(n_277));
   NAND2BX2M g39932 (.AN(n_117),
	.B(n_248),
	.Y(n_276));
   NOR2X2M g39933 (.A(n_23),
	.B(n_260),
	.Y(n_274));
   NAND2BX2M g39934 (.AN(n_259),
	.B(n_200),
	.Y(n_273));
   NOR2X2M g39935 (.A(n_259),
	.B(n_107),
	.Y(n_272));
   OAI2B1X2M g39936 (.A0(n_242),
	.A1N(n_152),
	.B0(n_46),
	.Y(n_266));
   OAI211X2M g39937 (.A0(n_95),
	.A1(n_224),
	.B0(FE_DBTN0_buttons_block),
	.C0(n_236),
	.Y(n_265));
   NAND3X2M g39938 (.A(FE_DBTN0_buttons_block),
	.B(n_234),
	.C(n_189),
	.Y(n_264));
   NAND4BX1M g39939 (.AN(n_116),
	.B(n_222),
	.C(n_15),
	.D(n_137),
	.Y(n_263));
   NAND3X2M g39940 (.A(n_235),
	.B(n_222),
	.C(n_168),
	.Y(n_262));
   OAI21X2M g39941 (.A0(n_21),
	.A1(n_230),
	.B0(n_79),
	.Y(n_261));
   NAND3BX2M g39942 (.AN(n_162),
	.B(n_232),
	.C(active_out_down_levels[4]),
	.Y(n_269));
   NAND4BX1M g39943 (.AN(n_259),
	.B(n_98),
	.C(active_out_down_levels[3]),
	.D(n_59),
	.Y(n_268));
   NOR3BX2M g39944 (.AN(n_123),
	.B(n_3),
	.C(n_239),
	.Y(n_267));
   AND2X2M g39945 (.A(n_243),
	.B(n_153),
	.Y(n_258));
   NAND2X2M g39946 (.A(n_231),
	.B(door[1]),
	.Y(n_257));
   NAND3BX2M g39947 (.AN(n_226),
	.B(FE_DBTN0_buttons_block),
	.C(n_207),
	.Y(n_256));
   NAND2X2M g39948 (.A(FE_DBTN0_buttons_block),
	.B(n_228),
	.Y(n_255));
   NAND2BX2M g39949 (.AN(n_231),
	.B(n_33),
	.Y(n_254));
   NAND2X2M g39950 (.A(n_231),
	.B(door[0]),
	.Y(n_253));
   CLKNAND2X2M g39951 (.A(n_241),
	.B(n_73),
	.Y(n_260));
   NAND2BX2M g39952 (.AN(active_out_down_levels[4]),
	.B(n_232),
	.Y(n_259));
   INVX1M g39953 (.A(n_251),
	.Y(n_250));
   NAND3BX2M g39954 (.AN(n_83),
	.B(n_223),
	.C(counter[3]),
	.Y(n_247));
   OR3X2M g39955 (.A(n_109),
	.B(n_628),
	.C(n_220),
	.Y(n_246));
   OAI2B1X2M g39956 (.A0(n_195),
	.A1N(n_215),
	.B0(n_8),
	.Y(n_245));
   AOI22X1M g39957 (.A0(n_105),
	.A1(n_221),
	.B0(n_96),
	.B1(inactivate_in_levels[5]),
	.Y(n_244));
   NAND3BX2M g39958 (.AN(n_227),
	.B(n_163),
	.C(n_72),
	.Y(n_252));
   OAI31X1M g39959 (.A0(n_191),
	.A1(active_out_up_levels[4]),
	.A2(n_11),
	.B0(n_84),
	.Y(n_251));
   OAI2BB2X1M g39960 (.A0N(n_7),
	.A1N(n_218),
	.B0(n_7),
	.B1(n_190),
	.Y(n_249));
   NOR4X1M g39961 (.A(n_218),
	.B(active_in_levels[4]),
	.C(active_out_up_levels[4]),
	.D(active_out_down_levels[4]),
	.Y(n_248));
   INVX2M g39962 (.A(n_239),
	.Y(n_238));
   NOR2BX2M g39963 (.AN(n_223),
	.B(counter[3]),
	.Y(n_237));
   NAND2X2M g39964 (.A(n_224),
	.B(inactivate_out_down_levels[6]),
	.Y(n_236));
   NOR4X1M g39965 (.A(n_169),
	.B(n_124),
	.C(n_160),
	.D(n_122),
	.Y(n_243));
   AND2X2M g39967 (.A(n_128),
	.B(n_225),
	.Y(n_242));
   NAND2BX2M g39968 (.AN(n_218),
	.B(active_out_up_levels[4]),
	.Y(n_241));
   NOR2X2M g39969 (.A(n_218),
	.B(n_191),
	.Y(n_240));
   CLKNAND2X2M g39970 (.A(n_227),
	.B(n_72),
	.Y(n_239));
   AOI21X2M g39971 (.A0(n_90),
	.A1(n_191),
	.B0(n_58),
	.Y(n_230));
   AOI21X2M g39972 (.A0(n_10),
	.A1(n_89),
	.B0(n_222),
	.Y(n_229));
   AOI211X2M g39973 (.A0(n_93),
	.A1(inactivate_out_up_levels[2]),
	.B0(n_194),
	.C0(n_196),
	.Y(n_228));
   NOR3BX2M g39974 (.AN(n_175),
	.B(n_204),
	.C(n_630),
	.Y(n_235));
   NAND3X2M g39975 (.A(n_105),
	.B(n_193),
	.C(n_68),
	.Y(n_234));
   OAI21BX1M g39976 (.A0(n_192),
	.A1(letout),
	.B0N(n_596),
	.Y(n_233));
   NOR3X2M g39977 (.A(active_in_levels[4]),
	.B(n_191),
	.C(active_out_up_levels[4]),
	.Y(n_232));
   OAI2B1X2M g39978 (.A0(n_154),
	.A1N(n_199),
	.B0(state[4]),
	.Y(n_231));
   ADDHX1M g39979 (.A(counter[2]),
	.B(n_134),
	.S(n_217),
	.CO(n_216));
   NAND2X2M g39980 (.A(n_200),
	.B(active_out_up_levels[3]),
	.Y(n_227));
   NOR3BX2M g39981 (.AN(n_76),
	.B(n_164),
	.C(n_108),
	.Y(n_226));
   NAND2X2M g39982 (.A(n_633),
	.B(n_202),
	.Y(n_225));
   AOI211X2M g39983 (.A0(n_633),
	.A1(n_132),
	.B0(n_97),
	.C0(n_167),
	.Y(n_224));
   NOR4BX1M g39984 (.AN(counter[8]),
	.B(n_111),
	.C(counter[13]),
	.D(counter[11]),
	.Y(n_223));
   AND2X2M g39985 (.A(n_192),
	.B(n_10),
	.Y(n_222));
   NAND2BX2M g39986 (.AN(n_193),
	.B(n_68),
	.Y(n_221));
   NOR2X2M g39987 (.A(n_21),
	.B(n_191),
	.Y(n_220));
   NAND2BX2M g39989 (.AN(n_107),
	.B(n_200),
	.Y(n_218));
   AOI2B1X1M g39990 (.A0(n_147),
	.A1N(n_164),
	.B0(n_197),
	.Y(n_212));
   AOI2B1X1M g39992 (.A0(inactivate_out_down_levels[1]),
	.A1N(n_172),
	.B0(n_186),
	.Y(n_210));
   AOI32X1M g39993 (.A0(n_633),
	.A1(n_136),
	.A2(n_71),
	.B0(n_176),
	.B1(inactivate_out_down_levels[3]),
	.Y(n_209));
   AOI22X1M g39994 (.A0(n_98),
	.A1(n_86),
	.B0(n_176),
	.B1(inactivate_out_up_levels[3]),
	.Y(n_208));
   AOI2BB2XLM g39995 (.A0N(n_99),
	.A1N(n_66),
	.B0(n_171),
	.B1(inactivate_out_up_levels[1]),
	.Y(n_207));
   OAI2BB2X1M g39996 (.A0N(closing),
	.A1N(n_183),
	.B0(n_127),
	.B1(n_183),
	.Y(n_206));
   NOR3X2M g39997 (.A(n_145),
	.B(n_174),
	.C(n_159),
	.Y(n_215));
   INVX2M g40000 (.A(n_201),
	.Y(n_202));
   OAI21X2M g40001 (.A0(n_127),
	.A1(n_81),
	.B0(n_130),
	.Y(n_199));
   NOR2X2M g40002 (.A(n_162),
	.B(n_84),
	.Y(n_198));
   NOR2BX2M g40003 (.AN(inactivate_in_levels[1]),
	.B(n_172),
	.Y(n_197));
   NOR2X2M g40004 (.A(n_161),
	.B(n_87),
	.Y(n_196));
   NOR3X2M g40005 (.A(n_3),
	.B(n_149),
	.C(n_147),
	.Y(n_205));
   NAND2X2M g40006 (.A(n_173),
	.B(n_95),
	.Y(n_204));
   OAI2BB1X2M g40007 (.A0N(n_27),
	.A1N(n_112),
	.B0(n_184),
	.Y(n_203));
   CLKNAND2X2M g40008 (.A(n_185),
	.B(n_75),
	.Y(n_201));
   NOR3BX2M g40009 (.AN(n_37),
	.B(n_148),
	.C(active_out_up_levels[2]),
	.Y(n_200));
   INVX2M g40010 (.A(n_190),
	.Y(n_191));
   AOI32X1M g40011 (.A0(n_633),
	.A1(n_16),
	.A2(n_69),
	.B0(n_96),
	.B1(inactivate_out_down_levels[5]),
	.Y(n_189));
   AOI32X1M g40012 (.A0(n_633),
	.A1(n_52),
	.A2(n_74),
	.B0(n_93),
	.B1(inactivate_out_down_levels[2]),
	.Y(n_188));
   AOI2BB1X2M g40013 (.A0N(n_90),
	.A1N(n_631),
	.B0(n_168),
	.Y(n_187));
   NOR3BX2M g40014 (.AN(n_116),
	.B(n_3),
	.C(n_76),
	.Y(n_186));
   NAND3X2M g40015 (.A(n_144),
	.B(n_119),
	.C(n_121),
	.Y(n_195));
   NOR2X2M g40016 (.A(n_185),
	.B(n_131),
	.Y(n_194));
   NOR3BX2M g40017 (.AN(active_out_down_levels[5]),
	.B(n_117),
	.C(active_out_up_levels[5]),
	.Y(n_193));
   NOR3X2M g40018 (.A(n_138),
	.B(n_115),
	.C(n_50),
	.Y(n_192));
   NOR3BX2M g40019 (.AN(n_60),
	.B(n_117),
	.C(active_out_up_levels[5]),
	.Y(n_190));
   CLKINVX2M g40020 (.A(n_179),
	.Y(n_178));
   INVX2M g40021 (.A(n_171),
	.Y(n_172));
   OR2X2M g40023 (.A(n_123),
	.B(n_128),
	.Y(n_169));
   NAND2BX2M g40024 (.AN(n_148),
	.B(active_out_up_levels[2]),
	.Y(n_185));
   CLKNAND2X2M g40025 (.A(n_45),
	.B(n_124),
	.Y(n_184));
   NAND2BX2M g40026 (.AN(n_32),
	.B(n_130),
	.Y(n_183));
   NOR2X2M g40028 (.A(buttons_block),
	.B(n_143),
	.Y(n_181));
   NOR2BX2M g40029 (.AN(n_123),
	.B(n_46),
	.Y(n_180));
   NOR2X2M g40030 (.A(n_46),
	.B(n_149),
	.Y(n_179));
   NOR2X2M g40031 (.A(buttons_block),
	.B(n_126),
	.Y(n_177));
   NAND2X2M g40032 (.A(n_138),
	.B(n_8),
	.Y(n_176));
   NOR2X2M g40033 (.A(n_116),
	.B(n_52),
	.Y(n_175));
   NOR2BX2M g40034 (.AN(n_115),
	.B(buttons_block),
	.Y(n_174));
   NOR2X2M g40035 (.A(n_136),
	.B(n_18),
	.Y(n_173));
   CLKNAND2X2M g40036 (.A(n_115),
	.B(n_8),
	.Y(n_171));
   AOI22X1M g40037 (.A0(n_105),
	.A1(n_67),
	.B0(n_96),
	.B1(inactivate_out_up_levels[5]),
	.Y(n_158));
   NOR4BX1M g40038 (.AN(n_27),
	.B(n_94),
	.C(n_54),
	.D(n_36),
	.Y(n_157));
   NOR4X1M g40039 (.A(n_16),
	.B(n_22),
	.C(n_18),
	.D(n_50),
	.Y(n_156));
   AOI21BX2M g40040 (.A0(n_34),
	.A1(n_81),
	.B0N(n_151),
	.Y(n_155));
   NOR2X2M g40041 (.A(n_113),
	.B(n_584),
	.Y(n_154));
   OAI21X2M g40042 (.A0(n_91),
	.A1(n_27),
	.B0(n_64),
	.Y(n_153));
   NOR4X1M g40043 (.A(n_48),
	.B(n_22),
	.C(n_631),
	.D(n_20),
	.Y(n_168));
   NOR3X2M g40044 (.A(n_101),
	.B(active_in_levels[6]),
	.C(n_80),
	.Y(n_167));
   AOI21X2M g40045 (.A0(n_90),
	.A1(n_25),
	.B0(n_30),
	.Y(n_166));
   NAND2BX2M g40047 (.AN(n_23),
	.B(n_116),
	.Y(n_164));
   NOR2X2M g40048 (.A(n_23),
	.B(n_137),
	.Y(n_163));
   CLKNAND2X2M g40049 (.A(n_45),
	.B(n_136),
	.Y(n_162));
   CLKNAND2X2M g40050 (.A(n_45),
	.B(n_116),
	.Y(n_161));
   NOR3BX2M g40051 (.AN(n_27),
	.B(buttons_block),
	.C(n_65),
	.Y(n_160));
   NOR3X2M g40052 (.A(buttons_block),
	.B(n_104),
	.C(n_26),
	.Y(n_159));
   INVX2M g40053 (.A(n_146),
	.Y(n_145));
   INVX2M g40054 (.A(n_143),
	.Y(n_142));
   INVX2M g40055 (.A(n_141),
	.Y(n_140));
   INVX2M g40056 (.A(n_139),
	.Y(n_138));
   INVX2M g40057 (.A(n_137),
	.Y(n_136));
   ADDHX1M g40058 (.A(counter[1]),
	.B(counter[0]),
	.S(n_135),
	.CO(n_134));
   CLKNAND2X2M g40059 (.A(n_93),
	.B(inactivate_in_levels[2]),
	.Y(n_133));
   NOR2X2M g40060 (.A(n_9),
	.B(n_77),
	.Y(n_132));
   CLKNAND2X2M g40061 (.A(n_110),
	.B(n_75),
	.Y(n_131));
   CLKNAND2X2M g40064 (.A(n_64),
	.B(n_27),
	.Y(n_152));
   AND2X2M g40065 (.A(n_91),
	.B(n_106),
	.Y(n_151));
   CLKNAND2X2M g40066 (.A(n_80),
	.B(n_78),
	.Y(n_150));
   CLKNAND2X2M g40067 (.A(n_91),
	.B(n_64),
	.Y(n_149));
   NAND2BX2M g40068 (.AN(n_82),
	.B(n_53),
	.Y(n_148));
   CLKNAND2X2M g40069 (.A(n_76),
	.B(n_108),
	.Y(n_147));
   OR2X2M g40070 (.A(n_31),
	.B(n_104),
	.Y(n_146));
   CLKNAND2X2M g40071 (.A(n_91),
	.B(n_575),
	.Y(n_144));
   CLKNAND2X2M g40072 (.A(n_89),
	.B(letout),
	.Y(n_143));
   CLKNAND2X2M g40073 (.A(n_90),
	.B(letout),
	.Y(n_141));
   NAND2BX2M g40074 (.AN(n_581),
	.B(n_100),
	.Y(n_139));
   NAND2BX2M g40075 (.AN(n_580),
	.B(n_100),
	.Y(n_137));
   INVX2M g40076 (.A(n_126),
	.Y(n_125));
   INVX2M g40077 (.A(n_121),
	.Y(n_120));
   INVX1M g40078 (.A(n_119),
	.Y(n_118));
   OAI2BB1X2M g40079 (.A0N(n_576),
	.A1N(n_28),
	.B0(state[4]),
	.Y(n_114));
   OAI2B1X2M g40080 (.A0(n_54),
	.A1N(n_36),
	.B0(n_33),
	.Y(n_113));
   NOR3BX2M g40081 (.AN(n_54),
	.B(n_94),
	.C(closing),
	.Y(n_112));
   OR4X1M g40082 (.A(counter[1]),
	.B(counter[0]),
	.C(counter[14]),
	.D(counter[15]),
	.Y(n_111));
   NOR3X2M g40083 (.A(n_56),
	.B(n_584),
	.C(waiting),
	.Y(n_130));
   NOR2BX2M g40084 (.AN(n_93),
	.B(n_97),
	.Y(n_129));
   NOR2BX2M g40085 (.AN(n_64),
	.B(n_26),
	.Y(n_128));
   NOR3X2M g40086 (.A(n_34),
	.B(overload),
	.C(sensor_inside),
	.Y(n_127));
   NAND3BX2M g40087 (.AN(n_581),
	.B(n_33),
	.C(state[4]),
	.Y(n_126));
   NOR2BX2M g40088 (.AN(n_91),
	.B(n_65),
	.Y(n_124));
   NOR2BX2M g40089 (.AN(n_64),
	.B(n_31),
	.Y(n_123));
   NOR2X2M g40090 (.A(n_65),
	.B(n_26),
	.Y(n_122));
   NAND3BX2M g40091 (.AN(n_26),
	.B(FE_DBTN0_buttons_block),
	.C(n_575),
	.Y(n_121));
   NAND3X2M g40092 (.A(FE_DBTN0_buttons_block),
	.B(n_575),
	.C(n_27),
	.Y(n_119));
   OR4X1M g40093 (.A(active_in_levels[6]),
	.B(n_24),
	.C(active_out_up_levels[6]),
	.D(active_out_down_levels[6]),
	.Y(n_117));
   NOR2BX2M g40094 (.AN(n_100),
	.B(n_582),
	.Y(n_116));
   NOR2X2M g40095 (.A(n_104),
	.B(n_57),
	.Y(n_115));
   CLKINVX2M g40096 (.A(n_103),
	.Y(n_102));
   INVX2M g40097 (.A(n_90),
	.Y(n_89));
   NAND2BX2M g40098 (.AN(n_56),
	.B(n_34),
	.Y(n_88));
   NOR2X2M g40099 (.A(n_23),
	.B(n_51),
	.Y(n_110));
   NOR2BX2M g40100 (.AN(n_30),
	.B(n_21),
	.Y(n_109));
   NAND2X2M g40101 (.A(n_53),
	.B(active_out_up_levels[1]),
	.Y(n_108));
   NAND2X2M g40102 (.A(n_59),
	.B(n_12),
	.Y(n_107));
   AND2X2M g40103 (.A(n_28),
	.B(state[4]),
	.Y(n_106));
   NOR2X2M g40104 (.A(n_46),
	.B(n_17),
	.Y(n_105));
   NAND2BX2M g40105 (.AN(state[4]),
	.B(n_28),
	.Y(n_104));
   OR2X2M g40106 (.A(n_23),
	.B(n_15),
	.Y(n_103));
   CLKNAND2X2M g40107 (.A(n_45),
	.B(n_16),
	.Y(n_101));
   NOR2X2M g40108 (.A(n_56),
	.B(state[4]),
	.Y(n_100));
   CLKNAND2X2M g40109 (.A(n_45),
	.B(n_630),
	.Y(n_99));
   NOR2X2M g40110 (.A(n_46),
	.B(n_51),
	.Y(n_98));
   NOR2X2M g40111 (.A(n_47),
	.B(letout),
	.Y(n_97));
   NAND2X2M g40112 (.A(n_50),
	.B(n_8),
	.Y(n_96));
   NOR2X2M g40113 (.A(n_16),
	.B(n_629),
	.Y(n_95));
   NAND2BX2M g40114 (.AN(n_32),
	.B(n_28),
	.Y(n_94));
   CLKNAND2X2M g40115 (.A(n_20),
	.B(n_8),
	.Y(n_93));
   NOR2X2M g40116 (.A(n_21),
	.B(letout),
	.Y(n_92));
   NOR2X2M g40117 (.A(buttons_block),
	.B(n_57),
	.Y(n_91));
   NOR2X2M g40118 (.A(n_30),
	.B(n_58),
	.Y(n_90));
   INVX1M g40119 (.A(n_85),
	.Y(n_86));
   INVX1M g40120 (.A(n_75),
	.Y(n_74));
   INVX1M g40121 (.A(n_72),
	.Y(n_71));
   INVX1M g40122 (.A(n_70),
	.Y(n_69));
   INVX1M g40123 (.A(n_68),
	.Y(n_67));
   AO21XLM g40124 (.A0(n_572),
	.A1(inactivate_in_levels[0]),
	.B0(n_570),
	.Y(n_63));
   NOR3X2M g40125 (.A(buttons_block),
	.B(n_578),
	.C(n_580),
	.Y(n_62));
   AO21XLM g40126 (.A0(n_571),
	.A1(inactivate_in_levels[7]),
	.B0(n_569),
	.Y(n_61));
   AOI2B1X1M g40127 (.A0(active_out_up_levels[2]),
	.A1N(overload),
	.B0(active_in_levels[2]),
	.Y(n_87));
   AOI2B1X1M g40128 (.A0(active_out_up_levels[3]),
	.A1N(overload),
	.B0(active_in_levels[3]),
	.Y(n_85));
   AOI2B1X1M g40129 (.A0(active_out_up_levels[4]),
	.A1N(overload),
	.B0(active_in_levels[4]),
	.Y(n_84));
   NAND3BX2M g40130 (.AN(counter[2]),
	.B(counter[9]),
	.C(counter[12]),
	.Y(n_83));
   OR3X2M g40131 (.A(active_in_levels[1]),
	.B(active_out_up_levels[1]),
	.C(active_out_down_levels[1]),
	.Y(n_82));
   NOR3X2M g40132 (.A(overload),
	.B(open_btn),
	.C(sensor_inside),
	.Y(n_81));
   NAND3BX2M g40133 (.AN(active_out_up_levels[6]),
	.B(n_25),
	.C(active_out_down_levels[6]),
	.Y(n_80));
   NOR3X2M g40134 (.A(n_48),
	.B(n_628),
	.C(n_629),
	.Y(n_79));
   AOI2B1X1M g40135 (.A0(active_out_up_levels[6]),
	.A1N(overload),
	.B0(active_in_levels[6]),
	.Y(n_78));
   AOI2B1X1M g40136 (.A0(active_out_down_levels[6]),
	.A1N(overload),
	.B0(active_in_levels[6]),
	.Y(n_77));
   AOI2B1X1M g40137 (.A0(active_out_down_levels[1]),
	.A1N(overload),
	.B0(active_in_levels[1]),
	.Y(n_76));
   AOI2B1X1M g40138 (.A0(active_out_down_levels[2]),
	.A1N(overload),
	.B0(active_in_levels[2]),
	.Y(n_75));
   AOI2BB1X2M g40139 (.A0N(overload),
	.A1N(n_11),
	.B0(active_in_levels[4]),
	.Y(n_73));
   AOI2BB1X2M g40140 (.A0N(overload),
	.A1N(n_12),
	.B0(active_in_levels[3]),
	.Y(n_72));
   AOI2B1X1M g40141 (.A0(active_out_down_levels[5]),
	.A1N(overload),
	.B0(active_in_levels[5]),
	.Y(n_70));
   AOI2B1X1M g40142 (.A0(active_out_up_levels[5]),
	.A1N(overload),
	.B0(active_in_levels[5]),
	.Y(n_68));
   AOI2B1X1M g40143 (.A0(active_out_up_levels[1]),
	.A1N(overload),
	.B0(active_in_levels[1]),
	.Y(n_66));
   NAND3BX2M g40144 (.AN(state[4]),
	.B(state[3]),
	.C(state[2]),
	.Y(n_65));
   NOR3BX2M g40145 (.AN(state[3]),
	.B(state[4]),
	.C(state[2]),
	.Y(n_64));
   INVX2M g40146 (.A(n_52),
	.Y(n_51));
   INVX2M g40147 (.A(n_50),
	.Y(n_49));
   INVX2M g40148 (.A(n_48),
	.Y(n_47));
   INVX2M g40149 (.A(n_46),
	.Y(n_45));
   OR2X1M g40150 (.A(an_reset),
	.B(saved_state[0]),
	.Y(n_44));
   OR2X1M g40151 (.A(an_reset),
	.B(saved_state[2]),
	.Y(n_43));
   OR2X1M g40152 (.A(an_reset),
	.B(saved_state[1]),
	.Y(n_42));
   OR2X1M g40153 (.A(an_reset),
	.B(saved_state[3]),
	.Y(n_41));
   NAND2XLM g40154 (.A(FE_DBTN1_an_reset),
	.B(saved_state[0]),
	.Y(n_40));
   NAND2XLM g40155 (.A(FE_DBTN1_an_reset),
	.B(saved_state[2]),
	.Y(n_39));
   NOR2X2M g40156 (.A(n_2),
	.B(counter[15]),
	.Y(n_38));
   NOR2X2M g40157 (.A(active_in_levels[5]),
	.B(active_out_down_levels[5]),
	.Y(n_60));
   NOR2X2M g40158 (.A(active_in_levels[3]),
	.B(active_out_up_levels[3]),
	.Y(n_59));
   NOR2BX2M g40159 (.AN(i_direction),
	.B(n_7),
	.Y(n_58));
   NAND2BX2M g40160 (.AN(state[1]),
	.B(state[0]),
	.Y(n_57));
   NAND2BX2M g40161 (.AN(state[2]),
	.B(state[0]),
	.Y(n_56));
   OR2X2M g40162 (.A(waiting),
	.B(opening),
	.Y(n_55));
   NOR2BX2M g40163 (.AN(sensor_door[0]),
	.B(sensor_door[1]),
	.Y(n_54));
   NOR2X2M g40164 (.A(active_in_levels[0]),
	.B(active_out_up_levels[0]),
	.Y(n_53));
   NOR2X2M g40165 (.A(n_583),
	.B(n_580),
	.Y(n_52));
   NOR2X2M g40166 (.A(n_578),
	.B(n_584),
	.Y(n_50));
   NOR2X2M g40167 (.A(n_579),
	.B(n_581),
	.Y(n_48));
   CLKNAND2X2M g40168 (.A(reached),
	.B(direction),
	.Y(n_46));
   INVX1M g40169 (.A(n_25),
	.Y(n_24));
   INVX2M g40170 (.A(n_22),
	.Y(n_21));
   INVX2M g40171 (.A(n_20),
	.Y(n_19));
   INVX2M g40172 (.A(n_18),
	.Y(n_17));
   INVX2M g40173 (.A(n_16),
	.Y(n_15));
   NAND2XLM g40174 (.A(FE_DBTN1_an_reset),
	.B(saved_state[1]),
	.Y(n_14));
   NAND2XLM g40175 (.A(FE_DBTN1_an_reset),
	.B(saved_state[3]),
	.Y(n_13));
   NOR2X2M g40176 (.A(active_in_levels[2]),
	.B(active_out_down_levels[2]),
	.Y(n_37));
   NOR2BX2M g40177 (.AN(close_btn),
	.B(opening),
	.Y(n_36));
   NAND2X2M g40178 (.A(FE_OFN0_an_reset),
	.B(buttons_block),
	.Y(n_35));
   NAND2BX2M g40179 (.AN(sensor_door[0]),
	.B(sensor_door[1]),
	.Y(n_34));
   NOR2X2M g40180 (.A(state[0]),
	.B(state[2]),
	.Y(n_33));
   CLKNAND2X2M g40181 (.A(FE_DBTN0_buttons_block),
	.B(state[4]),
	.Y(n_32));
   OR2X2M g40182 (.A(buttons_block),
	.B(n_576),
	.Y(n_31));
   NOR2X2M g40183 (.A(direction),
	.B(i_direction),
	.Y(n_30));
   NOR2X2M g40184 (.A(FE_DBTN1_an_reset),
	.B(buttons_block),
	.Y(n_29));
   NOR2X2M g40185 (.A(state[2]),
	.B(state[3]),
	.Y(n_28));
   NOR2X2M g40186 (.A(state[0]),
	.B(state[1]),
	.Y(n_27));
   NAND2BX2M g40187 (.AN(state[0]),
	.B(state[1]),
	.Y(n_26));
   NOR2X2M g40188 (.A(active_in_levels[7]),
	.B(active_out_down_levels[7]),
	.Y(n_25));
   CLKNAND2X2M g40189 (.A(reached),
	.B(n_7),
	.Y(n_23));
   NOR2X2M g40190 (.A(n_579),
	.B(n_584),
	.Y(n_22));
   NOR2X2M g40191 (.A(n_583),
	.B(n_581),
	.Y(n_20));
   NOR2X2M g40192 (.A(n_579),
	.B(n_582),
	.Y(n_18));
   NOR2X2M g40193 (.A(n_578),
	.B(n_582),
	.Y(n_16));
   INVX2M g40194 (.A(active_out_down_levels[3]),
	.Y(n_12));
   INVX2M g40195 (.A(active_out_down_levels[4]),
	.Y(n_11));
   INVX2M g40197 (.A(n_628),
	.Y(n_10));
   INVX2M g40198 (.A(n_629),
	.Y(n_9));
   INVX2M g40199 (.A(letout),
	.Y(n_8));
   INVX2M g40200 (.A(direction),
	.Y(n_7));
   INVX2M g40203 (.A(reached),
	.Y(n_4));
   INVX2M g40204 (.A(n_633),
	.Y(n_3));
   DFFRX1M \counter_reg[14]  (.D(n_563),
	.CK(clk),
	.RN(an_reset),
	.Q(counter[14]),
	.QN(n_2));
   NAND4BX1M g2 (.AN(n_511),
	.B(n_526),
	.C(n_518),
	.D(n_505),
	.Y(n_1));
   NAND2BX2M g40207 (.AN(n_439),
	.B(n_410),
	.Y(n_0));
   INVXLM g40216 (.A(n_597),
	.Y(n_572));
   INVXLM g40217 (.A(n_596),
	.Y(n_571));
   NAND4BBX1M g40218 (.AN(n_136),
	.BN(n_52),
	.C(n_139),
	.D(n_19),
	.Y(n_636));
   SDFFRQX2M direction_reg (.SI(n_414),
	.SE(n_556),
	.D(direction),
	.CK(clk),
	.RN(FE_OFN0_an_reset),
	.Q(direction));
   SDFFRQX2M letout_reg (.SI(n_258),
	.SE(n_335),
	.D(letout),
	.CK(clk),
	.RN(an_reset),
	.Q(letout));
endmodule

