###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID lab513-pc1)
#  Generated on:      Sat Jun 29 23:57:41 2019
#  Design:            elevator
#  Command:           saveIoFile -locations elevator.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopin
)
