
// Generated by Cadence Genus(TM) Synthesis Solution 16.12-s027_1
// Generated on: Jun 29 2019 23:39:03 CEST (Jun 29 2019 21:39:03 UTC)

// Verification Directory fv/elevator 

module buttons_res(clock, an_reset, buttons_block, btn_in, btn_up_out,
     btn_down_out, inactivate_in_levels, inactivate_out_up_levels,
     inactivate_out_down_levels, active_in_levels,
     active_out_up_levels, active_out_down_levels);
  input clock, an_reset, buttons_block;
  input [7:0] btn_in, inactivate_in_levels;
  input [6:0] btn_up_out, inactivate_out_up_levels;
  input [7:1] btn_down_out, inactivate_out_down_levels;
  output [7:0] active_in_levels;
  output [6:0] active_out_up_levels;
  output [7:1] active_out_down_levels;
  wire clock, an_reset, buttons_block;
  wire [7:0] btn_in, inactivate_in_levels;
  wire [6:0] btn_up_out, inactivate_out_up_levels;
  wire [7:1] btn_down_out, inactivate_out_down_levels;
  wire [7:0] active_in_levels;
  wire [6:0] active_out_up_levels;
  wire [7:1] active_out_down_levels;
  wire [7:0] l_active_in_levels;
  wire [7:0] buttons_state;
  wire [7:0] l_btn_in;
  wire [7:0] l_inactivate_in_levels;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_225;
  DCBX1 \active_in_levels_reg[0] (.CLR (1'b1), .CLK (clock), .D
       (n_191), .Q (active_in_levels[0]), .QB (l_active_in_levels[0]));
  DCBX1 \active_in_levels_reg[1] (.CLR (1'b1), .CLK (clock), .D
       (n_195), .Q (active_in_levels[1]), .QB (l_active_in_levels[1]));
  DCBX1 \active_in_levels_reg[2] (.CLR (1'b1), .CLK (clock), .D
       (n_189), .Q (active_in_levels[2]), .QB (l_active_in_levels[2]));
  DCBX1 \active_in_levels_reg[3] (.CLR (1'b1), .CLK (clock), .D
       (n_188), .Q (active_in_levels[3]), .QB (l_active_in_levels[3]));
  DCBX1 \active_in_levels_reg[4] (.CLR (1'b1), .CLK (clock), .D
       (n_193), .Q (active_in_levels[4]), .QB (l_active_in_levels[4]));
  DCBX1 \active_in_levels_reg[5] (.CLR (1'b1), .CLK (clock), .D
       (n_192), .Q (active_in_levels[5]), .QB (l_active_in_levels[5]));
  DCBX1 \active_in_levels_reg[6] (.CLR (1'b1), .CLK (clock), .D
       (n_190), .Q (active_in_levels[6]), .QB (l_active_in_levels[6]));
  DCBX1 \active_in_levels_reg[7] (.CLR (1'b1), .CLK (clock), .D
       (n_194), .Q (active_in_levels[7]), .QB (UNCONNECTED));
  DCBX1 \active_out_down_levels_reg[1] (.CLR (1'b1), .CLK (clock), .D
       (n_107), .Q (active_out_down_levels[1]), .QB (UNCONNECTED0));
  DCBX1 \active_out_down_levels_reg[2] (.CLR (1'b1), .CLK (clock), .D
       (n_111), .Q (active_out_down_levels[2]), .QB (UNCONNECTED1));
  DCBX1 \active_out_down_levels_reg[3] (.CLR (1'b1), .CLK (clock), .D
       (n_110), .Q (active_out_down_levels[3]), .QB (UNCONNECTED2));
  DCBX1 \active_out_down_levels_reg[4] (.CLR (1'b1), .CLK (clock), .D
       (n_109), .Q (active_out_down_levels[4]), .QB (UNCONNECTED3));
  DCBX1 \active_out_down_levels_reg[5] (.CLR (1'b1), .CLK (clock), .D
       (n_108), .Q (active_out_down_levels[5]), .QB (UNCONNECTED4));
  DCBX1 \active_out_down_levels_reg[6] (.CLR (1'b1), .CLK (clock), .D
       (n_112), .Q (active_out_down_levels[6]), .QB (UNCONNECTED5));
  DCBX1 \active_out_down_levels_reg[7] (.CLR (1'b1), .CLK (clock), .D
       (n_106), .Q (active_out_down_levels[7]), .QB (UNCONNECTED6));
  DCBX1 \active_out_up_levels_reg[0] (.CLR (1'b1), .CLK (clock), .D
       (n_105), .Q (active_out_up_levels[0]), .QB (n_225));
  DCBX1 \active_out_up_levels_reg[1] (.CLR (1'b1), .CLK (clock), .D
       (n_104), .Q (active_out_up_levels[1]), .QB (UNCONNECTED7));
  DCBX1 \active_out_up_levels_reg[2] (.CLR (1'b1), .CLK (clock), .D
       (n_103), .Q (active_out_up_levels[2]), .QB (UNCONNECTED8));
  DCBX1 \active_out_up_levels_reg[3] (.CLR (1'b1), .CLK (clock), .D
       (n_102), .Q (active_out_up_levels[3]), .QB (UNCONNECTED9));
  DCBX1 \active_out_up_levels_reg[4] (.CLR (1'b1), .CLK (clock), .D
       (n_115), .Q (active_out_up_levels[4]), .QB (UNCONNECTED10));
  DCBX1 \active_out_up_levels_reg[5] (.CLR (1'b1), .CLK (clock), .D
       (n_114), .Q (active_out_up_levels[5]), .QB (UNCONNECTED11));
  DCBX1 \active_out_up_levels_reg[6] (.CLR (1'b1), .CLK (clock), .D
       (n_113), .Q (active_out_up_levels[6]), .QB (UNCONNECTED12));
  DCBX1 \buttons_state_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_205),
       .Q (UNCONNECTED13), .QB (buttons_state[0]));
  DCBX1 \buttons_state_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_207),
       .Q (UNCONNECTED14), .QB (buttons_state[1]));
  DCBX1 \buttons_state_reg[2] (.CLR (1'b1), .CLK (clock), .D (n_210),
       .Q (UNCONNECTED15), .QB (buttons_state[2]));
  DCBX1 \buttons_state_reg[3] (.CLR (1'b1), .CLK (clock), .D (n_209),
       .Q (UNCONNECTED16), .QB (buttons_state[3]));
  DCBX1 \buttons_state_reg[4] (.CLR (1'b1), .CLK (clock), .D (n_208),
       .Q (UNCONNECTED17), .QB (buttons_state[4]));
  DCBX1 \buttons_state_reg[5] (.CLR (1'b1), .CLK (clock), .D (n_211),
       .Q (UNCONNECTED18), .QB (buttons_state[5]));
  DCBX1 \buttons_state_reg[6] (.CLR (1'b1), .CLK (clock), .D (n_206),
       .Q (UNCONNECTED19), .QB (buttons_state[6]));
  DCBX1 \buttons_state_reg[7] (.CLR (1'b1), .CLK (clock), .D (n_204),
       .Q (UNCONNECTED20), .QB (buttons_state[7]));
  DCBX1 \l_btn_in_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_50), .Q
       (UNCONNECTED21), .QB (l_btn_in[0]));
  DCBX1 \l_btn_in_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_46), .Q
       (UNCONNECTED22), .QB (l_btn_in[1]));
  DCBX1 \l_btn_in_reg[2] (.CLR (1'b1), .CLK (clock), .D (n_48), .Q
       (UNCONNECTED23), .QB (l_btn_in[2]));
  DCBX1 \l_btn_in_reg[3] (.CLR (1'b1), .CLK (clock), .D (n_44), .Q
       (UNCONNECTED24), .QB (l_btn_in[3]));
  DCBX1 \l_btn_in_reg[4] (.CLR (1'b1), .CLK (clock), .D (n_43), .Q
       (UNCONNECTED25), .QB (l_btn_in[4]));
  DCBX1 \l_btn_in_reg[5] (.CLR (1'b1), .CLK (clock), .D (n_47), .Q
       (UNCONNECTED26), .QB (l_btn_in[5]));
  DCBX1 \l_btn_in_reg[6] (.CLR (1'b1), .CLK (clock), .D (n_49), .Q
       (UNCONNECTED27), .QB (l_btn_in[6]));
  DCBX1 \l_btn_in_reg[7] (.CLR (1'b1), .CLK (clock), .D (n_45), .Q
       (UNCONNECTED28), .QB (l_btn_in[7]));
  DCBX1 \l_inactivate_in_levels_reg[0] (.CLR (1'b1), .CLK (clock), .D
       (n_32), .Q (UNCONNECTED29), .QB (l_inactivate_in_levels[0]));
  DCBX1 \l_inactivate_in_levels_reg[1] (.CLR (1'b1), .CLK (clock), .D
       (n_30), .Q (UNCONNECTED30), .QB (l_inactivate_in_levels[1]));
  DCBX1 \l_inactivate_in_levels_reg[2] (.CLR (1'b1), .CLK (clock), .D
       (n_28), .Q (UNCONNECTED31), .QB (l_inactivate_in_levels[2]));
  DCBX1 \l_inactivate_in_levels_reg[3] (.CLR (1'b1), .CLK (clock), .D
       (n_31), .Q (UNCONNECTED32), .QB (l_inactivate_in_levels[3]));
  DCBX1 \l_inactivate_in_levels_reg[4] (.CLR (1'b1), .CLK (clock), .D
       (n_27), .Q (UNCONNECTED33), .QB (l_inactivate_in_levels[4]));
  DCBX1 \l_inactivate_in_levels_reg[5] (.CLR (1'b1), .CLK (clock), .D
       (n_34), .Q (UNCONNECTED34), .QB (l_inactivate_in_levels[5]));
  DCBX1 \l_inactivate_in_levels_reg[6] (.CLR (1'b1), .CLK (clock), .D
       (n_29), .Q (UNCONNECTED35), .QB (l_inactivate_in_levels[6]));
  DCBX1 \l_inactivate_in_levels_reg[7] (.CLR (1'b1), .CLK (clock), .D
       (n_33), .Q (UNCONNECTED36), .QB (l_inactivate_in_levels[7]));
  NAND2X1 g5384(.A (an_reset), .B (n_203), .Y (n_211));
  NAND2X1 g5385(.A (an_reset), .B (n_202), .Y (n_210));
  NAND2X1 g5386(.A (an_reset), .B (n_201), .Y (n_209));
  NAND2X1 g5387(.A (an_reset), .B (n_200), .Y (n_208));
  NAND2X1 g5388(.A (an_reset), .B (n_199), .Y (n_207));
  NAND2X1 g5389(.A (an_reset), .B (n_198), .Y (n_206));
  NAND2X1 g5390(.A (an_reset), .B (n_197), .Y (n_205));
  NAND2X1 g5391(.A (an_reset), .B (n_196), .Y (n_204));
  AOI21X1 g5392(.A (n_127), .B (inactivate_in_levels[5]), .C (n_183),
       .Y (n_203));
  AOI21X1 g5393(.A (n_128), .B (inactivate_in_levels[2]), .C (n_184),
       .Y (n_202));
  AOI21X1 g5394(.A (n_126), .B (inactivate_in_levels[3]), .C (n_181),
       .Y (n_201));
  AOI21X1 g5395(.A (n_125), .B (inactivate_in_levels[4]), .C (n_182),
       .Y (n_200));
  AOI21X1 g5396(.A (n_130), .B (inactivate_in_levels[1]), .C (n_187),
       .Y (n_199));
  AOI21X1 g5397(.A (n_129), .B (inactivate_in_levels[6]), .C (n_180),
       .Y (n_198));
  AOI21X1 g5398(.A (n_131), .B (inactivate_out_up_levels[0]), .C
       (n_185), .Y (n_197));
  AOI21X1 g5399(.A (n_124), .B (inactivate_out_down_levels[7]), .C
       (n_186), .Y (n_196));
  OAI22X1 g5400(.A (n_174), .B (n_8), .C (n_35), .D (n_146), .Y
       (n_195));
  OAI22X1 g5401(.A (n_173), .B (n_8), .C (n_35), .D (n_150), .Y
       (n_194));
  OAI22X1 g5402(.A (n_178), .B (n_8), .C (n_35), .D (n_149), .Y
       (n_193));
  OAI22X1 g5403(.A (n_179), .B (n_8), .C (n_35), .D (n_148), .Y
       (n_192));
  OAI22X1 g5404(.A (n_177), .B (n_8), .C (n_35), .D (n_143), .Y
       (n_191));
  OAI22X1 g5405(.A (n_176), .B (n_8), .C (n_35), .D (n_147), .Y
       (n_190));
  OAI22X1 g5406(.A (n_175), .B (n_8), .C (n_35), .D (n_145), .Y
       (n_189));
  OAI22X1 g5407(.A (n_172), .B (n_8), .C (n_35), .D (n_144), .Y
       (n_188));
  OAI22X1 g5408(.A (n_161), .B (buttons_state[1]), .C (n_154), .D
       (inactivate_in_levels[1]), .Y (n_187));
  OAI22X1 g5409(.A (n_159), .B (buttons_state[7]), .C (n_133), .D
       (inactivate_out_down_levels[7]), .Y (n_186));
  OAI22X1 g5410(.A (n_169), .B (buttons_state[0]), .C (n_153), .D
       (inactivate_out_up_levels[0]), .Y (n_185));
  OAI22X1 g5411(.A (n_163), .B (buttons_state[2]), .C (n_155), .D
       (inactivate_in_levels[2]), .Y (n_184));
  OAI22X1 g5412(.A (n_171), .B (buttons_state[5]), .C (n_141), .D
       (inactivate_in_levels[5]), .Y (n_183));
  OAI22X1 g5413(.A (n_167), .B (buttons_state[4]), .C (n_151), .D
       (inactivate_in_levels[4]), .Y (n_182));
  OAI22X1 g5414(.A (n_157), .B (buttons_state[3]), .C (n_152), .D
       (inactivate_in_levels[3]), .Y (n_181));
  OAI22X1 g5415(.A (n_165), .B (buttons_state[6]), .C (n_140), .D
       (inactivate_in_levels[6]), .Y (n_180));
  NAND2X1 g5416(.A (active_in_levels[5]), .B (n_170), .Y (n_179));
  NAND2X1 g5417(.A (active_in_levels[4]), .B (n_166), .Y (n_178));
  NAND2X1 g5418(.A (active_in_levels[0]), .B (n_168), .Y (n_177));
  NAND2X1 g5419(.A (active_in_levels[6]), .B (n_164), .Y (n_176));
  NAND2X1 g5420(.A (active_in_levels[2]), .B (n_162), .Y (n_175));
  NAND2X1 g5421(.A (active_in_levels[1]), .B (n_160), .Y (n_174));
  NAND2X1 g5422(.A (active_in_levels[7]), .B (n_158), .Y (n_173));
  NAND2X1 g5423(.A (active_in_levels[3]), .B (n_156), .Y (n_172));
  INVX2 g5424(.A (n_170), .Y (n_171));
  INVX2 g5425(.A (n_168), .Y (n_169));
  INVX2 g5426(.A (n_166), .Y (n_167));
  INVX2 g5427(.A (n_164), .Y (n_165));
  MUX2NX1 g5428(.A (n_122), .B (l_inactivate_in_levels[5]), .S
       (inactivate_in_levels[5]), .Y (n_170));
  MUX2NX1 g5429(.A (n_116), .B (l_inactivate_in_levels[0]), .S
       (inactivate_out_up_levels[0]), .Y (n_168));
  MUX2NX1 g5430(.A (n_117), .B (l_inactivate_in_levels[4]), .S
       (inactivate_in_levels[4]), .Y (n_166));
  MUX2NX1 g5431(.A (n_123), .B (l_inactivate_in_levels[6]), .S
       (inactivate_in_levels[6]), .Y (n_164));
  INVX2 g5432(.A (n_162), .Y (n_163));
  INVX2 g5433(.A (n_160), .Y (n_161));
  INVX2 g5434(.A (n_158), .Y (n_159));
  INVX2 g5435(.A (n_156), .Y (n_157));
  MUX2NX1 g5436(.A (n_119), .B (l_inactivate_in_levels[2]), .S
       (inactivate_in_levels[2]), .Y (n_162));
  MUX2NX1 g5437(.A (n_120), .B (l_inactivate_in_levels[1]), .S
       (inactivate_in_levels[1]), .Y (n_160));
  MUX2NX1 g5438(.A (n_118), .B (l_inactivate_in_levels[7]), .S
       (inactivate_out_down_levels[7]), .Y (n_158));
  MUX2NX1 g5439(.A (n_121), .B (l_inactivate_in_levels[3]), .S
       (inactivate_in_levels[3]), .Y (n_156));
  NAND2X1 g5440(.A (buttons_state[2]), .B (n_119), .Y (n_155));
  NAND2X1 g5441(.A (buttons_state[1]), .B (n_120), .Y (n_154));
  NAND2X1 g5442(.A (buttons_state[0]), .B (n_116), .Y (n_153));
  NAND2X1 g5443(.A (buttons_state[3]), .B (n_121), .Y (n_152));
  NAND2X1 g5444(.A (buttons_state[4]), .B (n_117), .Y (n_151));
  INVX2 g5459(.A (n_142), .Y (n_150));
  INVX2 g5460(.A (n_139), .Y (n_149));
  INVX2 g5461(.A (n_138), .Y (n_148));
  INVX2 g5462(.A (n_137), .Y (n_147));
  INVX2 g5463(.A (n_136), .Y (n_146));
  INVX2 g5464(.A (n_135), .Y (n_145));
  INVX2 g5465(.A (n_134), .Y (n_144));
  INVX2 g5466(.A (n_132), .Y (n_143));
  NOR3X1 g5467(.A (buttons_state[7]), .B
       (inactivate_out_down_levels[7]), .C (n_101), .Y (n_142));
  NAND2X1 g5468(.A (buttons_state[5]), .B (n_122), .Y (n_141));
  NAND2X1 g5469(.A (buttons_state[6]), .B (n_123), .Y (n_140));
  NOR3X1 g5470(.A (buttons_state[4]), .B (inactivate_in_levels[4]), .C
       (n_97), .Y (n_139));
  NOR3X1 g5471(.A (buttons_state[5]), .B (inactivate_in_levels[5]), .C
       (n_100), .Y (n_138));
  NOR3X1 g5472(.A (buttons_state[6]), .B (inactivate_in_levels[6]), .C
       (n_98), .Y (n_137));
  NOR3X1 g5473(.A (buttons_state[1]), .B (inactivate_in_levels[1]), .C
       (n_96), .Y (n_136));
  NOR3X1 g5474(.A (buttons_state[2]), .B (inactivate_in_levels[2]), .C
       (n_95), .Y (n_135));
  NOR3X1 g5475(.A (buttons_state[3]), .B (inactivate_in_levels[3]), .C
       (n_86), .Y (n_134));
  NAND2X1 g5476(.A (buttons_state[7]), .B (n_118), .Y (n_133));
  NOR3X1 g5477(.A (buttons_state[0]), .B (inactivate_out_up_levels[0]),
       .C (n_99), .Y (n_132));
  MUX2NX1 g5478(.A (active_in_levels[0]), .B (n_93), .S
       (buttons_state[0]), .Y (n_131));
  MUX2NX1 g5479(.A (active_in_levels[1]), .B (n_92), .S
       (buttons_state[1]), .Y (n_130));
  MUX2NX1 g5480(.A (active_in_levels[6]), .B (n_91), .S
       (buttons_state[6]), .Y (n_129));
  MUX2NX1 g5481(.A (active_in_levels[2]), .B (n_94), .S
       (buttons_state[2]), .Y (n_128));
  MUX2NX1 g5482(.A (active_in_levels[5]), .B (n_87), .S
       (buttons_state[5]), .Y (n_127));
  MUX2NX1 g5483(.A (active_in_levels[3]), .B (n_89), .S
       (buttons_state[3]), .Y (n_126));
  MUX2NX1 g5484(.A (active_in_levels[4]), .B (n_88), .S
       (buttons_state[4]), .Y (n_125));
  MUX2NX1 g5485(.A (active_in_levels[7]), .B (n_90), .S
       (buttons_state[7]), .Y (n_124));
  OAI21X1 g5486(.A (n_51), .B (inactivate_out_up_levels[4]), .C (n_84),
       .Y (n_115));
  OAI21X1 g5487(.A (n_57), .B (inactivate_out_up_levels[5]), .C (n_83),
       .Y (n_114));
  OAI21X1 g5488(.A (n_56), .B (inactivate_out_up_levels[6]), .C (n_82),
       .Y (n_113));
  NOR2X1 g5489(.A (buttons_block), .B (n_98), .Y (n_123));
  NOR2X1 g5490(.A (buttons_block), .B (n_100), .Y (n_122));
  NOR2X1 g5491(.A (buttons_block), .B (n_86), .Y (n_121));
  NOR2X1 g5492(.A (buttons_block), .B (n_96), .Y (n_120));
  NOR2X1 g5493(.A (buttons_block), .B (n_95), .Y (n_119));
  NOR2X1 g5494(.A (buttons_block), .B (n_101), .Y (n_118));
  NOR2X1 g5495(.A (buttons_block), .B (n_97), .Y (n_117));
  NOR2X1 g5496(.A (buttons_block), .B (n_99), .Y (n_116));
  OAI21X1 g5497(.A (n_39), .B (inactivate_out_down_levels[6]), .C
       (n_76), .Y (n_112));
  OAI21X1 g5498(.A (n_52), .B (inactivate_out_down_levels[2]), .C
       (n_80), .Y (n_111));
  OAI21X1 g5499(.A (n_36), .B (inactivate_out_down_levels[3]), .C
       (n_79), .Y (n_110));
  OAI21X1 g5500(.A (n_55), .B (inactivate_out_down_levels[4]), .C
       (n_85), .Y (n_109));
  OAI21X1 g5501(.A (n_37), .B (inactivate_out_down_levels[5]), .C
       (n_77), .Y (n_108));
  OAI21X1 g5502(.A (n_53), .B (inactivate_out_down_levels[1]), .C
       (n_81), .Y (n_107));
  OAI21X1 g5503(.A (n_42), .B (inactivate_out_down_levels[7]), .C
       (n_75), .Y (n_106));
  OAI21X1 g5504(.A (n_38), .B (inactivate_out_up_levels[0]), .C (n_74),
       .Y (n_105));
  OAI21X1 g5505(.A (n_40), .B (inactivate_out_up_levels[1]), .C (n_73),
       .Y (n_104));
  OAI21X1 g5506(.A (n_54), .B (inactivate_out_up_levels[2]), .C (n_72),
       .Y (n_103));
  OAI21X1 g5507(.A (n_41), .B (inactivate_out_up_levels[3]), .C (n_78),
       .Y (n_102));
  NAND2X1 g5508(.A (l_inactivate_in_levels[2]), .B
       (active_in_levels[2]), .Y (n_94));
  NAND2X1 g5509(.A (l_inactivate_in_levels[0]), .B
       (active_in_levels[0]), .Y (n_93));
  NAND2X1 g5510(.A (l_inactivate_in_levels[1]), .B
       (active_in_levels[1]), .Y (n_92));
  NAND2X1 g5511(.A (l_inactivate_in_levels[6]), .B
       (active_in_levels[6]), .Y (n_91));
  NAND2X1 g5512(.A (l_inactivate_in_levels[7]), .B
       (active_in_levels[7]), .Y (n_90));
  NAND2X1 g5513(.A (l_inactivate_in_levels[3]), .B
       (active_in_levels[3]), .Y (n_89));
  NAND2X1 g5514(.A (l_inactivate_in_levels[4]), .B
       (active_in_levels[4]), .Y (n_88));
  NAND2X1 g5515(.A (l_inactivate_in_levels[5]), .B
       (active_in_levels[5]), .Y (n_87));
  NAND2X1 g5516(.A (l_btn_in[7]), .B (btn_in[7]), .Y (n_101));
  NAND2X1 g5517(.A (l_btn_in[5]), .B (btn_in[5]), .Y (n_100));
  NAND2X1 g5518(.A (l_btn_in[0]), .B (btn_in[0]), .Y (n_99));
  NAND2X1 g5519(.A (l_btn_in[6]), .B (btn_in[6]), .Y (n_98));
  NAND2X1 g5520(.A (l_btn_in[4]), .B (btn_in[4]), .Y (n_97));
  NAND2X1 g5521(.A (l_btn_in[1]), .B (btn_in[1]), .Y (n_96));
  NAND2X1 g5522(.A (l_btn_in[2]), .B (btn_in[2]), .Y (n_95));
  NAND2X1 g5523(.A (btn_down_out[4]), .B (n_63), .Y (n_85));
  NAND2X1 g5524(.A (btn_up_out[4]), .B (n_70), .Y (n_84));
  NAND2X1 g5525(.A (btn_up_out[5]), .B (n_69), .Y (n_83));
  NAND2X1 g5526(.A (btn_up_out[6]), .B (n_68), .Y (n_82));
  NAND2X1 g5527(.A (btn_down_out[1]), .B (n_66), .Y (n_81));
  NAND2X1 g5528(.A (btn_down_out[2]), .B (n_65), .Y (n_80));
  NAND2X1 g5529(.A (btn_down_out[3]), .B (n_71), .Y (n_79));
  NAND2X1 g5530(.A (btn_up_out[3]), .B (n_67), .Y (n_78));
  NAND2X1 g5531(.A (btn_down_out[5]), .B (n_62), .Y (n_77));
  NAND2X1 g5532(.A (btn_down_out[6]), .B (n_61), .Y (n_76));
  NAND2X1 g5533(.A (btn_down_out[7]), .B (n_60), .Y (n_75));
  NAND2X1 g5534(.A (btn_up_out[0]), .B (n_59), .Y (n_74));
  NAND2X1 g5535(.A (btn_up_out[1]), .B (n_58), .Y (n_73));
  NAND2X1 g5536(.A (btn_up_out[2]), .B (n_64), .Y (n_72));
  NAND2X1 g5537(.A (l_btn_in[3]), .B (btn_in[3]), .Y (n_86));
  NAND2X1 g5553(.A (n_36), .B (n_35), .Y (n_71));
  NAND2X1 g5554(.A (n_51), .B (n_35), .Y (n_70));
  NAND2X1 g5555(.A (n_57), .B (n_35), .Y (n_69));
  NAND2X1 g5556(.A (n_56), .B (n_35), .Y (n_68));
  NAND2X1 g5557(.A (n_41), .B (n_35), .Y (n_67));
  NAND2X1 g5558(.A (n_53), .B (n_35), .Y (n_66));
  NAND2X1 g5559(.A (n_52), .B (n_35), .Y (n_65));
  NAND2X1 g5560(.A (n_54), .B (n_35), .Y (n_64));
  NAND2X1 g5561(.A (n_55), .B (n_35), .Y (n_63));
  NAND2X1 g5562(.A (n_37), .B (n_35), .Y (n_62));
  NAND2X1 g5563(.A (n_39), .B (n_35), .Y (n_61));
  NAND2X1 g5564(.A (n_42), .B (n_35), .Y (n_60));
  NAND2X1 g5565(.A (n_38), .B (n_35), .Y (n_59));
  NAND2X1 g5566(.A (n_40), .B (n_35), .Y (n_58));
  NOR2X1 g5568(.A (n_16), .B (n_8), .Y (n_50));
  NOR2X1 g5569(.A (n_24), .B (n_8), .Y (n_49));
  NOR2X1 g5570(.A (n_15), .B (n_8), .Y (n_48));
  NOR2X1 g5571(.A (n_25), .B (n_8), .Y (n_47));
  NOR2X1 g5572(.A (n_23), .B (n_8), .Y (n_46));
  NOR2X1 g5573(.A (n_22), .B (n_8), .Y (n_45));
  NOR2X1 g5574(.A (n_14), .B (n_8), .Y (n_44));
  NOR2X1 g5575(.A (n_26), .B (n_8), .Y (n_43));
  NAND2X1 g5576(.A (active_out_up_levels[5]), .B (an_reset), .Y (n_57));
  NAND2X1 g5577(.A (active_out_up_levels[6]), .B (an_reset), .Y (n_56));
  NAND2X1 g5578(.A (active_out_down_levels[4]), .B (an_reset), .Y
       (n_55));
  NAND2X1 g5579(.A (active_out_up_levels[2]), .B (an_reset), .Y (n_54));
  NAND2X1 g5580(.A (active_out_down_levels[1]), .B (an_reset), .Y
       (n_53));
  NAND2X1 g5581(.A (active_out_down_levels[2]), .B (an_reset), .Y
       (n_52));
  NAND2X1 g5582(.A (active_out_up_levels[4]), .B (an_reset), .Y (n_51));
  NOR2X1 g5583(.A (n_10), .B (n_8), .Y (n_34));
  NOR2X1 g5584(.A (n_9), .B (n_8), .Y (n_33));
  NOR2X1 g5585(.A (n_18), .B (n_8), .Y (n_32));
  NOR2X1 g5586(.A (n_19), .B (n_8), .Y (n_31));
  NOR2X1 g5587(.A (n_20), .B (n_8), .Y (n_30));
  NOR2X1 g5588(.A (n_11), .B (n_8), .Y (n_29));
  NOR2X1 g5589(.A (n_13), .B (n_8), .Y (n_28));
  NOR2X1 g5590(.A (n_12), .B (n_8), .Y (n_27));
  NAND2X1 g5591(.A (active_out_down_levels[7]), .B (an_reset), .Y
       (n_42));
  NAND2X1 g5592(.A (active_out_up_levels[3]), .B (an_reset), .Y (n_41));
  NAND2X1 g5593(.A (active_out_up_levels[1]), .B (an_reset), .Y (n_40));
  NAND2X1 g5594(.A (active_out_down_levels[6]), .B (an_reset), .Y
       (n_39));
  NAND2X1 g5595(.A (active_out_up_levels[0]), .B (an_reset), .Y (n_38));
  NAND2X1 g5596(.A (active_out_down_levels[5]), .B (an_reset), .Y
       (n_37));
  NAND2X1 g5597(.A (active_out_down_levels[3]), .B (an_reset), .Y
       (n_36));
  NAND2X2 g5598(.A (an_reset), .B (n_17), .Y (n_35));
  INVX2 g5599(.A (btn_in[4]), .Y (n_26));
  INVX2 g5600(.A (btn_in[5]), .Y (n_25));
  INVX2 g5601(.A (btn_in[6]), .Y (n_24));
  INVX2 g5602(.A (btn_in[1]), .Y (n_23));
  INVX2 g5603(.A (btn_in[7]), .Y (n_22));
  INVX2 g5611(.A (inactivate_in_levels[1]), .Y (n_20));
  INVX2 g5612(.A (inactivate_in_levels[3]), .Y (n_19));
  INVX2 g5613(.A (inactivate_out_up_levels[0]), .Y (n_18));
  INVX2 g5614(.A (buttons_block), .Y (n_17));
  INVX2 g5615(.A (btn_in[0]), .Y (n_16));
  INVX2 g5616(.A (btn_in[2]), .Y (n_15));
  INVX2 g5617(.A (btn_in[3]), .Y (n_14));
  INVX2 g5626(.A (inactivate_in_levels[2]), .Y (n_13));
  INVX2 g5627(.A (inactivate_in_levels[4]), .Y (n_12));
  INVX2 g5628(.A (inactivate_in_levels[6]), .Y (n_11));
  INVX2 g5629(.A (inactivate_in_levels[5]), .Y (n_10));
  INVX2 g5630(.A (inactivate_out_down_levels[7]), .Y (n_9));
  INVX2 g5631(.A (an_reset), .Y (n_8));
endmodule

module elevator(clock, an_reset, buttons_block, open_btn, close_btn,
     overload, bell, sensor_up, sensor_down, sensor_inside,
     sensor_door, btn_in, btn_up_out, btn_down_out, engine, door,
     direction, bell_out, level_display);
  input clock, an_reset, buttons_block, open_btn, close_btn, overload,
       bell, sensor_up, sensor_down, sensor_inside;
  input [1:0] sensor_door;
  input [7:0] btn_in;
  input [6:0] btn_up_out;
  input [7:1] btn_down_out;
  output [1:0] engine, door;
  output direction, bell_out;
  output [3:0] level_display;
  wire clock, an_reset, buttons_block, open_btn, close_btn, overload,
       bell, sensor_up, sensor_down, sensor_inside;
  wire [1:0] sensor_door;
  wire [7:0] btn_in;
  wire [6:0] btn_up_out;
  wire [7:1] btn_down_out;
  wire [1:0] engine, door;
  wire direction, bell_out;
  wire [3:0] level_display;
  wire [7:0] inactivate_in_levels;
  wire [6:0] inactivate_out_up_levels;
  wire [7:1] inactivate_out_down_levels;
  wire [7:0] active_in_levels;
  wire [6:0] active_out_up_levels;
  wire [7:1] active_out_down_levels;
  wire [4:0] state;
  wire [15:0] counter;
  wire [1:0] i_engine;
  wire [4:0] saved_state;
  wire UNCONNECTED37, UNCONNECTED38, UNCONNECTED39, UNCONNECTED40,
       UNCONNECTED41, UNCONNECTED42, UNCONNECTED43, UNCONNECTED44;
  wire UNCONNECTED45, UNCONNECTED46, UNCONNECTED47, UNCONNECTED48,
       UNCONNECTED49, UNCONNECTED50, UNCONNECTED51, UNCONNECTED52;
  wire UNCONNECTED53, UNCONNECTED54, UNCONNECTED55, UNCONNECTED56,
       UNCONNECTED57, UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, closing;
  wire i_direction, letout, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_68, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_274;
  wire n_275, n_276, n_277, n_278, n_280, n_281, n_282, n_283;
  wire n_284, n_285, n_286, n_287, n_288, n_289, n_290, n_291;
  wire n_292, n_293, n_294, n_295, n_296, n_297, n_298, n_299;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_318, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_334, n_335, n_336, n_337, n_338, n_339, n_340;
  wire n_341, n_342, n_343, n_344, n_345, n_346, n_347, n_348;
  wire n_349, n_350, n_351, n_352, n_353, n_355, n_356, n_357;
  wire n_358, n_359, n_360, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_369, n_370, n_371, n_372, n_373, n_375;
  wire n_376, n_377, n_378, n_379, n_380, n_381, n_382, n_383;
  wire n_384, n_385, n_386, n_387, n_388, n_389, n_390, n_391;
  wire n_392, n_393, n_394, n_396, n_397, n_398, n_399, n_400;
  wire n_401, n_402, n_403, n_404, n_405, n_406, n_408, n_409;
  wire n_410, n_411, n_412, n_413, n_414, n_415, n_416, n_417;
  wire n_418, n_420, n_421, n_422, n_423, n_424, n_425, n_426;
  wire n_427, n_428, n_429, n_430, n_431, n_433, n_434, n_435;
  wire n_436, n_437, n_438, n_439, n_440, n_441, n_442, n_443;
  wire n_444, n_445, n_447, n_448, n_450, n_451, n_452, n_453;
  wire n_454, n_455, n_456, n_457, n_458, n_459, n_460, n_462;
  wire n_463, n_464, n_465, n_466, n_467, n_468, n_469, n_470;
  wire n_471, n_473, n_474, n_475, n_476, n_477, n_478, n_479;
  wire n_480, n_481, n_482, n_483, n_484, n_485, n_486, n_487;
  wire n_488, n_489, n_490, n_491, n_492, n_493, n_494, n_495;
  wire n_496, n_497, n_498, n_499, n_500, n_501, n_502, n_503;
  wire n_504, n_505, n_507, n_508, n_509, n_510, n_511, n_512;
  wire n_513, n_514, n_515, n_516, n_517, n_518, n_519, n_520;
  wire n_521, n_522, n_523, n_524, n_525, n_527, n_529, n_531;
  wire n_532, n_533, n_534, n_535, n_536, n_537, n_538, n_539;
  wire n_540, n_541, n_542, n_544, n_545, n_546, n_547, n_548;
  wire n_549, n_550, n_551, n_552, n_553, n_554, n_555, n_557;
  wire n_558, n_559, n_560, n_561, n_562, n_563, n_564, n_565;
  wire n_566, n_567, n_568, n_569, n_571, n_572, n_573, n_574;
  wire n_575, n_576, n_577, n_579, n_580, n_581, n_582, n_583;
  wire n_584, n_585, n_586, n_588, n_589, n_590, n_592, n_593;
  wire n_594, n_595, n_596, n_597, n_598, n_599, n_600, n_601;
  wire n_602, n_603, n_605, n_606, n_607, n_608, n_609, n_610;
  wire n_611, n_612, n_613, n_614, n_615, n_616, n_617, n_618;
  wire n_619, n_620, n_621, n_622, n_623, n_624, n_625, n_626;
  wire n_627, n_628, n_629, n_630, n_631, n_632, n_633, n_634;
  wire n_636, n_637, n_638, n_639, n_640, n_641, n_642, n_643;
  wire n_644, n_645, n_646, n_647, n_648, n_649, n_650, n_651;
  wire n_652, n_653, n_654, n_655, n_656, n_657, n_658, n_659;
  wire n_661, n_662, n_663, n_664, n_665, n_666, n_667, n_668;
  wire n_669, n_670, n_671, n_672, n_673, n_674, n_675, n_676;
  wire n_679, n_680, n_681, n_682, n_683, n_684, n_685, n_686;
  wire n_687, n_688, n_689, n_690, n_692, n_694, n_695, n_697;
  wire n_698, n_700, n_701, n_702, n_703, n_704, n_705, n_706;
  wire n_707, n_708, n_709, n_710, n_711, n_712, n_713, n_714;
  wire n_715, n_716, n_717, n_718, n_719, n_720, n_721, n_723;
  wire n_724, n_725, n_726, n_727, n_729, n_730, n_731, n_732;
  wire n_733, n_734, n_735, n_736, n_737, n_738, n_739, n_741;
  wire n_742, n_743, n_744, n_745, n_746, n_747, n_748, n_749;
  wire n_750, n_751, n_752, n_753, n_754, n_755, n_756, n_757;
  wire n_758, n_759, n_760, n_762, n_763, n_764, n_765, n_766;
  wire n_767, n_768, n_769, n_770, n_771, n_773, n_774, n_775;
  wire n_776, n_777, n_778, n_779, n_780, n_781, n_782, n_783;
  wire n_784, n_785, n_786, n_787, n_789, n_790, n_791, n_792;
  wire n_793, n_794, n_795, n_796, n_797, n_798, n_799, n_800;
  wire n_801, n_802, n_803, n_804, n_805, n_807, n_808, n_809;
  wire n_810, n_811, n_812, n_813, n_816, n_818, n_819, n_820;
  wire n_821, n_822, n_823, n_824, n_825, n_826, n_827, n_829;
  wire n_831, n_832, n_833, n_834, n_835, n_836, n_837, n_838;
  wire n_839, n_840, n_841, n_842, n_844, n_845, n_846, n_847;
  wire n_848, n_849, n_850, n_852, n_853, n_854, n_855, n_856;
  wire n_857, n_859, n_860, n_861, n_863, n_864, n_865, n_866;
  wire n_867, n_868, n_869, n_870, n_871, n_872, n_873, n_874;
  wire n_875, n_876, n_877, n_878, n_879, n_880, n_881, n_887;
  wire n_889, n_892, n_893, n_894, n_895, n_896, n_897, n_899;
  wire n_900, n_902, n_903, n_907, n_908, n_909, n_910, n_911;
  wire n_912, n_913, n_914, n_915, n_916, n_917, n_918, n_919;
  wire n_920, n_964, n_966, n_967, n_968, n_969, n_971, n_974;
  wire n_975, n_976, n_977, n_990, n_991, n_992, n_993, n_994;
  wire n_995, n_996, n_997, n_998, n_999, n_1000, n_1001, n_1002;
  wire n_1003, n_1004, n_1005, n_1006, n_1007, n_1008, n_1009, n_1010;
  wire n_1011, n_1012, n_1013, n_1014, n_1015, n_1016, n_1017, n_1018;
  wire n_1019, n_1020, n_1021, n_1022, n_1023, n_1024, opening, reached;
  wire waiting;
  buttons_res buttons_inst(.clock (clock), .an_reset (an_reset),
       .buttons_block (buttons_block), .btn_in (btn_in), .btn_up_out
       (btn_up_out), .btn_down_out (btn_down_out),
       .inactivate_in_levels ({UNCONNECTED_HIER_Z0,
       inactivate_in_levels[6:1], UNCONNECTED_HIER_Z}),
       .inactivate_out_up_levels ({inactivate_out_up_levels[6:1],
       inactivate_in_levels[0]}), .inactivate_out_down_levels
       ({inactivate_in_levels[7], inactivate_out_down_levels[6:1]}),
       .active_in_levels (active_in_levels), .active_out_up_levels
       (active_out_up_levels), .active_out_down_levels
       (active_out_down_levels));
  NOR2X1 g19242(.A (letout), .B (n_902), .Y (n_909));
  NOR2X1 g19243(.A (n_907), .B (n_903), .Y (n_913));
  NOR2X1 g19244(.A (letout), .B (n_900), .Y (n_908));
  INVX2 g19246(.A (n_902), .Y (n_914));
  NOR2X1 g19247(.A (n_907), .B (n_899), .Y (n_911));
  NAND3X1 g19248(.A (n_966), .B (an_reset), .C (n_1024), .Y (n_902));
  NOR2X1 g19249(.A (n_907), .B (n_896), .Y (n_910));
  NOR2X1 g19250(.A (n_907), .B (n_897), .Y (n_912));
  INVX2 g19252(.A (n_900), .Y (n_915));
  NOR2X1 g19254(.A (letout), .B (n_895), .Y (n_903));
  NAND3X1 g19255(.A (n_969), .B (an_reset), .C (n_1024), .Y (n_900));
  NOR2X1 g19257(.A (letout), .B (n_894), .Y (n_899));
  NAND2X1 g19258(.A (n_967), .B (n_964), .Y (n_897));
  INVX2 g19259(.A (n_966), .Y (n_895));
  NAND2X1 g19260(.A (n_968), .B (n_971), .Y (n_896));
  NOR2X1 g19261(.A (state[3]), .B (n_893), .Y (n_966));
  DCBX1 bell_out_reg(.CLR (1'b1), .CLK (clock), .D (n_975), .Q
       (bell_out), .QB (UNCONNECTED37));
  NOR2X1 g19263(.A (n_917), .B (n_916), .Y (n_967));
  INVX2 g19264(.A (n_969), .Y (n_894));
  NAND2X1 g19265(.A (state[1]), .B (n_892), .Y (n_893));
  NOR2X1 g19266(.A (n_918), .B (n_919), .Y (n_968));
  NOR2X1 g19267(.A (n_920), .B (n_919), .Y (n_969));
  NOR2X2 g19268(.A (direction), .B (n_64), .Y (n_971));
  NAND2X1 g19269(.A (state[2]), .B (n_887), .Y (n_916));
  NAND2X1 g19270(.A (n_9), .B (n_887), .Y (n_919));
  NOR2X1 g19271(.A (state[4]), .B (n_889), .Y (n_892));
  NOR2X1 g19273(.A (n_60), .B (n_64), .Y (n_964));
  INVX2 g19274(.A (n_59), .Y (n_920));
  INVX2 g19275(.A (n_64), .Y (reached));
  NAND2X1 g19276(.A (state[2]), .B (state[0]), .Y (n_889));
  NOR2X1 g19277(.A (state[1]), .B (state[3]), .Y (n_59));
  NAND2X2 g19278(.A (sensor_down), .B (sensor_up), .Y (n_64));
  NAND2X1 g19280(.A (state[3]), .B (n_33), .Y (n_918));
  NOR2X1 g19281(.A (state[0]), .B (state[4]), .Y (n_887));
  NAND2X1 g19282(.A (state[3]), .B (state[1]), .Y (n_917));
  NAND2X2 g19283(.A (an_reset), .B (n_52), .Y (n_907));
  INVX2 g19285(.A (buttons_block), .Y (n_52));
  DCBX1 closing_reg(.CLR (1'b1), .CLK (clock), .D (n_398), .Q
       (UNCONNECTED38), .QB (closing));
  DCBX1 \counter_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_769), .Q
       (n_13), .QB (counter[0]));
  DCBX1 \counter_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_765), .Q
       (n_38), .QB (counter[1]));
  DCBX1 \counter_reg[2] (.CLR (1'b1), .CLK (clock), .D (n_763), .Q
       (n_10), .QB (n_5));
  DCBX1 \counter_reg[3] (.CLR (1'b1), .CLK (clock), .D (n_764), .Q
       (n_36), .QB (counter[3]));
  DCBX1 \counter_reg[4] (.CLR (1'b1), .CLK (clock), .D (n_793), .Q
       (n_35), .QB (counter[4]));
  DCBX1 \counter_reg[5] (.CLR (1'b1), .CLK (clock), .D (n_808), .Q
       (UNCONNECTED39), .QB (counter[5]));
  DCBX1 \counter_reg[6] (.CLR (1'b1), .CLK (clock), .D (n_822), .Q
       (UNCONNECTED40), .QB (counter[6]));
  DCBX1 \counter_reg[7] (.CLR (1'b1), .CLK (clock), .D (n_819), .Q
       (n_12), .QB (n_3));
  DCBX1 \counter_reg[8] (.CLR (1'b1), .CLK (clock), .D (n_833), .Q
       (n_15), .QB (counter[8]));
  DCBX1 \counter_reg[9] (.CLR (1'b1), .CLK (clock), .D (n_836), .Q
       (n_30), .QB (n_2));
  DCBX1 \counter_reg[10] (.CLR (1'b1), .CLK (clock), .D (n_844), .Q
       (n_39), .QB (counter[10]));
  DCBX1 \counter_reg[11] (.CLR (1'b1), .CLK (clock), .D (n_847), .Q
       (n_40), .QB (counter[11]));
  DCBX1 \counter_reg[12] (.CLR (1'b1), .CLK (clock), .D (n_856), .Q
       (n_31), .QB (counter[12]));
  DCBX1 \counter_reg[13] (.CLR (1'b1), .CLK (clock), .D (n_859), .Q
       (n_37), .QB (counter[13]));
  DCBX1 \counter_reg[14] (.CLR (1'b1), .CLK (clock), .D (n_977), .Q
       (n_14), .QB (counter[14]));
  DCBX1 \counter_reg[15] (.CLR (1'b1), .CLK (clock), .D (n_865), .Q
       (n_42), .QB (counter[15]));
  DCBX1 direction_reg(.CLR (1'b1), .CLK (clock), .D (n_872), .Q
       (direction), .QB (UNCONNECTED41));
  DCBX1 \door_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_436), .Q
       (door[0]), .QB (UNCONNECTED42));
  DCBX1 \door_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_493), .Q
       (door[1]), .QB (UNCONNECTED43));
  DCBX1 \engine_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_781), .Q
       (engine[0]), .QB (UNCONNECTED44));
  DCBX1 \engine_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_784), .Q
       (engine[1]), .QB (UNCONNECTED45));
  DCBX1 i_direction_reg(.CLR (1'b1), .CLK (clock), .D (n_650), .Q
       (UNCONNECTED46), .QB (i_direction));
  DCBX1 \i_engine_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_850), .Q
       (UNCONNECTED47), .QB (i_engine[0]));
  DCBX1 \i_engine_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_861), .Q
       (UNCONNECTED48), .QB (i_engine[1]));
  DCBX1 \inactivate_in_levels_reg[0] (.CLR (1'b1), .CLK (clock), .D
       (n_203), .Q (UNCONNECTED49), .QB (n_874));
  DCBX1 \inactivate_in_levels_reg[1] (.CLR (1'b1), .CLK (clock), .D
       (n_680), .Q (inactivate_in_levels[1]), .QB (n_875));
  DCBX1 \inactivate_in_levels_reg[2] (.CLR (1'b1), .CLK (clock), .D
       (n_714), .Q (inactivate_in_levels[2]), .QB (n_876));
  DCBX1 \inactivate_in_levels_reg[3] (.CLR (1'b1), .CLK (clock), .D
       (n_671), .Q (inactivate_in_levels[3]), .QB (n_877));
  DCBX1 \inactivate_in_levels_reg[4] (.CLR (1'b1), .CLK (clock), .D
       (n_689), .Q (inactivate_in_levels[4]), .QB (n_878));
  DCBX1 \inactivate_in_levels_reg[5] (.CLR (1'b1), .CLK (clock), .D
       (n_624), .Q (inactivate_in_levels[5]), .QB (n_879));
  DCBX1 \inactivate_in_levels_reg[6] (.CLR (1'b1), .CLK (clock), .D
       (n_704), .Q (inactivate_in_levels[6]), .QB (n_880));
  DCBX1 \inactivate_in_levels_reg[7] (.CLR (1'b1), .CLK (clock), .D
       (n_195), .Q (UNCONNECTED50), .QB (n_881));
  DCBX1 \inactivate_out_down_levels_reg[1] (.CLR (1'b1), .CLK (clock),
       .D (n_700), .Q (inactivate_out_down_levels[1]), .QB (n_19));
  DCBX1 \inactivate_out_down_levels_reg[2] (.CLR (1'b1), .CLK (clock),
       .D (n_686), .Q (inactivate_out_down_levels[2]), .QB (n_18));
  DCBX1 \inactivate_out_down_levels_reg[3] (.CLR (1'b1), .CLK (clock),
       .D (n_625), .Q (inactivate_out_down_levels[3]), .QB (n_20));
  DCBX1 \inactivate_out_down_levels_reg[4] (.CLR (1'b1), .CLK (clock),
       .D (n_652), .Q (inactivate_out_down_levels[4]), .QB (n_25));
  DCBX1 \inactivate_out_down_levels_reg[5] (.CLR (1'b1), .CLK (clock),
       .D (n_598), .Q (inactivate_out_down_levels[5]), .QB (n_45));
  DCBX1 \inactivate_out_down_levels_reg[6] (.CLR (1'b1), .CLK (clock),
       .D (n_532), .Q (inactivate_out_down_levels[6]), .QB (n_16));
  DCBX1 \inactivate_out_up_levels_reg[1] (.CLR (1'b1), .CLK (clock), .D
       (n_455), .Q (inactivate_out_up_levels[1]), .QB (n_23));
  DCBX1 \inactivate_out_up_levels_reg[2] (.CLR (1'b1), .CLK (clock), .D
       (n_567), .Q (inactivate_out_up_levels[2]), .QB (n_46));
  DCBX1 \inactivate_out_up_levels_reg[3] (.CLR (1'b1), .CLK (clock), .D
       (n_566), .Q (inactivate_out_up_levels[3]), .QB (n_44));
  DCBX1 \inactivate_out_up_levels_reg[4] (.CLR (1'b1), .CLK (clock), .D
       (n_623), .Q (inactivate_out_up_levels[4]), .QB (n_43));
  DCBX1 \inactivate_out_up_levels_reg[5] (.CLR (1'b1), .CLK (clock), .D
       (n_601), .Q (inactivate_out_up_levels[5]), .QB (n_24));
  DCBX1 \inactivate_out_up_levels_reg[6] (.CLR (1'b1), .CLK (clock), .D
       (n_687), .Q (inactivate_out_up_levels[6]), .QB (n_22));
  DCBX1 letout_reg(.CLR (1'b1), .CLK (clock), .D (n_712), .Q
       (UNCONNECTED51), .QB (n_873));
  DCBX1 \level_display_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_697),
       .Q (level_display[0]), .QB (UNCONNECTED52));
  DCBX1 \level_display_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_685),
       .Q (level_display[1]), .QB (UNCONNECTED53));
  DCBX1 \level_display_reg[2] (.CLR (1'b1), .CLK (clock), .D (n_695),
       .Q (level_display[2]), .QB (UNCONNECTED54));
  DCBX1 \level_display_reg[3] (.CLR (1'b1), .CLK (clock), .D (n_618),
       .Q (level_display[3]), .QB (UNCONNECTED55));
  DCBX1 opening_reg(.CLR (1'b1), .CLK (clock), .D (n_715), .Q (n_41),
       .QB (opening));
  DCBX1 \saved_state_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_864), .Q
       (n_17), .QB (saved_state[0]));
  DCBX1 \saved_state_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_846), .Q
       (n_21), .QB (saved_state[1]));
  DCBX1 \saved_state_reg[2] (.CLR (1'b1), .CLK (clock), .D (n_991), .Q
       (UNCONNECTED56), .QB (saved_state[2]));
  DCBX1 \saved_state_reg[3] (.CLR (1'b1), .CLK (clock), .D (n_780), .Q
       (UNCONNECTED57), .QB (saved_state[3]));
  DCBX1 \state_reg[0] (.CLR (1'b1), .CLK (clock), .D (n_852), .Q
       (state[0]), .QB (n_27));
  DCBX1 \state_reg[1] (.CLR (1'b1), .CLK (clock), .D (n_841), .Q
       (state[1]), .QB (n_33));
  DCBX1 \state_reg[2] (.CLR (1'b1), .CLK (clock), .D (n_995), .Q
       (state[2]), .QB (n_9));
  DCBX1 \state_reg[3] (.CLR (1'b1), .CLK (clock), .D (n_848), .Q
       (state[3]), .QB (n_28));
  DCBX1 \state_reg[4] (.CLR (1'b1), .CLK (clock), .D (n_759), .Q
       (state[4]), .QB (n_8));
  DCBX1 waiting_reg(.CLR (1'b1), .CLK (clock), .D (n_753), .Q (n_34),
       .QB (waiting));
  NAND2X1 g40799(.A (n_757), .B (n_871), .Y (n_872));
  AOI21X1 g40800(.A (n_868), .B (n_82), .C (n_870), .Y (n_871));
  OAI22X1 g40801(.A (n_869), .B (n_60), .C (n_631), .D (n_907), .Y
       (n_870));
  OAI21X1 g40802(.A (n_867), .B (buttons_block), .C (an_reset), .Y
       (n_869));
  AOI21X1 g40803(.A (n_568), .B (n_456), .C (n_867), .Y (n_868));
  AND3X1 g40804(.A (n_559), .B (n_529), .C (n_866), .Y (n_867));
  AND3X1 g40806(.A (n_386), .B (n_418), .C (n_863), .Y (n_866));
  OAI21X1 g40808(.A (n_860), .B (counter[15]), .C (n_845), .Y (n_865));
  NAND3X1 g40812(.A (n_757), .B (n_802), .C (n_854), .Y (n_864));
  NOR3X1 g40813(.A (n_1019), .B (n_1021), .C (n_855), .Y (n_863));
  NAND2X1 g40815(.A (n_737), .B (n_853), .Y (n_861));
  AOI21X1 g40817(.A (n_748), .B (counter[14]), .C (n_857), .Y (n_860));
  MUX2NX1 g40818(.A (n_849), .B (n_818), .S (counter[13]), .Y (n_859));
  MUX2X2 g40826(.A (n_838), .B (n_801), .S (counter[12]), .Y (n_856));
  NAND3X1 g40827(.A (n_525), .B (n_352), .C (n_834), .Y (n_855));
  AND3X1 g40828(.A (n_738), .B (n_750), .C (n_840), .Y (n_854));
  MUX2X2 g40829(.A (i_engine[1]), .B (n_842), .S (n_726), .Y (n_853));
  OAI21X1 g40831(.A (n_747), .B (n_37), .C (n_849), .Y (n_857));
  OAI21X1 g40832(.A (n_832), .B (n_50), .C (n_731), .Y (n_852));
  NAND2X1 g40834(.A (n_750), .B (n_839), .Y (n_850));
  NAND2X1 g40838(.A (n_701), .B (n_837), .Y (n_848));
  OAI21X1 g40839(.A (n_825), .B (counter[11]), .C (n_795), .Y (n_847));
  NAND3X1 g40840(.A (n_486), .B (n_771), .C (n_823), .Y (n_846));
  NAND3X1 g40841(.A (n_14), .B (n_37), .C (n_831), .Y (n_845));
  OAI22X1 g40842(.A (n_820), .B (counter[10]), .C (n_803), .D (n_2), .Y
       (n_844));
  AOI21X1 g40843(.A (n_748), .B (counter[12]), .C (n_838), .Y (n_849));
  NAND2X1 g40845(.A (n_141), .B (n_826), .Y (n_842));
  NAND2X1 g40846(.A (n_701), .B (n_829), .Y (n_841));
  NOR2X1 g40847(.A (n_786), .B (n_821), .Y (n_840));
  INVX2 g40850(.A (n_835), .Y (n_839));
  NOR2X1 g40851(.A (n_371), .B (n_827), .Y (n_837));
  MUX2NX1 g40852(.A (n_812), .B (n_791), .S (n_2), .Y (n_836));
  OAI21X1 g40853(.A (n_726), .B (i_engine[0]), .C (n_826), .Y (n_835));
  AOI21X1 g40854(.A (n_447), .B (letout), .C (n_824), .Y (n_834));
  OAI22X1 g40855(.A (n_809), .B (counter[8]), .C (n_790), .D (n_3), .Y
       (n_833));
  OAI21X1 g40856(.A (n_747), .B (n_40), .C (n_825), .Y (n_838));
  NAND3X1 g40857(.A (n_647), .B (n_721), .C (n_796), .Y (n_832));
  NOR2X1 g40858(.A (n_42), .B (n_818), .Y (n_831));
  NOR2X1 g40860(.A (n_561), .B (n_816), .Y (n_829));
  OAI21X1 g40862(.A (n_629), .B (n_76), .C (n_811), .Y (n_827));
  OAI21X1 g40864(.A (n_632), .B (n_522), .C (n_993), .Y (n_824));
  AND3X1 g40865(.A (n_737), .B (n_807), .C (n_802), .Y (n_823));
  OAI22X1 g40866(.A (n_794), .B (counter[6]), .C (n_773), .D (n_11), .Y
       (n_822));
  NAND3X1 g40867(.A (n_338), .B (n_766), .C (n_797), .Y (n_821));
  AOI21X1 g40868(.A (n_748), .B (n_2), .C (n_813), .Y (n_820));
  MUX2NX1 g40869(.A (n_800), .B (n_776), .S (n_3), .Y (n_819));
  AND3X1 g40870(.A (n_771), .B (n_805), .C (n_787), .Y (n_826));
  AOI21X1 g40871(.A (n_748), .B (n_86), .C (n_813), .Y (n_825));
  NAND3X1 g40873(.A (n_335), .B (n_647), .C (n_789), .Y (n_816));
  NAND2X1 g40875(.A (n_31), .B (n_801), .Y (n_818));
  INVX2 g40878(.A (n_813), .Y (n_812));
  AOI21X1 g40879(.A (n_50), .B (n_29), .C (n_804), .Y (n_811));
  OAI21X1 g40880(.A (n_754), .B (saved_state[2]), .C (n_798), .Y
       (n_810));
  AOI21X1 g40881(.A (n_748), .B (n_3), .C (n_799), .Y (n_809));
  MUX2X2 g40882(.A (n_785), .B (n_756), .S (n_11), .Y (n_808));
  OAI21X1 g40883(.A (n_747), .B (n_110), .C (n_800), .Y (n_813));
  AND3X1 g40884(.A (n_553), .B (n_733), .C (n_783), .Y (n_807));
  AOI21X1 g40886(.A (n_749), .B (n_574), .C (n_782), .Y (n_805));
  NAND3X1 g40887(.A (n_448), .B (n_405), .C (n_774), .Y (n_804));
  NAND2X1 g40888(.A (counter[10]), .B (n_792), .Y (n_803));
  INVX2 g40893(.A (n_800), .Y (n_799));
  AOI22X1 g40894(.A (n_392), .B (n_777), .C (n_327), .D (n_726), .Y
       (n_798));
  AOI21X1 g40895(.A (n_755), .B (n_17), .C (n_779), .Y (n_797));
  AND3X1 g40896(.A (n_222), .B (n_338), .C (n_767), .Y (n_796));
  NAND2X1 g40897(.A (n_139), .B (n_792), .Y (n_795));
  AOI21X1 g40898(.A (n_748), .B (n_11), .C (n_785), .Y (n_794));
  OAI22X1 g40899(.A (n_770), .B (counter[4]), .C (n_747), .D (n_260),
       .Y (n_793));
  NAND3X1 g40900(.A (n_106), .B (letout), .C (n_777), .Y (n_802));
  NOR3X1 g40901(.A (counter[11]), .B (n_86), .C (n_791), .Y (n_801));
  AOI21X1 g40902(.A (n_748), .B (n_112), .C (n_785), .Y (n_800));
  INVX2 g40903(.A (n_792), .Y (n_791));
  NAND2X1 g40904(.A (counter[8]), .B (n_775), .Y (n_790));
  AND3X1 g40905(.A (n_463), .B (n_706), .C (n_758), .Y (n_789));
  NOR2X1 g40907(.A (n_109), .B (n_776), .Y (n_792));
  INVX2 g40912(.A (n_786), .Y (n_787));
  OAI22X1 g40913(.A (n_762), .B (i_engine[1]), .C (n_745), .D (n_62),
       .Y (n_784));
  AOI22X1 g40914(.A (n_21), .B (n_755), .C (n_26), .D (n_736), .Y
       (n_783));
  OAI22X1 g40915(.A (n_760), .B (n_26), .C (n_727), .D (n_323), .Y
       (n_782));
  OAI22X1 g40916(.A (n_762), .B (i_engine[0]), .C (n_742), .D (n_62),
       .Y (n_781));
  OAI21X1 g40917(.A (n_754), .B (saved_state[3]), .C (n_727), .Y
       (n_780));
  OAI21X1 g40918(.A (n_755), .B (n_51), .C (n_730), .Y (n_779));
  OAI21X1 g40919(.A (n_727), .B (n_531), .C (n_778), .Y (n_786));
  OAI21X1 g40920(.A (n_747), .B (n_35), .C (n_770), .Y (n_785));
  INVX1 g40921(.A (n_776), .Y (n_775));
  AND3X1 g40922(.A (n_463), .B (n_637), .C (n_751), .Y (n_774));
  NAND2X1 g40923(.A (counter[6]), .B (n_756), .Y (n_773));
  NAND2X1 g40925(.A (n_967), .B (n_754), .Y (n_778));
  NOR2X1 g40926(.A (n_226), .B (n_755), .Y (n_777));
  NAND2X1 g40927(.A (n_111), .B (n_756), .Y (n_776));
  MUX2NX1 g40930(.A (n_717), .B (n_747), .S (counter[0]), .Y (n_769));
  AND3X1 g40931(.A (n_373), .B (n_337), .C (n_741), .Y (n_768));
  AOI21X1 g40932(.A (n_246), .B (n_169), .C (n_752), .Y (n_767));
  AOI22X1 g40933(.A (n_26), .B (n_735), .C (n_6), .D (n_301), .Y
       (n_766));
  OAI22X1 g40934(.A (n_747), .B (n_122), .C (n_717), .D (counter[1]),
       .Y (n_765));
  OAI22X1 g40935(.A (n_747), .B (n_223), .C (n_717), .D (counter[3]),
       .Y (n_764));
  OAI22X1 g40936(.A (n_747), .B (n_168), .C (n_717), .D (n_4), .Y
       (n_763));
  AOI21X1 g40937(.A (n_743), .B (n_60), .C (n_739), .Y (n_771));
  AOI21X1 g40938(.A (n_748), .B (n_194), .C (n_716), .Y (n_770));
  NOR2X1 g40940(.A (n_736), .B (n_735), .Y (n_760));
  NAND2X1 g40941(.A (n_605), .B (n_744), .Y (n_759));
  NOR2X1 g40942(.A (n_360), .B (n_734), .Y (n_758));
  NAND3X1 g40943(.A (n_82), .B (n_64), .C (n_729), .Y (n_762));
  INVX2 g40944(.A (n_755), .Y (n_754));
  OAI22X1 g40945(.A (n_724), .B (waiting), .C (n_0), .D
       (buttons_block), .Y (n_753));
  NAND3X1 g40946(.A (n_251), .B (n_448), .C (n_999), .Y (n_752));
  NAND2X1 g40947(.A (n_551), .B (n_749), .Y (n_757));
  NOR3X1 g40948(.A (counter[4]), .B (n_194), .C (n_747), .Y (n_756));
  OAI21X1 g40949(.A (n_723), .B (n_478), .C (n_82), .Y (n_755));
  INVX2 g40950(.A (n_746), .Y (n_751));
  INVX2 g40951(.A (n_748), .Y (n_747));
  OAI21X1 g40952(.A (n_720), .B (saved_state[3]), .C (n_616), .Y
       (n_746));
  NAND2X1 g40953(.A (engine[1]), .B (n_997), .Y (n_745));
  NOR2X1 g40954(.A (n_483), .B (n_725), .Y (n_744));
  NOR2X1 g40955(.A (n_263), .B (n_727), .Y (n_743));
  NAND2X1 g40956(.A (engine[0]), .B (n_997), .Y (n_742));
  NOR3X1 g40957(.A (n_492), .B (n_642), .C (n_713), .Y (n_741));
  NAND2X1 g40958(.A (n_309), .B (n_726), .Y (n_750));
  NOR2X1 g40959(.A (n_126), .B (n_727), .Y (n_749));
  AND3X1 g40960(.A (n_717), .B (n_655), .C (n_710), .Y (n_748));
  INVX2 g40962(.A (n_738), .Y (n_739));
  OAI22X1 g40963(.A (n_721), .B (saved_state[1]), .C (n_1024), .D
       (n_33), .Y (n_734));
  NAND3X1 g40964(.A (n_144), .B (n_488), .C (n_726), .Y (n_733));
  OAI22X1 g40965(.A (n_720), .B (saved_state[2]), .C (n_76), .D
       (n_268), .Y (n_732));
  AOI22X1 g40966(.A (n_17), .B (n_719), .C (state[0]), .D (n_50), .Y
       (n_731));
  OAI21X1 g40967(.A (n_102), .B (n_104), .C (n_726), .Y (n_730));
  NAND3X1 g40968(.A (n_225), .B (n_345), .C (n_726), .Y (n_738));
  NAND3X1 g40969(.A (n_252), .B (n_142), .C (n_726), .Y (n_737));
  AOI21X1 g40970(.A (n_265), .B (n_204), .C (n_727), .Y (n_736));
  AND3X1 g40971(.A (n_126), .B (n_296), .C (n_726), .Y (n_735));
  INVX2 g40972(.A (n_997), .Y (n_729));
  INVX2 g40977(.A (n_727), .Y (n_726));
  NAND3X1 g40978(.A (n_676), .B (n_679), .C (n_711), .Y (n_725));
  AOI21X1 g40979(.A (n_633), .B (n_705), .C (n_320), .Y (n_724));
  NAND2X1 g40980(.A (n_675), .B (n_718), .Y (n_723));
  OAI21X1 g40982(.A (n_702), .B (n_684), .C (n_82), .Y (n_727));
  INVX1 g40983(.A (n_720), .Y (n_719));
  NOR2X1 g40984(.A (n_509), .B (n_702), .Y (n_718));
  NOR2X1 g40987(.A (n_692), .B (n_709), .Y (n_721));
  NOR2X1 g40990(.A (n_709), .B (n_708), .Y (n_720));
  INVX2 g40991(.A (n_717), .Y (n_716));
  OAI22X1 g40992(.A (n_688), .B (opening), .C (n_81), .D (n_533), .Y
       (n_715));
  NAND2X1 g40993(.A (n_78), .B (n_1001), .Y (n_714));
  NAND2X1 g40995(.A (n_694), .B (n_577), .Y (n_713));
  NOR2X1 g40996(.A (n_62), .B (n_698), .Y (n_712));
  AOI21X1 g40997(.A (n_50), .B (state[4]), .C (n_707), .Y (n_711));
  AOI21X1 g40998(.A (n_269), .B (n_634), .C (n_708), .Y (n_710));
  AOI21X1 g40999(.A (an_reset), .B (n_690), .C (n_50), .Y (n_717));
  INVX2 g41000(.A (n_703), .Y (n_708));
  INVX2 g41001(.A (n_706), .Y (n_707));
  NAND2X1 g41003(.A (n_78), .B (n_1003), .Y (n_704));
  NAND2X1 g41008(.A (an_reset), .B (n_682), .Y (n_709));
  NAND2X1 g41009(.A (n_603), .B (n_692), .Y (n_703));
  NAND2X1 g41011(.A (n_602), .B (n_692), .Y (n_706));
  NOR2X1 g41012(.A (n_666), .B (n_684), .Y (n_705));
  NAND2X1 g41013(.A (n_78), .B (n_683), .Y (n_700));
  AOI22X1 g41015(.A (n_148), .B (n_674), .C (letout), .D (n_558), .Y
       (n_698));
  NAND3X1 g41016(.A (n_235), .B (n_232), .C (n_661), .Y (n_697));
  NAND3X1 g41018(.A (n_146), .B (n_187), .C (n_659), .Y (n_695));
  AOI22X1 g41019(.A (n_209), .B (n_670), .C (letout), .D (n_421), .Y
       (n_694));
  NAND3X1 g41021(.A (n_665), .B (n_517), .C (n_669), .Y (n_702));
  AOI21X1 g41022(.A (n_275), .B (n_620), .C (n_681), .Y (n_701));
  NOR2X1 g41024(.A (n_219), .B (n_664), .Y (n_690));
  NAND2X1 g41025(.A (n_78), .B (n_667), .Y (n_689));
  NOR2X1 g41026(.A (n_320), .B (n_672), .Y (n_688));
  NAND2X1 g41027(.A (n_78), .B (n_663), .Y (n_687));
  NAND2X1 g41028(.A (n_78), .B (n_656), .Y (n_686));
  NAND2X1 g41029(.A (n_146), .B (n_662), .Y (n_685));
  AOI21X1 g41031(.A (n_638), .B (n_476), .C (n_177), .Y (n_692));
  AOI22X1 g41032(.A (n_290), .B (n_1005), .C (n_61), .D (n_648), .Y
       (n_683));
  AOI21X1 g41033(.A (n_239), .B (n_646), .C (n_654), .Y (n_682));
  OAI22X1 g41034(.A (n_653), .B (n_173), .C (n_120), .D (n_417), .Y
       (n_681));
  OAI21X1 g41035(.A (n_640), .B (n_907), .C (n_370), .Y (n_680));
  AOI21X1 g41036(.A (an_reset), .B (n_261), .C (n_668), .Y (n_679));
  AOI22X1 g41039(.A (n_431), .B (n_289), .C (n_645), .D (n_239), .Y
       (n_676));
  OAI21X1 g41040(.A (n_508), .B (n_6), .C (n_675), .Y (n_684));
  AND3X1 g41041(.A (n_146), .B (n_284), .C (n_611), .Y (n_674));
  NOR2X1 g41042(.A (n_908), .B (n_651), .Y (n_673));
  AOI21X1 g41043(.A (n_634), .B (n_73), .C (n_478), .Y (n_672));
  NAND2X1 g41044(.A (n_78), .B (n_636), .Y (n_671));
  OAI21X1 g41045(.A (n_632), .B (n_524), .C (n_542), .Y (n_670));
  AOI21X1 g41046(.A (n_544), .B (n_80), .C (n_643), .Y (n_669));
  NAND2X1 g41047(.A (n_639), .B (n_608), .Y (n_668));
  AOI21X1 g41048(.A (n_541), .B (n_209), .C (n_641), .Y (n_675));
  INVX1 g41051(.A (n_657), .Y (n_667));
  INVX2 g41052(.A (n_665), .Y (n_666));
  OAI22X1 g41053(.A (n_622), .B (n_177), .C (n_188), .D (n_116), .Y
       (n_664));
  AOI22X1 g41054(.A (n_312), .B (n_1007), .C (n_61), .D (n_626), .Y
       (n_663));
  AND3X1 g41055(.A (n_91), .B (n_291), .C (n_613), .Y (n_662));
  AND3X1 g41056(.A (n_91), .B (n_334), .C (n_614), .Y (n_661));
  AND3X1 g41058(.A (n_91), .B (n_333), .C (n_619), .Y (n_659));
  AOI22X1 g41059(.A (n_26), .B (n_630), .C (n_968), .D (n_79), .Y
       (n_658));
  OAI22X1 g41060(.A (n_592), .B (n_294), .C (n_628), .D (n_907), .Y
       (n_657));
  AOI22X1 g41061(.A (n_315), .B (n_1009), .C (n_61), .D (n_627), .Y
       (n_656));
  NOR3X1 g41062(.A (n_504), .B (n_560), .C (n_615), .Y (n_665));
  INVX2 g41063(.A (n_654), .Y (n_655));
  NOR2X1 g41064(.A (n_475), .B (n_617), .Y (n_653));
  NAND2X1 g41065(.A (n_78), .B (n_607), .Y (n_652));
  AOI21X1 g41066(.A (n_600), .B (n_51), .C (n_964), .Y (n_651));
  NOR2X1 g41067(.A (n_62), .B (n_610), .Y (n_650));
  NOR3X1 g41068(.A (n_324), .B (n_593), .C (n_596), .Y (n_649));
  NOR2X1 g41069(.A (n_19), .B (n_1005), .Y (n_648));
  NOR2X1 g41071(.A (n_620), .B (n_274), .Y (n_654));
  INVX2 g41075(.A (n_645), .Y (n_646));
  NAND3X1 g41076(.A (n_588), .B (n_469), .C (n_499), .Y (n_643));
  AOI21X1 g41077(.A (n_477), .B (n_420), .C (n_632), .Y (n_642));
  OAI21X1 g41078(.A (n_586), .B (n_177), .C (n_491), .Y (n_641));
  AOI21X1 g41079(.A (n_241), .B (n_218), .C (n_609), .Y (n_640));
  AOI22X1 g41080(.A (n_585), .B (n_236), .C (n_178), .D (n_75), .Y
       (n_639));
  AOI22X1 g41081(.A (n_606), .B (n_75), .C (n_523), .D (n_236), .Y
       (n_638));
  AOI21X1 g41082(.A (n_281), .B (n_64), .C (n_612), .Y (n_637));
  AOI22X1 g41083(.A (n_287), .B (n_579), .C (n_61), .D (n_599), .Y
       (n_636));
  AOI22X1 g41084(.A (n_590), .B (n_304), .C (n_34), .D (n_246), .Y
       (n_647));
  OAI21X1 g41085(.A (n_589), .B (opening), .C (waiting), .Y (n_645));
  OAI21X1 g41086(.A (n_594), .B (n_64), .C (n_179), .Y (n_644));
  INVX2 g41087(.A (n_634), .Y (n_633));
  NAND2X1 g41088(.A (n_967), .B (n_1007), .Y (n_631));
  NAND3X1 g41089(.A (n_65), .B (n_379), .C (n_576), .Y (n_630));
  OAI21X1 g41090(.A (n_571), .B (n_64), .C (n_968), .Y (n_629));
  NAND2X1 g41091(.A (inactivate_in_levels[4]), .B (n_592), .Y (n_628));
  NOR2X1 g41092(.A (n_18), .B (n_1009), .Y (n_627));
  NOR2X1 g41093(.A (n_22), .B (n_1007), .Y (n_626));
  NAND2X1 g41094(.A (n_78), .B (n_583), .Y (n_625));
  NAND2X1 g41095(.A (n_78), .B (n_581), .Y (n_624));
  NAND2X1 g41096(.A (n_78), .B (n_584), .Y (n_623));
  NOR2X1 g41097(.A (n_606), .B (n_582), .Y (n_622));
  NAND2X1 g41101(.A (n_590), .B (an_reset), .Y (n_634));
  NAND2X1 g41102(.A (n_176), .B (n_603), .Y (n_632));
  AOI21X1 g41103(.A (n_575), .B (level_display[2]), .C (n_297), .Y
       (n_619));
  NAND2X1 g41104(.A (n_1024), .B (n_595), .Y (n_618));
  OAI21X1 g41105(.A (n_237), .B (n_350), .C (n_580), .Y (n_617));
  OAI21X1 g41106(.A (n_468), .B (n_545), .C (n_964), .Y (n_616));
  AOI21X1 g41107(.A (n_548), .B (n_515), .C (n_177), .Y (n_615));
  AOI21X1 g41108(.A (n_575), .B (level_display[0]), .C (n_301), .Y
       (n_614));
  AOI21X1 g41109(.A (n_575), .B (level_display[1]), .C (n_339), .Y
       (n_613));
  NAND3X1 g41110(.A (n_552), .B (n_564), .C (n_391), .Y (n_612));
  AND3X1 g41111(.A (n_557), .B (n_280), .C (n_334), .Y (n_611));
  MUX2X2 g41112(.A (n_60), .B (i_direction), .S (n_558), .Y (n_610));
  OAI22X1 g41113(.A (n_576), .B (n_79), .C (n_234), .D (n_875), .Y
       (n_609));
  AOI21X1 g41114(.A (n_915), .B (n_417), .C (n_597), .Y (n_608));
  AOI22X1 g41115(.A (n_295), .B (n_1011), .C (n_61), .D (n_569), .Y
       (n_607));
  OAI21X1 g41116(.A (n_563), .B (n_64), .C (n_181), .Y (n_621));
  NAND3X1 g41117(.A (n_30), .B (n_31), .C (n_565), .Y (n_620));
  INVX1 g41118(.A (n_603), .Y (n_602));
  NAND2X1 g41119(.A (n_78), .B (n_547), .Y (n_601));
  NOR2X1 g41120(.A (n_465), .B (n_561), .Y (n_600));
  NOR2X1 g41121(.A (n_877), .B (n_579), .Y (n_599));
  NAND2X1 g41122(.A (n_78), .B (n_549), .Y (n_598));
  OAI21X1 g41123(.A (n_190), .B (n_534), .C (n_550), .Y (n_597));
  OAI21X1 g41124(.A (n_501), .B (n_60), .C (n_555), .Y (n_596));
  NAND2X1 g41125(.A (level_display[3]), .B (n_575), .Y (n_595));
  NAND2X1 g41127(.A (n_420), .B (n_554), .Y (n_606));
  AND3X1 g41128(.A (n_486), .B (n_220), .C (n_520), .Y (n_605));
  NOR2X1 g41131(.A (n_31), .B (n_572), .Y (n_603));
  INVX2 g41132(.A (n_593), .Y (n_594));
  INVX2 g41133(.A (n_590), .Y (n_589));
  AOI21X1 g41134(.A (n_503), .B (n_967), .C (n_573), .Y (n_588));
  AOI22X1 g41136(.A (n_209), .B (n_524), .C (n_142), .D (n_443), .Y
       (n_586));
  NAND3X1 g41137(.A (letout), .B (n_542), .C (n_523), .Y (n_585));
  AOI22X1 g41138(.A (n_295), .B (n_510), .C (n_61), .D (n_535), .Y
       (n_584));
  AOI22X1 g41139(.A (n_287), .B (n_1013), .C (n_61), .D (n_536), .Y
       (n_583));
  OAI21X1 g41140(.A (n_524), .B (n_208), .C (n_485), .Y (n_582));
  AOI22X1 g41141(.A (n_293), .B (n_505), .C (n_61), .D (n_537), .Y
       (n_581));
  AOI21X1 g41142(.A (n_189), .B (n_464), .C (n_546), .Y (n_580));
  MUX2NX1 g41143(.A (n_343), .B (n_538), .S (n_26), .Y (n_593));
  AOI21X1 g41144(.A (n_527), .B (reached), .C (n_286), .Y (n_592));
  NAND3X1 g41146(.A (n_4), .B (n_31), .C (n_539), .Y (n_590));
  OAI21X1 g41148(.A (n_362), .B (n_174), .C (n_516), .Y (n_574));
  NOR2X1 g41149(.A (n_540), .B (n_88), .Y (n_573));
  NAND3X1 g41150(.A (n_2), .B (n_10), .C (n_494), .Y (n_572));
  NOR2X1 g41151(.A (n_540), .B (n_48), .Y (n_571));
  NOR2X1 g41153(.A (n_25), .B (n_1011), .Y (n_569));
  NOR3X1 g41154(.A (n_969), .B (n_388), .C (n_471), .Y (n_568));
  NAND2X1 g41155(.A (n_78), .B (n_521), .Y (n_567));
  NAND2X1 g41156(.A (n_78), .B (n_519), .Y (n_566));
  AND3X1 g41157(.A (n_11), .B (n_5), .C (n_473), .Y (n_565));
  OAI21X1 g41158(.A (n_355), .B (n_497), .C (n_283), .Y (n_564));
  NAND2X1 g41159(.A (n_240), .B (n_518), .Y (n_579));
  NAND3X1 g41160(.A (n_490), .B (n_149), .C (n_87), .Y (n_577));
  NAND2X1 g41161(.A (n_968), .B (n_540), .Y (n_576));
  OAI21X1 g41163(.A (n_512), .B (n_969), .C (an_reset), .Y (n_575));
  INVX2 g41164(.A (n_562), .Y (n_563));
  INVX2 g41165(.A (n_559), .Y (n_560));
  INVX2 g41166(.A (n_558), .Y (n_557));
  AOI22X1 g41168(.A (n_60), .B (n_474), .C (n_264), .D (n_64), .Y
       (n_555));
  AOI21X1 g41169(.A (n_480), .B (n_144), .C (n_513), .Y (n_554));
  AOI22X1 g41170(.A (n_482), .B (n_230), .C (n_6), .D (n_292), .Y
       (n_553));
  OAI21X1 g41171(.A (n_503), .B (n_64), .C (n_145), .Y (n_552));
  OAI21X1 g41172(.A (n_363), .B (n_174), .C (n_514), .Y (n_551));
  OAI21X1 g41173(.A (n_482), .B (n_6), .C (n_230), .Y (n_550));
  AOI22X1 g41174(.A (n_293), .B (n_1015), .C (n_61), .D (n_496), .Y
       (n_549));
  AOI22X1 g41175(.A (n_225), .B (n_400), .C (n_144), .D (n_481), .Y
       (n_548));
  AOI22X1 g41176(.A (n_293), .B (n_466), .C (n_61), .D (n_495), .Y
       (n_547));
  OAI22X1 g41177(.A (n_229), .B (n_403), .C (n_235), .D (n_511), .Y
       (n_546));
  OAI22X1 g41178(.A (n_282), .B (n_479), .C (n_232), .D (n_1023), .Y
       (n_545));
  OAI22X1 g41179(.A (n_479), .B (n_210), .C (n_416), .D (n_206), .Y
       (n_544));
  MUX2NX1 g41180(.A (n_256), .B (n_502), .S (n_60), .Y (n_562));
  OAI22X1 g41181(.A (n_146), .B (n_503), .C (n_355), .D (n_284), .Y
       (n_561));
  AOI22X1 g41182(.A (n_175), .B (n_444), .C (n_144), .D (n_507), .Y
       (n_559));
  OAI21X1 g41183(.A (n_478), .B (n_372), .C (n_52), .Y (n_558));
  INVX2 g41184(.A (n_542), .Y (n_541));
  NOR3X1 g41185(.A (n_12), .B (n_86), .C (n_452), .Y (n_539));
  NAND2X1 g41186(.A (n_211), .B (n_479), .Y (n_538));
  NOR2X1 g41187(.A (n_879), .B (n_505), .Y (n_537));
  NOR2X1 g41188(.A (n_20), .B (n_1013), .Y (n_536));
  NOR2X1 g41189(.A (n_43), .B (n_510), .Y (n_535));
  NOR2X1 g41190(.A (n_481), .B (n_507), .Y (n_534));
  NAND2X1 g41191(.A (n_188), .B (n_478), .Y (n_533));
  NAND2X1 g41192(.A (n_78), .B (n_470), .Y (n_532));
  NAND2X1 g41193(.A (n_144), .B (n_487), .Y (n_531));
  NAND2X1 g41196(.A (n_172), .B (n_511), .Y (n_542));
  NAND2X1 g41197(.A (n_489), .B (n_149), .Y (n_540));
  INVX2 g41201(.A (n_524), .Y (n_523));
  AOI21X1 g41202(.A (n_144), .B (n_277), .C (n_484), .Y (n_522));
  AOI22X1 g41203(.A (n_315), .B (n_426), .C (n_61), .D (n_451), .Y
       (n_521));
  OAI21X1 g41204(.A (n_462), .B (n_443), .C (n_186), .Y (n_520));
  AOI22X1 g41205(.A (n_287), .B (n_423), .C (n_61), .D (n_453), .Y
       (n_519));
  AOI22X1 g41206(.A (n_459), .B (n_151), .C (n_347), .D (n_248), .Y
       (n_518));
  AOI21X1 g41207(.A (n_344), .B (n_104), .C (n_500), .Y (n_517));
  AOI22X1 g41208(.A (n_209), .B (n_458), .C (n_214), .D (n_212), .Y
       (n_516));
  AOI22X1 g41209(.A (n_175), .B (n_442), .C (n_212), .D (n_367), .Y
       (n_515));
  AOI22X1 g41210(.A (n_209), .B (n_457), .C (n_213), .D (n_212), .Y
       (n_514));
  OAI22X1 g41211(.A (n_400), .B (n_226), .C (n_443), .D (n_141), .Y
       (n_513));
  NAND3X1 g41212(.A (n_211), .B (n_440), .C (n_80), .Y (n_529));
  MUX2NX1 g41213(.A (n_450), .B (n_412), .S (n_60), .Y (n_527));
  NAND3X1 g41214(.A (n_967), .B (n_454), .C (n_971), .Y (n_525));
  MUX2NX1 g41215(.A (n_458), .B (n_108), .S (n_60), .Y (n_524));
  INVX2 g41216(.A (n_498), .Y (n_512));
  INVX2 g41217(.A (n_508), .Y (n_509));
  NAND2X1 g41218(.A (n_967), .B (n_460), .Y (n_502));
  NAND2X1 g41219(.A (n_104), .B (n_459), .Y (n_501));
  NOR2X1 g41220(.A (n_459), .B (n_150), .Y (n_500));
  NOR2X1 g41221(.A (n_433), .B (n_389), .Y (n_499));
  NOR3X1 g41222(.A (n_966), .B (n_401), .C (n_372), .Y (n_498));
  NOR2X1 g41223(.A (n_459), .B (n_48), .Y (n_497));
  NOR2X1 g41224(.A (n_45), .B (n_1015), .Y (n_496));
  NOR2X1 g41225(.A (n_24), .B (n_466), .Y (n_495));
  AND3X1 g41226(.A (counter[10]), .B (n_110), .C (n_422), .Y (n_494));
  AOI21X1 g41227(.A (n_394), .B (n_380), .C (n_81), .Y (n_493));
  NAND2X1 g41229(.A (n_108), .B (n_458), .Y (n_511));
  NAND2X1 g41231(.A (n_285), .B (n_434), .Y (n_510));
  NOR2X1 g41232(.A (n_421), .B (n_447), .Y (n_508));
  NOR2X1 g41233(.A (n_173), .B (n_464), .Y (n_507));
  NAND2X1 g41235(.A (n_243), .B (n_439), .Y (n_505));
  NOR2X1 g41236(.A (n_173), .B (n_437), .Y (n_504));
  NOR2X1 g41237(.A (n_460), .B (n_63), .Y (n_503));
  INVX2 g41238(.A (n_491), .Y (n_492));
  INVX2 g41239(.A (n_489), .Y (n_490));
  INVX2 g41240(.A (n_487), .Y (n_488));
  INVX1 g41241(.A (n_484), .Y (n_485));
  INVX2 g41242(.A (n_467), .Y (n_482));
  INVX2 g41243(.A (n_481), .Y (n_480));
  AOI22X1 g41244(.A (n_142), .B (n_404), .C (n_225), .D (n_351), .Y
       (n_477));
  NAND2X1 g41245(.A (n_441), .B (n_230), .Y (n_476));
  OAI21X1 g41246(.A (n_187), .B (n_427), .C (n_410), .Y (n_475));
  OAI21X1 g41247(.A (n_217), .B (n_210), .C (n_435), .Y (n_474));
  NOR2X1 g41248(.A (n_35), .B (n_438), .Y (n_473));
  OAI22X1 g41250(.A (n_414), .B (n_143), .C (n_342), .D (n_26), .Y
       (n_471));
  AOI22X1 g41251(.A (n_312), .B (n_387), .C (n_61), .D (n_409), .Y
       (n_470));
  AOI22X1 g41252(.A (n_102), .B (n_411), .C (n_205), .D (n_262), .Y
       (n_469));
  OAI22X1 g41253(.A (n_227), .B (n_416), .C (n_148), .D (n_331), .Y
       (n_468));
  NAND2X1 g41254(.A (n_142), .B (n_462), .Y (n_491));
  NAND3X1 g41255(.A (active_out_down_levels[1]), .B (n_57), .C (n_458),
       .Y (n_489));
  OAI21X1 g41256(.A (n_415), .B (n_126), .C (n_107), .Y (n_487));
  OAI21X1 g41257(.A (n_417), .B (active_in_levels[0]), .C (n_914), .Y
       (n_486));
  NOR2X1 g41258(.A (n_174), .B (n_442), .Y (n_484));
  OAI22X1 g41259(.A (n_237), .B (n_393), .C (n_333), .D (letout), .Y
       (n_483));
  NOR2X1 g41260(.A (n_442), .B (n_444), .Y (n_467));
  OAI21X1 g41261(.A (n_414), .B (n_60), .C (n_277), .Y (n_481));
  OAI21X1 g41262(.A (n_415), .B (n_72), .C (n_136), .Y (n_479));
  NAND3X1 g41263(.A (n_179), .B (n_181), .C (n_396), .Y (n_478));
  INVX2 g41264(.A (n_457), .Y (n_458));
  NAND2X1 g41265(.A (n_106), .B (n_401), .Y (n_456));
  NAND2X1 g41266(.A (n_370), .B (n_390), .Y (n_455));
  NOR2X1 g41267(.A (n_424), .B (n_134), .Y (n_454));
  NOR2X1 g41268(.A (n_44), .B (n_423), .Y (n_453));
  NAND2X1 g41269(.A (n_15), .B (n_422), .Y (n_452));
  NOR2X1 g41270(.A (n_46), .B (n_426), .Y (n_451));
  NAND2X1 g41271(.A (n_207), .B (n_416), .Y (n_450));
  NAND2X1 g41272(.A (n_243), .B (n_397), .Y (n_466));
  NOR2X1 g41274(.A (n_148), .B (n_425), .Y (n_465));
  NOR2X1 g41275(.A (n_216), .B (n_415), .Y (n_464));
  NAND2X1 g41276(.A (n_147), .B (n_425), .Y (n_463));
  NOR2X1 g41277(.A (n_173), .B (n_428), .Y (n_462));
  NAND2X1 g41279(.A (n_424), .B (n_135), .Y (n_460));
  OAI21X1 g41280(.A (n_362), .B (n_98), .C (n_137), .Y (n_459));
  NAND2X1 g41281(.A (n_155), .B (n_414), .Y (n_457));
  INVX2 g41283(.A (n_429), .Y (n_447));
  INVX2 g41285(.A (n_441), .Y (n_442));
  NOR3X1 g41286(.A (active_out_up_levels[2]), .B (n_74), .C (n_415), .Y
       (n_440));
  AOI22X1 g41287(.A (n_381), .B (n_245), .C (n_331), .D (n_154), .Y
       (n_439));
  NAND3X1 g41288(.A (n_36), .B (n_110), .C (n_377), .Y (n_438));
  AOI22X1 g41289(.A (n_225), .B (n_382), .C (n_212), .D (n_350), .Y
       (n_437));
  AOI21X1 g41290(.A (n_376), .B (n_251), .C (n_81), .Y (n_436));
  AOI22X1 g41291(.A (n_205), .B (n_381), .C (n_207), .D (n_347), .Y
       (n_435));
  AOI21X1 g41292(.A (n_964), .B (n_255), .C (n_406), .Y (n_434));
  OAI22X1 g41293(.A (n_244), .B (n_381), .C (n_242), .D (n_218), .Y
       (n_433));
  OAI21X1 g41295(.A (n_383), .B (n_173), .C (n_399), .Y (n_431));
  OAI22X1 g41296(.A (n_378), .B (letout), .C (n_334), .D (n_48), .Y
       (n_430));
  NAND2X1 g41297(.A (n_971), .B (n_413), .Y (n_448));
  OAI21X1 g41298(.A (n_365), .B (active_in_levels[0]), .C (n_966), .Y
       (n_429));
  NAND3X1 g41299(.A (n_207), .B (n_359), .C (n_80), .Y (n_445));
  NOR2X1 g41300(.A (n_173), .B (n_402), .Y (n_444));
  OAI21X1 g41301(.A (n_105), .B (n_60), .C (n_404), .Y (n_443));
  MUX2NX1 g41302(.A (n_267), .B (n_362), .S (n_26), .Y (n_441));
  INVX2 g41303(.A (n_427), .Y (n_428));
  INVX2 g41304(.A (n_408), .Y (n_421));
  INVX2 g41306(.A (n_415), .Y (n_414));
  NOR2X1 g41307(.A (n_381), .B (n_232), .Y (n_413));
  NAND2X1 g41308(.A (n_102), .B (n_384), .Y (n_412));
  NOR2X1 g41309(.A (n_384), .B (n_83), .Y (n_411));
  NAND2X1 g41310(.A (n_383), .B (n_289), .Y (n_410));
  NOR2X1 g41311(.A (n_16), .B (n_387), .Y (n_409));
  NAND2X1 g41312(.A (n_105), .B (n_369), .Y (n_427));
  NAND2X1 g41313(.A (n_179), .B (n_358), .Y (n_426));
  NOR2X1 g41314(.A (n_384), .B (n_63), .Y (n_425));
  NAND2X1 g41315(.A (active_out_up_levels[6]), .B (n_369), .Y (n_424));
  NAND2X1 g41316(.A (n_240), .B (n_361), .Y (n_423));
  AND3X1 g41317(.A (counter[3]), .B (n_35), .C (n_340), .Y (n_422));
  NAND2X1 g41318(.A (n_969), .B (n_365), .Y (n_408));
  NAND2X1 g41319(.A (n_212), .B (n_366), .Y (n_420));
  NAND2X1 g41320(.A (n_363), .B (n_303), .Y (n_418));
  NAND2X1 g41321(.A (letout), .B (n_364), .Y (n_417));
  OAI21X1 g41322(.A (n_346), .B (n_71), .C (n_158), .Y (n_416));
  NAND2X1 g41323(.A (n_156), .B (n_363), .Y (n_415));
  INVX2 g41325(.A (n_402), .Y (n_403));
  INVX1 g41326(.A (n_400), .Y (n_399));
  OAI22X1 g41327(.A (n_321), .B (n_81), .C (n_325), .D (closing), .Y
       (n_398));
  AOI21X1 g41328(.A (n_964), .B (n_200), .C (n_385), .Y (n_397));
  NOR3X1 g41329(.A (n_234), .B (n_286), .C (n_326), .Y (n_396));
  NAND3X1 g41331(.A (n_182), .B (n_115), .C (n_348), .Y (n_394));
  AOI21X1 g41332(.A (n_350), .B (n_172), .C (n_367), .Y (n_393));
  OAI22X1 g41333(.A (n_345), .B (n_173), .C (n_177), .D (n_60), .Y
       (n_392));
  OAI21X1 g41334(.A (n_297), .B (n_339), .C (n_64), .Y (n_391));
  AOI22X1 g41335(.A (n_290), .B (n_353), .C (n_61), .D (n_328), .Y
       (n_390));
  OAI22X1 g41336(.A (n_247), .B (n_347), .C (n_153), .D (n_331), .Y
       (n_389));
  OAI22X1 g41337(.A (n_345), .B (n_226), .C (n_141), .D (n_105), .Y
       (n_388));
  NOR3X1 g41338(.A (n_356), .B (n_201), .C (n_83), .Y (n_406));
  NAND2X1 g41339(.A (n_971), .B (n_375), .Y (n_405));
  NAND2X1 g41340(.A (n_60), .B (n_1017), .Y (n_404));
  NOR2X1 g41341(.A (n_267), .B (n_362), .Y (n_402));
  NAND3X1 g41342(.A (n_226), .B (n_141), .C (n_341), .Y (n_401));
  OAI21X1 g41343(.A (n_345), .B (n_60), .C (n_351), .Y (n_400));
  INVX2 g41344(.A (n_385), .Y (n_386));
  INVX1 g41345(.A (n_383), .Y (n_382));
  NAND2X1 g41346(.A (door[1]), .B (n_349), .Y (n_380));
  NAND2X1 g41347(.A (n_102), .B (n_331), .Y (n_379));
  NOR2X1 g41348(.A (n_332), .B (n_292), .Y (n_378));
  AND3X1 g41349(.A (counter[6]), .B (counter[10]), .C (n_299), .Y
       (n_377));
  NAND2X1 g41350(.A (door[0]), .B (n_349), .Y (n_376));
  NOR2X1 g41351(.A (n_347), .B (n_227), .Y (n_375));
  NAND2X1 g41352(.A (n_181), .B (n_322), .Y (n_387));
  NOR2X1 g41353(.A (n_357), .B (n_308), .Y (n_385));
  NAND2X1 g41354(.A (n_356), .B (n_131), .Y (n_384));
  NOR2X1 g41355(.A (n_314), .B (n_346), .Y (n_383));
  NAND2X1 g41356(.A (n_357), .B (n_133), .Y (n_381));
  INVX2 g41358(.A (n_1017), .Y (n_369));
  INVX2 g41359(.A (n_367), .Y (n_366));
  INVX2 g41360(.A (n_364), .Y (n_365));
  INVX2 g41361(.A (n_363), .Y (n_362));
  AOI21X1 g41362(.A (n_964), .B (n_202), .C (n_336), .Y (n_361));
  OAI21X1 g41363(.A (n_282), .B (n_48), .C (n_329), .Y (n_360));
  AND3X1 g41364(.A (active_out_down_levels[4]), .B (n_117), .C (n_345),
       .Y (n_359));
  AOI21X1 g41365(.A (n_964), .B (n_257), .C (n_1019), .Y (n_358));
  NAND3X1 g41366(.A (active_out_down_levels[5]), .B (n_316), .C
       (n_154), .Y (n_373));
  NAND3X1 g41367(.A (n_51), .B (n_268), .C (n_318), .Y (n_372));
  AND3X1 g41368(.A (n_217), .B (n_971), .C (n_281), .Y (n_371));
  AOI21X1 g41369(.A (n_290), .B (n_234), .C (n_77), .Y (n_370));
  MUX2NX1 g41371(.A (n_310), .B (n_214), .S (n_26), .Y (n_367));
  NOR3X1 g41372(.A (active_out_up_levels[0]), .B (n_306), .C (n_346),
       .Y (n_364));
  NOR2X1 g41373(.A (n_161), .B (n_346), .Y (n_363));
  INVX1 g41374(.A (n_352), .Y (n_353));
  INVX2 g41375(.A (n_348), .Y (n_349));
  INVX2 g41376(.A (n_346), .Y (n_345));
  NOR2X1 g41377(.A (n_311), .B (n_83), .Y (n_344));
  NAND2X1 g41378(.A (n_104), .B (n_311), .Y (n_343));
  NOR2X1 g41379(.A (n_205), .B (n_317), .Y (n_342));
  NOR2X1 g41380(.A (n_144), .B (n_296), .Y (n_341));
  NOR2X1 g41381(.A (n_112), .B (n_298), .Y (n_340));
  NAND2X1 g41382(.A (active_out_up_levels[5]), .B (n_310), .Y (n_357));
  NAND2X1 g41383(.A (active_out_up_levels[4]), .B (n_313), .Y (n_356));
  NOR2X1 g41384(.A (n_63), .B (n_311), .Y (n_355));
  NAND2X1 g41386(.A (n_128), .B (n_305), .Y (n_352));
  NAND2X1 g41387(.A (n_60), .B (n_314), .Y (n_351));
  NAND2X1 g41388(.A (n_214), .B (n_310), .Y (n_350));
  OAI21X1 g41389(.A (n_124), .B (n_185), .C (n_278), .Y (n_348));
  NAND2X1 g41390(.A (n_319), .B (n_132), .Y (n_347));
  NAND2X1 g41391(.A (n_54), .B (n_316), .Y (n_346));
  INVX2 g41392(.A (n_336), .Y (n_337));
  INVX2 g41393(.A (n_332), .Y (n_333));
  AOI22X1 g41394(.A (n_964), .B (n_228), .C (state[2]), .D (n_50), .Y
       (n_330));
  AOI22X1 g41395(.A (n_191), .B (n_246), .C (n_48), .D (n_228), .Y
       (n_329));
  OAI22X1 g41396(.A (n_234), .B (n_23), .C (n_88), .D (n_149), .Y
       (n_328));
  OAI21X1 g41397(.A (n_263), .B (n_60), .C (n_204), .Y (n_327));
  OAI21X1 g41398(.A (n_276), .B (letout), .C (n_96), .Y (n_326));
  AOI21X1 g41399(.A (an_reset), .B (n_271), .C (n_50), .Y (n_325));
  AOI21X1 g41400(.A (n_263), .B (n_268), .C (reached), .Y (n_324));
  AOI21X1 g41401(.A (n_225), .B (n_106), .C (n_966), .Y (n_323));
  AOI21X1 g41402(.A (n_971), .B (n_196), .C (n_1021), .Y (n_322));
  NAND2X1 g41403(.A (n_284), .B (n_227), .Y (n_339));
  AOI21X1 g41404(.A (n_236), .B (n_6), .C (n_909), .Y (n_338));
  NOR2X1 g41405(.A (n_319), .B (n_307), .Y (n_336));
  AOI22X1 g41406(.A (n_224), .B (n_75), .C (n_964), .D (n_231), .Y
       (n_335));
  NOR2X1 g41407(.A (n_281), .B (n_228), .Y (n_334));
  NAND2X1 g41408(.A (n_237), .B (n_288), .Y (n_332));
  OAI21X1 g41409(.A (n_253), .B (active_out_up_levels[5]), .C (n_138),
       .Y (n_331));
  INVX2 g41410(.A (n_302), .Y (n_321));
  INVX2 g41411(.A (n_317), .Y (n_318));
  INVX1 g41412(.A (n_314), .Y (n_313));
  NOR2X1 g41413(.A (n_252), .B (n_141), .Y (n_309));
  NAND2X1 g41414(.A (n_133), .B (n_245), .Y (n_308));
  NAND2X1 g41415(.A (n_132), .B (n_248), .Y (n_307));
  NAND2X1 g41416(.A (n_157), .B (n_250), .Y (n_306));
  NOR2X1 g41417(.A (n_164), .B (n_242), .Y (n_305));
  NOR2X1 g41418(.A (n_116), .B (n_238), .Y (n_304));
  NOR3X1 g41419(.A (active_out_up_levels[3]), .B (active_in_levels[3]),
       .C (n_198), .Y (n_303));
  NOR2X1 g41420(.A (n_271), .B (n_191), .Y (n_302));
  NAND2X1 g41421(.A (n_269), .B (n_1024), .Y (n_320));
  NAND2X1 g41422(.A (active_out_up_levels[3]), .B (n_266), .Y (n_319));
  NAND2X1 g41423(.A (n_265), .B (n_263), .Y (n_317));
  NOR3X1 g41424(.A (active_out_up_levels[5]), .B (active_in_levels[5]),
       .C (n_213), .Y (n_316));
  NOR2X1 g41425(.A (n_265), .B (n_907), .Y (n_315));
  NAND2X1 g41426(.A (n_156), .B (n_266), .Y (n_314));
  NOR2X1 g41427(.A (n_268), .B (n_907), .Y (n_312));
  NAND2X1 g41428(.A (n_272), .B (n_129), .Y (n_311));
  NOR2X1 g41429(.A (n_216), .B (n_249), .Y (n_310));
  INVX2 g41430(.A (n_298), .Y (n_299));
  INVX2 g41431(.A (n_295), .Y (n_294));
  INVX2 g41432(.A (n_292), .Y (n_291));
  INVX2 g41433(.A (n_288), .Y (n_289));
  INVX2 g41434(.A (n_286), .Y (n_285));
  INVX2 g41435(.A (n_283), .Y (n_284));
  INVX2 g41436(.A (n_282), .Y (n_281));
  OAI21X1 g41437(.A (n_205), .B (n_968), .C (n_75), .Y (n_280));
  OAI21X1 g41439(.A (n_191), .B (n_165), .C (n_270), .Y (n_278));
  NAND2X1 g41440(.A (n_229), .B (n_237), .Y (n_301));
  NAND3X1 g41442(.A (counter[14]), .B (counter[13]), .C (n_171), .Y
       (n_298));
  NAND2X1 g41443(.A (n_148), .B (n_232), .Y (n_297));
  NAND2X1 g41444(.A (n_208), .B (n_276), .Y (n_296));
  NOR2X1 g41445(.A (n_263), .B (n_907), .Y (n_295));
  AOI21X1 g41446(.A (n_101), .B (n_204), .C (n_907), .Y (n_293));
  NAND3X1 g41447(.A (n_229), .B (n_187), .C (n_190), .Y (n_292));
  AOI21X1 g41448(.A (n_51), .B (n_210), .C (n_907), .Y (n_290));
  NAND2X1 g41449(.A (n_225), .B (n_75), .Y (n_288));
  AOI21X1 g41450(.A (n_103), .B (n_206), .C (n_907), .Y (n_287));
  NOR2X1 g41451(.A (letout), .B (n_226), .Y (n_286));
  NOR3X1 g41452(.A (n_7), .B (n_166), .C (n_76), .Y (n_283));
  NAND3X1 g41453(.A (n_29), .B (n_170), .C (n_75), .Y (n_282));
  INVX2 g41454(.A (n_274), .Y (n_275));
  INVX1 g41456(.A (n_271), .Y (n_270));
  INVX2 g41458(.A (n_267), .Y (n_266));
  INVX2 g41459(.A (n_264), .Y (n_265));
  NOR2X1 g41460(.A (n_1023), .B (n_79), .Y (n_262));
  NAND2X1 g41461(.A (n_185), .B (n_183), .Y (n_261));
  NAND2X1 g41462(.A (counter[4]), .B (n_193), .Y (n_260));
  NOR2X1 g41463(.A (n_210), .B (n_128), .Y (n_259));
  NOR2X1 g41464(.A (n_204), .B (n_133), .Y (n_258));
  NOR2X1 g41465(.A (n_210), .B (n_136), .Y (n_257));
  NAND2X1 g41466(.A (n_205), .B (n_1023), .Y (n_256));
  NOR2X1 g41467(.A (n_206), .B (n_158), .Y (n_255));
  NOR2X1 g41468(.A (n_206), .B (n_132), .Y (n_254));
  NAND2X1 g41469(.A (active_out_down_levels[5]), .B (n_214), .Y
       (n_253));
  NAND2X1 g41470(.A (n_60), .B (n_216), .Y (n_277));
  NOR2X1 g41472(.A (n_175), .B (n_212), .Y (n_276));
  NAND2X1 g41473(.A (n_219), .B (n_75), .Y (n_274));
  NAND2X1 g41474(.A (active_out_up_levels[2]), .B (n_215), .Y (n_272));
  NAND2X1 g41476(.A (waiting), .B (n_182), .Y (n_271));
  NAND2X1 g41477(.A (n_188), .B (an_reset), .Y (n_269));
  NOR2X1 g41478(.A (n_967), .B (n_205), .Y (n_268));
  NAND2X1 g41479(.A (n_155), .B (n_215), .Y (n_267));
  NAND2X1 g41480(.A (n_210), .B (n_103), .Y (n_264));
  NOR2X1 g41481(.A (n_207), .B (n_102), .Y (n_263));
  INVX1 g41482(.A (n_249), .Y (n_250));
  INVX2 g41483(.A (n_248), .Y (n_247));
  INVX2 g41484(.A (n_245), .Y (n_244));
  INVX2 g41485(.A (n_241), .Y (n_242));
  INVX2 g41486(.A (n_239), .Y (n_238));
  INVX2 g41487(.A (n_236), .Y (n_235));
  INVX1 g41489(.A (n_232), .Y (n_231));
  INVX2 g41490(.A (n_230), .Y (n_229));
  INVX2 g41491(.A (n_228), .Y (n_227));
  INVX2 g41492(.A (n_226), .Y (n_225));
  AND3X1 g41493(.A (closing), .B (n_184), .C (n_114), .Y (n_224));
  XNOR2X1 g41494(.A (n_36), .B (n_152), .Y (n_223));
  OAI21X1 g41495(.A (n_119), .B (state[2]), .C (state[4]), .Y (n_222));
  NAND2X1 g41497(.A (n_180), .B (n_75), .Y (n_220));
  AOI21X1 g41498(.A (n_125), .B (n_105), .C (n_106), .Y (n_252));
  NAND3X1 g41499(.A (n_184), .B (n_94), .C (n_113), .Y (n_251));
  NAND3X1 g41500(.A (n_156), .B (n_155), .C (n_162), .Y (n_249));
  NOR2X1 g41501(.A (n_206), .B (n_83), .Y (n_248));
  NOR2X1 g41502(.A (n_183), .B (n_76), .Y (n_246));
  NOR2X1 g41503(.A (n_204), .B (n_83), .Y (n_245));
  NAND2X1 g41504(.A (n_6), .B (n_212), .Y (n_243));
  NOR2X1 g41505(.A (n_210), .B (n_83), .Y (n_241));
  NAND2X1 g41506(.A (n_6), .B (n_175), .Y (n_240));
  NOR2X1 g41507(.A (n_188), .B (n_76), .Y (n_239));
  NAND2X1 g41508(.A (n_212), .B (n_75), .Y (n_237));
  NOR2X1 g41509(.A (n_208), .B (n_76), .Y (n_236));
  NOR2X1 g41510(.A (letout), .B (n_208), .Y (n_234));
  NAND2X1 g41511(.A (n_205), .B (n_75), .Y (n_232));
  NOR2X1 g41512(.A (n_174), .B (n_76), .Y (n_230));
  NOR2X1 g41513(.A (n_206), .B (n_76), .Y (n_228));
  NAND3X1 g41514(.A (n_8), .B (state[2]), .C (n_140), .Y (n_226));
  INVX2 g41515(.A (n_218), .Y (n_217));
  INVX2 g41516(.A (n_216), .Y (n_215));
  INVX2 g41517(.A (n_214), .Y (n_213));
  INVX2 g41518(.A (n_211), .Y (n_210));
  INVX2 g41519(.A (n_209), .Y (n_208));
  INVX2 g41520(.A (n_207), .Y (n_206));
  INVX2 g41521(.A (n_205), .Y (n_204));
  NAND2X1 g41522(.A (n_78), .B (n_118), .Y (n_203));
  NOR2X1 g41523(.A (n_103), .B (n_137), .Y (n_202));
  NAND2X1 g41524(.A (n_102), .B (n_131), .Y (n_201));
  NOR2X1 g41525(.A (n_101), .B (n_138), .Y (n_200));
  NOR2X1 g41526(.A (n_101), .B (n_131), .Y (n_199));
  NAND2X1 g41527(.A (active_out_down_levels[3]), .B (n_151), .Y
       (n_198));
  NOR2X1 g41528(.A (n_163), .B (n_48), .Y (n_197));
  NOR2X1 g41529(.A (n_65), .B (n_135), .Y (n_196));
  NAND2X1 g41530(.A (n_78), .B (n_121), .Y (n_195));
  NOR2X1 g41531(.A (n_130), .B (n_917), .Y (n_219));
  NAND2X1 g41532(.A (n_164), .B (n_128), .Y (n_218));
  NAND2X1 g41533(.A (n_108), .B (n_157), .Y (n_216));
  NOR2X1 g41534(.A (active_out_down_levels[6]), .B (n_159), .Y (n_214));
  NOR2X1 g41535(.A (n_130), .B (n_920), .Y (n_212));
  NOR2X1 g41536(.A (n_127), .B (n_918), .Y (n_211));
  NOR2X1 g41537(.A (n_127), .B (n_920), .Y (n_209));
  NOR2X1 g41538(.A (n_127), .B (n_917), .Y (n_207));
  NOR2X1 g41539(.A (n_130), .B (n_918), .Y (n_205));
  INVX1 g41540(.A (n_194), .Y (n_193));
  INVX2 g41541(.A (n_190), .Y (n_189));
  INVX1 g41542(.A (n_187), .Y (n_186));
  INVX2 g41543(.A (n_185), .Y (n_184));
  INVX2 g41544(.A (n_183), .Y (n_182));
  INVX1 g41545(.A (n_181), .Y (n_180));
  INVX1 g41546(.A (n_179), .Y (n_178));
  INVX1 g41547(.A (n_177), .Y (n_176));
  INVX2 g41548(.A (n_175), .Y (n_174));
  INVX2 g41549(.A (n_173), .Y (n_172));
  AND3X1 g41550(.A (counter[0]), .B (counter[1]), .C (n_99), .Y
       (n_171));
  NOR2X1 g41551(.A (state[1]), .B (n_127), .Y (n_170));
  NAND2X1 g41552(.A (n_115), .B (n_165), .Y (n_169));
  XNOR2X1 g41553(.A (n_4), .B (n_93), .Y (n_168));
  NOR2X1 g41554(.A (n_103), .B (n_129), .Y (n_167));
  NAND3X1 g41555(.A (state[1]), .B (n_29), .C (n_92), .Y (n_166));
  NAND2X1 g41556(.A (n_36), .B (n_152), .Y (n_194));
  NOR3X1 g41558(.A (overload), .B (sensor_inside), .C (n_115), .Y
       (n_191));
  NAND2X1 g41559(.A (n_144), .B (n_75), .Y (n_190));
  NAND3X1 g41560(.A (n_7), .B (n_92), .C (n_84), .Y (n_188));
  NAND2X1 g41561(.A (n_142), .B (n_75), .Y (n_187));
  NAND3X1 g41562(.A (n_7), .B (n_92), .C (n_59), .Y (n_185));
  NAND3X1 g41563(.A (n_9), .B (state[4]), .C (n_100), .Y (n_183));
  NAND2X1 g41564(.A (n_6), .B (n_142), .Y (n_181));
  NAND2X1 g41565(.A (n_6), .B (n_144), .Y (n_179));
  NAND2X1 g41566(.A (letout), .B (n_126), .Y (n_177));
  NOR2X1 g41567(.A (n_85), .B (n_127), .Y (n_175));
  NAND2X1 g41568(.A (letout), .B (n_125), .Y (n_173));
  INVX2 g41569(.A (n_161), .Y (n_162));
  INVX2 g41571(.A (n_153), .Y (n_154));
  INVX2 g41572(.A (n_150), .Y (n_151));
  INVX1 g41573(.A (n_148), .Y (n_147));
  INVX1 g41574(.A (n_146), .Y (n_145));
  INVX2 g41575(.A (n_144), .Y (n_143));
  INVX2 g41576(.A (n_142), .Y (n_141));
  NOR3X1 g41577(.A (state[0]), .B (state[1]), .C (n_29), .Y (n_140));
  NOR2X1 g41578(.A (n_40), .B (n_86), .Y (n_139));
  NOR3X1 g41579(.A (overload), .B (sensor_inside), .C (open_btn), .Y
       (n_165));
  NAND2X1 g41580(.A (active_out_up_levels[1]), .B (n_108), .Y (n_164));
  AOI21X1 g41581(.A (n_49), .B (active_out_up_levels[6]), .C
       (active_in_levels[6]), .Y (n_163));
  NAND2X1 g41582(.A (n_56), .B (n_117), .Y (n_161));
  NAND2X1 g41583(.A (n_105), .B (n_95), .Y (n_159));
  AOI21X1 g41584(.A (n_49), .B (active_out_up_levels[4]), .C
       (active_in_levels[4]), .Y (n_158));
  NOR3X1 g41585(.A (active_out_up_levels[1]), .B
       (active_out_down_levels[1]), .C (active_in_levels[1]), .Y
       (n_157));
  NOR3X1 g41586(.A (active_out_up_levels[3]), .B
       (active_out_down_levels[3]), .C (active_in_levels[3]), .Y
       (n_156));
  NOR3X1 g41587(.A (active_out_up_levels[2]), .B
       (active_out_down_levels[2]), .C (active_in_levels[2]), .Y
       (n_155));
  NAND2X1 g41588(.A (n_102), .B (n_80), .Y (n_153));
  NOR2X1 g41589(.A (n_5), .B (n_93), .Y (n_152));
  NAND2X1 g41590(.A (n_104), .B (n_80), .Y (n_150));
  AOI21X1 g41591(.A (n_49), .B (active_out_up_levels[1]), .C
       (active_in_levels[1]), .Y (n_149));
  NAND2X1 g41592(.A (n_102), .B (n_75), .Y (n_148));
  NAND2X1 g41593(.A (n_967), .B (n_75), .Y (n_146));
  NOR2X1 g41594(.A (n_85), .B (n_919), .Y (n_144));
  NOR2X1 g41595(.A (n_85), .B (n_916), .Y (n_142));
  INVX2 g41596(.A (n_135), .Y (n_134));
  INVX2 g41597(.A (n_126), .Y (n_125));
  NOR2X1 g41598(.A (n_94), .B (n_114), .Y (n_124));
  XNOR2X1 g41600(.A (counter[1]), .B (counter[0]), .Y (n_122));
  AOI21X1 g41601(.A (n_913), .B (inactivate_in_levels[7]), .C (n_912),
       .Y (n_121));
  AOI21X1 g41602(.A (n_914), .B (n_68), .C (n_915), .Y (n_120));
  OAI21X1 g41603(.A (n_33), .B (n_27), .C (n_28), .Y (n_119));
  AOI21X1 g41604(.A (n_911), .B (inactivate_in_levels[0]), .C (n_910),
       .Y (n_118));
  AOI21X1 g41605(.A (n_49), .B (active_out_up_levels[5]), .C
       (active_in_levels[5]), .Y (n_138));
  AOI21X1 g41606(.A (n_49), .B (active_out_up_levels[3]), .C
       (active_in_levels[3]), .Y (n_137));
  AOI21X1 g41607(.A (n_49), .B (active_out_up_levels[2]), .C
       (active_in_levels[2]), .Y (n_136));
  AOI21X1 g41608(.A (n_49), .B (active_out_down_levels[6]), .C
       (active_in_levels[6]), .Y (n_135));
  AOI21X1 g41609(.A (n_49), .B (active_out_down_levels[5]), .C
       (active_in_levels[5]), .Y (n_133));
  AOI21X1 g41610(.A (n_49), .B (active_out_down_levels[3]), .C
       (active_in_levels[3]), .Y (n_132));
  AOI21X1 g41611(.A (n_49), .B (active_out_down_levels[4]), .C
       (active_in_levels[4]), .Y (n_131));
  NAND3X1 g41612(.A (n_8), .B (state[2]), .C (state[0]), .Y (n_130));
  AOI21X1 g41613(.A (n_49), .B (active_out_down_levels[2]), .C
       (active_in_levels[2]), .Y (n_129));
  AOI21X1 g41614(.A (n_49), .B (active_out_down_levels[1]), .C
       (active_in_levels[1]), .Y (n_128));
  NAND3X1 g41615(.A (n_9), .B (n_8), .C (state[0]), .Y (n_127));
  OAI21X1 g41616(.A (i_direction), .B (n_60), .C (n_107), .Y (n_126));
  INVX2 g41617(.A (n_114), .Y (n_113));
  INVX2 g41618(.A (n_111), .Y (n_112));
  INVX2 g41619(.A (n_110), .Y (n_109));
  INVX2 g41620(.A (n_107), .Y (n_106));
  INVX2 g41621(.A (n_104), .Y (n_103));
  INVX2 g41622(.A (n_102), .Y (n_101));
  NOR2X1 g41623(.A (n_27), .B (n_920), .Y (n_100));
  NOR2X1 g41624(.A (n_40), .B (n_42), .Y (n_99));
  NAND2X1 g41625(.A (active_out_down_levels[3]), .B (n_53), .Y (n_98));
  NOR2X1 g41627(.A (n_899), .B (n_903), .Y (n_96));
  NOR2X1 g41628(.A (active_out_up_levels[6]), .B (active_in_levels[6]),
       .Y (n_95));
  NOR2X1 g41629(.A (active_out_up_levels[4]), .B (active_in_levels[4]),
       .Y (n_117));
  NOR2X1 g41630(.A (n_41), .B (n_34), .Y (n_116));
  NAND2X1 g41631(.A (sensor_door[1]), .B (n_70), .Y (n_115));
  NOR2X1 g41632(.A (sensor_door[1]), .B (n_70), .Y (n_114));
  NOR2X1 g41633(.A (counter[6]), .B (counter[5]), .Y (n_111));
  NOR2X1 g41634(.A (counter[8]), .B (n_3), .Y (n_110));
  NOR2X1 g41635(.A (active_out_up_levels[0]), .B (active_in_levels[0]),
       .Y (n_108));
  NAND2X1 g41636(.A (n_60), .B (i_direction), .Y (n_107));
  NOR2X1 g41637(.A (active_out_down_levels[7]), .B
       (active_in_levels[7]), .Y (n_105));
  NOR2X1 g41638(.A (n_917), .B (n_919), .Y (n_104));
  NOR2X1 g41639(.A (n_918), .B (n_916), .Y (n_102));
  INVX2 g41641(.A (n_87), .Y (n_88));
  INVX2 g41642(.A (n_85), .Y (n_84));
  INVX2 g41643(.A (n_82), .Y (n_81));
  INVX2 g41644(.A (n_80), .Y (n_79));
  INVX2 g41645(.A (n_78), .Y (n_77));
  INVX2 g41646(.A (n_76), .Y (n_75));
  NAND2X1 g41647(.A (active_out_down_levels[2]), .B (n_55), .Y (n_74));
  NAND2X1 g41648(.A (n_34), .B (an_reset), .Y (n_73));
  NAND2X1 g41649(.A (active_out_down_levels[2]), .B (n_66), .Y (n_72));
  NAND2X1 g41650(.A (active_out_down_levels[4]), .B (n_58), .Y (n_71));
  NAND2X1 g41651(.A (opening), .B (close_btn), .Y (n_94));
  NAND2X1 g41652(.A (n_38), .B (n_13), .Y (n_93));
  NOR2X1 g41653(.A (state[0]), .B (state[2]), .Y (n_92));
  NOR2X1 g41654(.A (n_50), .B (n_914), .Y (n_91));
  NOR2X1 g41656(.A (n_51), .B (n_48), .Y (n_87));
  NAND2X1 g41657(.A (n_39), .B (n_30), .Y (n_86));
  NAND2X1 g41658(.A (n_28), .B (state[1]), .Y (n_85));
  NAND2X1 g41659(.A (n_60), .B (reached), .Y (n_83));
  NOR2X1 g41660(.A (buttons_block), .B (n_62), .Y (n_82));
  NOR2X1 g41661(.A (n_60), .B (n_64), .Y (n_80));
  NAND2X2 g41662(.A (an_reset), .B (n_907), .Y (n_78));
  NAND2X1 g41663(.A (an_reset), .B (n_1024), .Y (n_76));
  INVX2 g41665(.A (sensor_door[0]), .Y (n_70));
  INVX2 g41668(.A (n_874), .Y (inactivate_in_levels[0]));
  INVX2 g41673(.A (n_881), .Y (inactivate_in_levels[7]));
  INVX2 g41680(.A (active_in_levels[0]), .Y (n_68));
  INVX1 g41686(.A (active_out_up_levels[2]), .Y (n_66));
  INVX2 g41701(.A (n_28), .Y (n_29));
  INVX2 g41710(.A (n_967), .Y (n_65));
  INVX2 g41712(.A (n_971), .Y (n_63));
  INVX2 g41713(.A (an_reset), .Y (n_62));
  INVX2 g41714(.A (n_907), .Y (n_61));
  INVX2 g41728(.A (n_60), .Y (n_26));
  INVX2 g41734(.A (direction), .Y (n_60));
  INVX1 g41748(.A (active_out_up_levels[4]), .Y (n_58));
  INVX2 g41749(.A (active_out_up_levels[1]), .Y (n_57));
  INVX2 g41750(.A (active_out_down_levels[4]), .Y (n_56));
  INVX1 g41752(.A (active_in_levels[2]), .Y (n_55));
  INVX2 g41753(.A (active_out_down_levels[5]), .Y (n_54));
  INVX1 g41755(.A (active_out_up_levels[3]), .Y (n_53));
  BUFX2 g41762(.A (counter[5]), .Y (n_11));
  INVX2 g41770(.A (n_968), .Y (n_51));
  INVX2 g41771(.A (n_1024), .Y (n_50));
  INVX2 g41777(.A (n_8), .Y (n_7));
  INVX2 g41779(.A (overload), .Y (n_49));
  INVX2 g41780(.A (n_964), .Y (n_48));
  INVX2 g41796(.A (letout), .Y (n_6));
  INVX2 g41797(.A (n_873), .Y (letout));
  INVX2 drc_bufs41798(.A (n_10), .Y (n_4));
  INVX1 g3(.A (n_1), .Y (n_0));
  NOR2X1 g2(.A (n_705), .B (n_269), .Y (n_1));
  INVX1 g41816(.A (n_974), .Y (n_975));
  NAND2X1 g41817(.A (bell), .B (an_reset), .Y (n_974));
  MUX2X2 g41818(.A (n_857), .B (n_976), .S (counter[14]), .Y (n_977));
  NOR2X1 g41819(.A (n_818), .B (counter[13]), .Y (n_976));
  NAND3X1 g41831(.A (n_990), .B (n_605), .C (n_778), .Y (n_991));
  NOR2X1 g41832(.A (n_810), .B (n_483), .Y (n_990));
  NOR3X1 g41833(.A (n_992), .B (n_504), .C (n_406), .Y (n_993));
  NAND2X1 g41834(.A (n_445), .B (n_768), .Y (n_992));
  NAND3X1 g41835(.A (n_994), .B (n_701), .C (n_330), .Y (n_995));
  NOR2X1 g41836(.A (n_732), .B (n_465), .Y (n_994));
  AND3X1 g41837(.A (n_996), .B (n_658), .C (n_649), .Y (n_997));
  NOR3X1 g41838(.A (buttons_block), .B (n_562), .C (n_527), .Y (n_996));
  NOR3X1 g41839(.A (n_998), .B (n_371), .C (n_430), .Y (n_999));
  NAND3X1 g41840(.A (n_673), .B (n_405), .C (n_335), .Y (n_998));
  MUX2NX1 g41841(.A (n_1000), .B (n_315), .S (n_644), .Y (n_1001));
  NOR2X1 g41842(.A (n_876), .B (n_907), .Y (n_1000));
  MUX2NX1 g41843(.A (n_1002), .B (n_312), .S (n_621), .Y (n_1003));
  NOR2X1 g41844(.A (n_880), .B (n_907), .Y (n_1002));
  NAND2X1 g41845(.A (n_1004), .B (n_577), .Y (n_1005));
  AOI21X1 g41846(.A (n_971), .B (n_259), .C (n_234), .Y (n_1004));
  NAND3X1 g41847(.A (n_1006), .B (n_181), .C (n_525), .Y (n_1007));
  NAND2X1 g41848(.A (n_197), .B (n_205), .Y (n_1006));
  NAND3X1 g41849(.A (n_1008), .B (n_179), .C (n_529), .Y (n_1009));
  NAND2X1 g41850(.A (n_971), .B (n_167), .Y (n_1008));
  NAND3X1 g41851(.A (n_1010), .B (n_285), .C (n_445), .Y (n_1011));
  NAND2X1 g41852(.A (n_971), .B (n_199), .Y (n_1010));
  NAND3X1 g41853(.A (n_1012), .B (n_240), .C (n_418), .Y (n_1013));
  NAND2X1 g41854(.A (n_971), .B (n_254), .Y (n_1012));
  NAND3X1 g41855(.A (n_1014), .B (n_243), .C (n_373), .Y (n_1015));
  NAND2X1 g41856(.A (n_971), .B (n_258), .Y (n_1014));
  NAND2X1 g41857(.A (n_1016), .B (n_310), .Y (n_1017));
  NOR3X1 g41858(.A (active_out_up_levels[5]), .B
       (active_out_down_levels[5]), .C (active_in_levels[5]), .Y
       (n_1016));
  NOR3X1 g41859(.A (n_1018), .B (n_83), .C (n_272), .Y (n_1019));
  NAND2X1 g41860(.A (n_129), .B (n_104), .Y (n_1018));
  NOR3X1 g41861(.A (n_1020), .B (n_204), .C (n_159), .Y (n_1021));
  NAND2X1 g41862(.A (n_80), .B (active_out_down_levels[6]), .Y
       (n_1020));
  OAI21X1 g41863(.A (n_1022), .B (active_out_up_levels[6]), .C (n_163),
       .Y (n_1023));
  NAND2X1 g41864(.A (n_105), .B (active_out_down_levels[6]), .Y
       (n_1022));
  NAND2X1 g41865(.A (buttons_block), .B (an_reset), .Y (n_1024));
endmodule

